### ISSUE TITLE
Feedback form not working

### ISSUE THREAD

**Issue by naught101** [sadko4u/lsp-plugins#1]
When I tried to submit this message to the feedback form at http://lsp-plug.in/?page=feedback, I got an error saying:

`Sorry, something went wrong while submitting form. You may try again some amount of time later.`

I tried again a few times, no luck.

---

Hi LSP!
I really like your plugins, especially the Klangerzueger - there's not much else out there that's as straight-forward for sampling.

I would love to submit some feature suggestions, but it's quite hard to find your github project, because link on the download page is broken - no HREF.

Are you open to suggestions on your plugins? I have a few that would really make Klangerzueger much more useful for resampling.

Cheers
ned

**Comment by sadko4u** [comment]
Hello!

Thanks for report about feedback form, I'll test it.

About plugins - you are always welcome with suggestions and feature requests!
LSP Plugins are only going to be completely open source, so, the GitHub project will be announced only with 1.1.4 release.

Best,
Vladimir

**Comment by sadko4u** [comment]
Fixed feedback form. The problem was related to former server restoration, so google's reCAPTCHA was broken. Now works properly.

**Comment by naught101** [comment]
Cool, thanks :)

So, the features I was thinking for Klangerzueger were:

- file preview in the file load dialog
- pitch/tune control (note and fine tuning)
- Allowing a single sample to be used across a range of midi notes (with pitch shifting away from a centre note).
- looping (start/end, fade length)

I've also been considering a [modification of Helm](https://github.com/mtytel/helm/issues/204) that might cover the same functionality, and I'm not sure which is the better path to tackle. Helm has a lot of nice modulation options that are pretty attractive, but maybe also a bit overkill for a simple sampler.

**Comment by naught101** [comment]
Probably also a filter would be good, and velocity mappable the filter cut-off, and tail cut/fade-out. Some of these things might be easier to do in Helm, since the modulation and filter is already built in.

**Comment by sadko4u** [comment]
I've added your request to our long TODO list.
You may see it in this commit: 362ee16738d520d1ee321e95e4a79abac3bf1abf
I can not guarantee that this feature set will be implemented soon.
Anyway, now we have the point to move to.
I'm closing this topic because initially it was related to the site and now the problem has been fixed.
