### ISSUE TITLE
Dynamic Processor plugin attack/relase don't work as they supposed to

### ISSUE THREAD

**Issue by ents-hqx** [sadko4u/lsp-plugins#103]
Hey,

I have problem with Dynamic Processor plugin, default attack and relase times are not working. If I set some big number(5000ms) it has no effect. But if I change "Ranges 0" attack and relase time and don't even enable Att and Rel knobs, then it uses those high attack and release times. It seems that ranges0 values are like default ones.

Plugin versions tried 1.1.19 and previous release.

Kristjan

**Comment by sadko4u** [comment]
Thanks for a report, I'll explore what's going on.

**Comment by sadko4u** [comment]
Yes' I've reproduced the issue. For mono processor, it seems that 'Attack' control does not have any effect at all.

**Comment by sadko4u** [comment]
Pushed changes to **github-issue-103**: 240158c74372124c485e8664451c1670b9c774e5
Please verify that now is all OK.

**Comment by ents-hqx** [comment]
Hey,

Seems to be working ok! Thanks for a quick fix!

**Comment by sadko4u** [comment]
Merged into **devel** branch: e692e1d6374431d4968886fe5b88427b824e1b88

**Comment by sadko4u** [comment]
Removed **github-issue-103** branch.

**Comment by sadko4u** [comment]
Changes available in 1.1.21 release!
