### ISSUE TITLE
Complete FTBFS on Ubuntu Groovy Gorilla (future 20.10)

### ISSUE THREAD

**Issue by eeickmeyer** [sadko4u/lsp-plugins#104]
Hi there,

Plugins are failing to build from source. See this build log: https://launchpadlibrarian.net/479168308/buildlog_ubuntu-groovy-amd64.lsp-plugins_1.1.19-0ubuntu1_BUILDING.txt.gz

I suspect it's a newer g++ version.

Thanks!

**Comment by sadko4u** [comment]
Hello.
No, it's result of change of LV2 headers. The fix in progress.

**Comment by sadko4u** [comment]
Please try to build from **github-issue-104** branch.

**Comment by eeickmeyer** [comment]
That also seems to have FTBFS: https://launchpadlibrarian.net/479247710/buildlog_ubuntu-groovy-amd64.lsp-plugins_1.1.19+gitd6df650-0ubuntu1_BUILDING.txt.gz

**Comment by sadko4u** [comment]
Pushed the change. Please retry.

**Comment by eeickmeyer** [comment]
That seems to have worked. Thanks!

**Comment by sadko4u** [comment]
Please don't close issues until they will get merged into **master** branch and released.

**Comment by eeickmeyer** [comment]
OK, sure, didn't know your workflow on that.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 4ebc0d08a5c4289063a384380ab243cdc0fd33ab

**Comment by sadko4u** [comment]
Added patch to the **hotfix** branch: 4d901135fb82fa95e668b4d55d05e405f5e620d2

**Comment by sadko4u** [comment]
Removed **github-issue-104** branch

**Comment by sadko4u** [comment]
Changes available in 1.1.21 release!
