### ISSUE TITLE
Multiple listings of MBE8M VST in REAPER

### ISSUE THREAD

**Issue by JamesPeters667** [sadko4u/lsp-plugins#105]
This happens with **1.1.21** binary Linux VST files from SourceForge, and also happened with **1.1.19** (but I assumed at the time it was because I had built the plugins and done something wrong during the build).

In the effects browser of the Linux version of REAPER, there are 8 entries of "Multiband Expander Mono x8" instead of separate entries for the various mono/stereo/lr/midside versions. See image 1 attached. (Only MBE8M exists multiple times, not the other variants.)

I did a clear cache/re-scan of plugins. The same thing happened.

Loading all those plugins shows they are all just the same plugin (Multiband Expander Mono x8).

Examining the reaper-vstplugins64.ini file (which has all the plugin listings for the 64-bit vst plugins), it seems the listing of those particular plugins is inconsistent from one part of the line to the next. See image 2 attached.

I then edited the reaper-vstplugins64.ini file, removing all lines containing lsp_plugins*. A fresh scan of the plugins then resulted in the same duplication. 

I then edited the reaper-vstplugins64.ini file, changing the second part of each line to be like the first part of the line (the first line for example, I renamed "Multiband Expander **Mono** x8" to "Multiband Expander **LeftRight** x8" (etc.) That didn't work. I then gave each plugin a unique number (since I notice that number "757935405" was for every one of those plugins, so I arbitrarily added 1 to each subsequent plugin listing). The effects browser then showed multiples of "Multiband Expander Mono x8" but now also _seemingly_ the other versions. Loading all the Multiband Expander plugins though, despite the different plugin names in the window title bars, each plugin had the same blue LSP button that says "**LSP MBE8M**" (and only 1 in/out for the routing) confirming it's all just the same plugin.

It seems the reaper-vstplugins64.ini file keeps getting re-generated with the erroneous listings, based on what the plugins are reporting to REAPER during a scan.

VST plugin references are contained in other REAPER ini files as well, but only for their names (for the sake of sorting into folders/favorites), so changing those files has no effect on this.

![mbexm_1](https://user-images.githubusercontent.com/64047181/82131735-fee06580-979d-11ea-8404-06b77bc0179b.jpg)

![mbexm_2](https://user-images.githubusercontent.com/64047181/82131738-043db000-979e-11ea-8f22-9cd70b6beb49.jpg)

**Comment by sadko4u** [comment]
The problem is, that I forgot to register Multiband Expander on the Steinberg site. All plugins have the same 4-character VST identifier.

Why didn't you report the problem before I've just released 1.1.21?

**Comment by JamesPeters667** [comment]
My apologies! I didn't even notice the mistake at first (when building the pre-release version with the bugfix for the previous issue). I only realized this a week or so later when trying that plugin for the first time. I don't normally use expansion plugins. Since I'm new to building anything in Linux, I thought I had made a mistake when building 1.1.19. I assumed when you released 1.1.21, I'd download the binaries and it would be "proper" and not "broken like the ones that I built wrong". :-/

**Comment by sadko4u** [comment]
It's my mistake too that I forgot to register VST2 identifiers. Anyway thanks that you've found that problem. Since it's a simple problem, it's very sad that it has not been included into 1.1.21 release.
Here's the change that will fix the problem: 8011a70d2856ab64b72a60f145a700412abd6a53

**Comment by sadko4u** [comment]
Added this patch to the **hotfix** branch so distro builders can include it into build scripts: 84bef7a19351a85ef89d619cb87ac38a074607db

**Comment by JamesPeters667** [comment]
I wish I'd have tested a previous version to confirm this, once I saw the problem in the version I built...but I tend to blame myself more often than others when I'm doing something new. I was a Windows user for too long. Becoming a Linux user is taking me a bit of time. :-)

**Comment by sadko4u** [comment]
Please confirm that all is OK now if it is possible for you to build from sources.

**Comment by JamesPeters667** [comment]
I successfully built the VST plugins with no errors, tested them and confirm this issue is resolved. Thanks!

**Comment by JamesPeters667** [comment]
UNRELATED and maybe not a bug (but I figure I should mention it now just in case):

I'm testing Compressor (stereo version) and I don't seem to notice a difference in sound with different settings of the lookahead control. I also don't notice any plugin delay compensation happening in REAPER when turning the control up past zero. Normally if a plugin requests some lookahead, REAPER will compensate automatically and display the number of samples (and the buffer size) required, right in the fx browser window for the plugin and in the performance meter.

**Comment by sadko4u** [comment]
No, according to the code currently none of the dynamic processor plugins does not report latency.
Please create another issue.

**Comment by sadko4u** [comment]
Available in 1.1.22 release!
