### ISSUE TITLE
Compressor and Dynamics Processor VST plugins don't report lookahead to the DAW

### ISSUE THREAD

**Issue by JamesPeters667** [sadko4u/lsp-plugins#106]
I noticed this in REAPER for Linux. Normally if a plugin requests some lookahead from REAPER, REAPER will compensate automatically and display the number of samples (and the buffer size) required, right in the fx browser window for the plugin and in the performance meter. I don't see this for these plugins. I do however see it for the Limiter plugins.

**Comment by sadko4u** [comment]
Yes, can confirm that dynamic processors are currently not reporting latency.
Will be fixed some time later.

**Comment by sadko4u** [comment]
Created branch **github-issue-106** and pushed changes: deb509311300b132cc466f73fbea4e722ba22835

Please verify that plugins now report their latency.

**Comment by JamesPeters667** [comment]
Branch 106 plugins built and tested (VST only, since I only use REAPER). The Compressor, Dynamics Processor, and Expander plugins now all report their lookahead to the DAW. Tested at 44.1KHz and 48KHz, PDC values are exactly what they're supposed to be at each sample rate. Thank you!

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: d07e8ed4d50cd101dcf5fc43fa3fe1f17a461f68

**Comment by sadko4u** [comment]
Removed branch **github-issue-106**.

**Comment by sadko4u** [comment]
Available in 1.1.22 release!
