### ISSUE TITLE
Numeric input for parameters won't accept decimal or enter from number pad

### ISSUE THREAD

**Issue by JamesPeters667** [sadko4u/lsp-plugins#108]
For the VST plugins (tested in REAPER):

When entering a value for a parameter using the keyboard using the number pad area of the keyboard, the decimal "." and enter key are not recognized.

(Decimal and enter key are recognized from the main area of the keyboard.)

**Comment by sadko4u** [comment]
Thanks for a report, I'll fix it soon.

**Comment by sadko4u** [comment]
Created **github-issue-108** branch and submitted patch: edbb1e5c1ab134157d57603821e7bfe9fcc024b2

For me works as expected. Please verify from your side.

**Comment by JamesPeters667** [comment]
VST plugins built from  github-issue-108, tested. Confirmed that this problem is resolved. Thank you! :)

**Comment by sadko4u** [comment]
Pushed changes to the **devel** branch: 578b9347b1680204771775c49c84c8751190ddb7

**Comment by sadko4u** [comment]
Removed **github-issue-108** branch.

**Comment by sadko4u** [comment]
Available in 1.1.22 release!
