### ISSUE TITLE
EQ nodes in the "display" area can't be grabbed/moved by the mouse initially

### ISSUE THREAD

**Issue by JamesPeters667** [sadko4u/lsp-plugins#109]
This is for the VST plugins, in REAPER.

The first time I load one of the EQs, I'm unable to grab and/or move the nodes in the "display" area in the middle of the plugin using the mouse.

If I close the plugin window and re-open it, I can then grab and move the nodes with the mouse in the "display" area. Also if I adjust a parameter with a knob, afterward I can grab/move nodes in the "display" area.

This doesn't seem to be an issue with the multiband compressors/expanders (the movable frequency division line).

This issue doesn't happen every time I load a plugin, but it happens often.

I recorded a video showing this. I load tracks one at a time, and load 1 plugin to each, and test them. You'll notice when I load plugins on the following tracks, the problem happens:

-track 3
-track 6 (even after closing and re-opening; it took doing that 2 times for it to respond)
-track 8

Here is the video: https://youtu.be/ekkO_B-bGOA

Thanks again. Sorry for reporting bugs so much :)

**Comment by sadko4u** [comment]
Thanks for a report. Don't hesitate to do more reports, this allows to raise the quality of the product.
Some days ago while reimplementing UI library for 1.2.0 version of plugins, I've noticed resembling behaviour of widgets in a test environment.
I suppose I need to back-port these changes to current LSP tree and give you a check.

**Comment by sadko4u** [comment]
Created **github-issue-109** branch and pushed changes: 973dbc0ecb722b0448c7ce58a09edd73fd16bf1e

Please try the UI. If it won't help, then I'll dig a bit deeper.

**Comment by JamesPeters667** [comment]
I built VST plugins from github-issue-109 branch and tested for this behavior. The same behaviour exists, unfortunately.

**Comment by sadko4u** [comment]
It seems that there are good news. This commit should fix the problem: db274c94eec207a57bae14067e354c7cfb06567c
Please confirm.

**Comment by JamesPeters667** [comment]
Branch 109 plugins built and tested just now (VST only, since I only use REAPER). The EQ and Dynamics Processor plugins now all immediately allow their nodes to be grabbed/moved by the mouse in the "display" area. Thank you!

**Comment by sadko4u** [comment]
Merged changes to the **devel** branch: 79970760ee41c871713d8080eab8d8787b20955b

**Comment by sadko4u** [comment]
Removed **github-issue-109** branch.

**Comment by sadko4u** [comment]
Available in 1.1.22 release!
