### ISSUE TITLE
cross compilation

### ISSUE THREAD

**Issue by trebmuh** [sadko4u/lsp-plugins#11]
I'm trying to build a debian package for the LSP plugins. This is done with the pbuilder tool which provides a chrooted environment. Building the 64 bits package on a 64 bits system works as expected. But when trying to build the 32 bits package, it looks like the LSP auto-detection system still consider that it is building on a 64 bits host as indicated by this comment:
> Building binaries for target architecture: x86_64

and thus lead to an error when building with this kind of things:
```
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
```
or
```
/usr/include/c++/6/cmath:41:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
```

Would you have any recommendation/idea?

**Comment by sadko4u** [comment]
How do you build 32-bit packages?
To build 32-bit package from 64-bit environment, you need to execute:
```
make clean
make BUILD_PROFILE=i586
```

**Comment by trebmuh** [comment]
Thanks for having leading me on the right road.
With adding the BRUILD_PROFILE to the building rules, it now works as expected when cross-building.

Thanks @sadko4u for that, for the LSP-plugins, and for releasing those under a libre license.
