### ISSUE TITLE
Crossover plugin

### ISSUE THREAD

**Issue by sadko4u** [sadko4u/lsp-plugins#113]
Crossover plugin is required to split input signal into multiple frequency bands.
The initial topic here: https://linuxmusicians.com/viewtopic.php?f=48&t=11713

**Comment by unfa** [comment]
I double this request.

**Comment by sadko4u** [comment]
I think that can be done up to 1.1.26 release.

**Comment by sadko4u** [comment]
Work is in progress, latest changes to the **github-issue-113** branch already allow to launch mono version of the crossover plugin:

![image](https://user-images.githubusercontent.com/12834464/93004659-ad7c9300-f551-11ea-970f-498fdd7397c9.png)

**Comment by capoei** [comment]
wow, it has realtime graphic of the effect on the overall frequency response? this will be the most advanced crossover ever

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 3397c1486e01489b0c79cf724233f8f5952d97d5

**Comment by sadko4u** [comment]
Removed **github-issue-113** branch.

**Comment by sadko4u** [comment]
Available in 1.1.26 release
