### ISSUE TITLE
graphical glitches in 1.1.22

### ISSUE THREAD

**Issue by magnetophon** [sadko4u/lsp-plugins#114]
For example the stereo multiband gate has a dropdown for "Split" or Bands.
When set to Split it's white area is a few pixels higher and back to the original height, every frame it goes back and forth.
The white areas of "Signal" and "Analysis" sometimes flicker to black for a frame.

This same plugin also doesn't fully fit all the knobs in the window, and when I resize the window, I just get grey in the extra space. 
![screenshot_20200605_163451](https://user-images.githubusercontent.com/7645711/83888843-aa9c2600-a74a-11ea-9b57-e5836ae75af0.png)

**Comment by sadko4u** [comment]
What host do you use?

**Comment by magnetophon** [comment]
Oh, sorry, forgot to mention: the screenshot was a test with jalv.gtk.
I just tried in Ardour and it works fine.

So feel free to close this issue; there is no need to run the plugins in jalv, since there are standalone versions.

**Comment by sadko4u** [comment]
I'll still keep this issue open, will do some additional checks since in Ardour 6 the window doesn't resize when the plugin's child window becomes larger for me.

**Comment by magnetophon** [comment]
Ah, I didn't even know they where *supposed* to scale!
Cool!

**Comment by sadko4u** [comment]
I've fixed glitches in the new version of toolkit and back-ported changes to the current version of LSP tree: a039e7ab6d7e93832aef0f1260aeb11bb45054d9

Now it seems that there won't be any UI glitches anymore.
Anyway you probably should check that there are no performance degradations in the UI.

Changes are available in the **github-issue-114** branch.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: d9ddd920fdc2814684f11618b552d52256c9cb33

**Comment by sadko4u** [comment]
Removed **github-issue-114** branch

**Comment by sadko4u** [comment]
Available in 1.1.24!
