### ISSUE TITLE
Controls UI Mismatch

### ISSUE THREAD

**Issue by p1839251** [sadko4u/lsp-plugins#117]
Hello,
I still haven't gone through all your plugins, fortunately, there are a bunch of them.
Apparently all the compressor plugins are affected.
Knobs called '**Thresh**' are remained '**Level**' in the automation list.
For example: LSP Multiband Compressor Stereo x8's knob is called '**Attack Thresh**', however, it's 'Attack Level 0' in the list

**Comment by sadko4u** [comment]
Created **github-issue-117** branch and pushed commit: a225e36c14d07abb7eb75ac70c92f1722bded6b4

@p1839251 
Are you available to build from **github-issue-117** and verify that all is OK now?

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 592edf50da2dbcce259c3023b17aa482af05d444

**Comment by sadko4u** [comment]
Available in 1.1.24!
