### ISSUE TITLE
Mark atom ports as connection optional

### ISSUE THREAD

**Issue by brummer10** [sadko4u/lsp-plugins#123]
Would it be possible to mark the atom ports as connection optional, to allow the use in hosts which didn't support atom ports.
All tests I've done so far with LSP plugins with unconnected atom ports works out stable. True is that some things wouldn't work without atom ports, but it is very usable to load and run presets with a reduced generic UI.

**Comment by sadko4u** [comment]
Pushed changes to **github-issue-123** branch: 8a5ced3bb6c98b4440cc844d7a1b9795055bffaa

Please check that these changes satisfy your requirements.

**Comment by brummer10** [comment]
https://s12.directupload.net/images/200704/ys6fnsfx.png

works like a charm. Thank you a lot.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 5d76b19be638c59e50b40780cf518d7b09c25dee

**Comment by sadko4u** [comment]
Removed branch **github-issue-123**

**Comment by sadko4u** [comment]
Available in 1.1.24!
