### ISSUE TITLE
Multi Sampler does not load settings file

### ISSUE THREAD

**Issue by Daniele71** [sadko4u/lsp-plugins#124]
Hello, I've made a simple drumkit with Multi Sampler stereo, then exported the settings. So I've a drum_1.cfg file. Loading this file does nothing. No matter if I use the Stereo or Multi output version.

System:
MultiSampler as LV2 plugin
Ardour 6
Opensuse Tumbleweed

Configuration file attached.
[Drum_1.cfg.zip](https://github.com/sadko4u/lsp-plugins/files/4874919/Drum_1.cfg.zip)

**Comment by sadko4u** [comment]
There's an error in file, please remove the following lines:
```
 = 

 = 

 = 
```

And all shall be probably OK. Please report the result after manual editing.

But anyway there seems to be problem with exporting file settings. Thanks for a report.

**Comment by Daniele71** [comment]
> There's an error in file, please remove the following lines:
> 
> ```
>  = 
> 
>  = 
> 
>  = 
> ```
> 
> And all shall be probably OK. Please report the result after manual editing.
> 
> But anyway there seems to be problem with exporting file settings. Thanks for a report.

Yep, it's working now ! Thanks.

**Comment by sadko4u** [comment]
Could you please tell the version of package? I can not reproduce the invalid file export on the **devel** branch.

**Comment by Daniele71** [comment]
> Could you please tell the version of package? I can not reproduce the invalid file export on the **devel** branch.

Maybe an old version (not sure which one..).. now with 1.1.22 (opensuse package) export seems working fine..
Sorry for the noise..

**Comment by sadko4u** [comment]
No problem. Anyway, I've added the package version to the header of the configuration file.
Now I don't need to ask the version of package when the configuration file is provided.

**Comment by sadko4u** [comment]
Will close the ticket after 1.1.24 release

**Comment by sadko4u** [comment]
Available in 1.1.24!
