### ISSUE TITLE
Suddenly latency meter shows crazy latency

### ISSUE THREAD

**Issue by v-fox** [sadko4u/lsp-plugins#126]
I use pretty long pipeline of:
* lsp-plugins-latency-meter OUT and all sources
* lsp-plugins-spectrum-analyzer-x4 IN
* Calf Stereo Tools
* lsp-plugins-para-equalizer-x16-stereo
* Calf Bass Enhancer
* Calf Multiband Enhancer
* lsp-plugins-gate-stereo OR lsp-plugins-surge-filter-stereo
* lsp-plugins-mb-compressor-stereo
* lsp-plugins-loud-comp-stereo
* lsp-plugins-limiter-stereo OR Calf Miltiband Limiter
* lsp-plugins-spectrum-analyzer-x4 OUT
* lsp-plugins-latency-meter IN
* DAC

Usually it was showing from 13-to-19 ms of latency depending on lookahead but on my recent measurement while using #122 branch and adding lsp-plugins-loud-comp-stereo it suddenly jumped to 97-to-106 ms. So even if I set bypass on every single plugin it shows 97 ms. What could be the cause ? Has meter gone crazy or something introduces delay even with bypass ?

**Comment by sadko4u** [comment]
Loud compensation module uses FFT transformations and may introduce significant latency.
If you use FFT frame of 4096 samples, then your latency at 48 kHz sample rate is about  4096/48 = 85 milliseconds.

**Comment by sadko4u** [comment]
All LSP plugins have soft bypass which crossfades the dry/wet signal when switching.
Loud compensation plugin introduces adds delay to the signal even in bypass mode. That was made to not to confuse the listener by shifting sound when switching between bypassed and non-bypassed modes.

**Comment by v-fox** [comment]
Yep, seems it was exactly that >_< Its CPU burden didn't seem to be significant but that delay is a no-go for casual use.
I think listener would be more "confused" by volume jumps when gain knobs are bypassed rather than delay. I know I am.
