### ISSUE TITLE
1.1.22 VERSION is undefined in Makefile

### ISSUE THREAD

**Issue by barjac** [sadko4u/lsp-plugins#127]
Looks like VERSION was changed to LSP_VERSION for the files section, but left at VERSION for the libraries.

**Comment by sadko4u** [comment]
Thanks for the report. This has been already fixed in **devel** branch.

**Comment by barjac** [comment]
OK fine, thanks, I patched our package for now.

**Comment by sadko4u** [comment]
Please don't close issue until the new release appears. I'll close it when it will be ready.

**Comment by sadko4u** [comment]
Available in 1.1.24!
