### ISSUE TITLE
Build fails on FreeBSD/i386

### ISSUE THREAD

**Issue by yurivict** [sadko4u/lsp-plugins#13]
See the build log: http://beefy10.nyi.freebsd.org/data/112i386-default/484272/logs/lsp-plugins-lv2-1.1.4.0.20181102.log

**Comment by sadko4u** [comment]
Interesting. I see that makefile didn't detect target CPU architecture.
I think I need to test i386 build under virtualbox.

**Comment by sadko4u** [comment]
Created **github-issue-13** branch.
Should be fixed in this commit: e29c646ea99f22d8068f11615f10a804e4c9676d
Please verify

**Comment by yurivict** [comment]
I updated the port, and will reopen it if it breaks again.
Thank you for fixing it.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: c2721d6431b3f6dc8d7dd337c7cbc0776d74b199

**Comment by sadko4u** [comment]
Removed **github-issue-13** branch, all changes are in **devel** branch now.
