### ISSUE TITLE
LSP impulse response stereo (and probably mono) showing "unknown error" when sharing between computers

### ISSUE THREAD

**Issue by cyrusadkisson** [sadko4u/lsp-plugins#131]
![lsp_imp_stereo_ard6](https://user-images.githubusercontent.com/2284720/87860362-ea8a2780-c90a-11ea-9cb6-2699ed59845b.jpg)

I share Ardour (6) sessions between computers very frequently and use common locations for wav files (and sf2 files and whatever else) so that the new computer can open the session and run with it immediately. This is for sharing across a team of session makers.

I'm trying to open this session on a new machine just now and all of the instances of LSP Impulse Responses are broken. All say "unknown error" and halt audio at the point of the plugin in the strip. 

And yet all the presets that should be in the dropdown are there. And the wav files are in the right places. And choosing a preset works just fine (although it overwrites the settings which is very bad). It's just that the wav file doesn't load.

Any idea what's going on with this?

**Comment by sadko4u** [comment]
Are you available to build LSP plugins from source?

Build the plugins with such option:
```
rm /tmp/lsp-plugins-lv2.log
make clean
make tracefile
make install
```

Then try to open your session (which will fail).
When it fails, close the session without saving, archive the ```/tmp/lsp-plugins-lv2.log``` file and ship it here.

**Comment by cyrusadkisson** [comment]
Pilot error. The wav files were in the wrong place.

My bad and thanks for the fast response.

**Comment by sadko4u** [comment]
OK, no problem.
