### ISSUE TITLE
Impulse response plugin creating unnecessary chains of symlinks

### ISSUE THREAD

**Issue by cyrusadkisson** [sadko4u/lsp-plugins#132]
When i open the wav selection window and choose a file, I expect the ardour link (under externals/) to point to that file.

Instead, LSP is doing some weird stuff where's linking to links that I'm not even using anymore. 

...externals/$ ls -l
total 8
lrwxrwxrwx 1 cyrus cyrus  41 Jul 22 11:56 'ACE Ampeg 2b.wav' -> '/dev/shm/bass/ACE Ampeg 2b.wav'
lrwxrwxrwx 1 cyrus cyrus  41 Jul 22 11:56 'ACE Ampeg 3b.wav' -> '/dev/shm/bass/ACE Ampeg 3b.wav'
lrwxrwxrwx 1 cyrus cyrus 101 Jul 22 09:13 'ACE Mes 412 2b.wav' -> '/home/cyrus/.lv2/LSP_Impulse_Responses_Stereo_Custom_Rect_2b_3b.lv2/ACE Mes 412 2b.wav'
lrwxrwxrwx 1 cyrus cyrus 101 Jul 22 09:13 'ACE Mes 412 3b.wav' -> '/home/cyrus/.lv2/LSP_Impulse_Responses_Stereo_Custom_Rect_2b_3b.lv2/ACE Mes 412 3b.wav'

The first two are correct, pointing to /dev/shm. 
The second two are incorrect, pointing to the old location.

...externals/$ ls -l /home/cyrus/.lv2/LSP_Impulse_Responses_Stereo_Custom_Rect_2b_3b.lv2/ACE\ Mes\ 412\ 2b.wav 
lrwxrwxrwx 1 cyrus cyrus 47 Jul 22 11:55 '/home/cyrus/.lv2/LSP_Impulse_Responses_Stereo_Custom_Rect_2b_3b.lv2/ACE Mes 412 2b.wav' -> '/dev/shm/electric/ACE Mes 412 2b.wav'

This is not good because it makes sessions non-portable. If both computers have /dev/shm (as expected), then everything would work. But if one of the machines is missing this middle link, then it breaks.

And I can't fix it by deleting the plugin and putting it back in. This middle-man linking still happens. 

Ideas? Is this an ardour issue?

**Comment by cyrusadkisson** [comment]
Yes, just tested again to make sure I wasn't going completely insane. 

1. open session 
2. delete LSP plugin 
3. re-add LSP plugin 
4. Select wav files from /dev/shm (no presets at all) 
5. close session 
6. check externals/ 
7. see the wav files I chose linked through /.lv2/oldpresetname/

Makes no sense to me at all.

**Comment by sadko4u** [comment]
LSP Plugins personally don't do any symlinks.

All symlinks are performed by the [State::mapPath](http://lv2plug.in/ns/ext/state#mapPath) calls. When plugin stores the state, the ```abstract_path``` is called. When plugin loads state, it automatically unmaps the file by ```absolute_path``` call.

The known problem is, that it doesn't work properly for **lilv**: lilv doesn't return the original file name. Instead of this, **lilv** returns the name of symlink created by itself.

Please consider reading the following tickets:
https://github.com/sadko4u/lsp-plugins/issues/119
https://github.com/sadko4u/lsp-plugins/issues/120
https://github.com/lv2/lilv/issues/13
https://github.com/lv2/lilv/issues/37

Currently I think your problem is a result of lilv bugs.

**Comment by cyrusadkisson** [comment]
I figured out the issue. You create a session. You add a plugin. You choose a preset. You SAVE the preset.

Now externals/ has the file.wav pointing to /.lv2/presetname...

You open the session, you delete the plugin.

The externals/file.wav STAYS and it continues pointing at the preset location.

You add the plugin again from scratch. You choose wav files manually (no preset) thinking this will link directly to the locations.

Wrong.

Ardour/LSP/whatever will not overwrite the existing link or change its pointer. So it will continue to link through the /.lv2/oldpresetname. 

How do we fix this? From within Ardour? LSP? Somewhere else? Otherwise, I have to manually delete links every time.

**Comment by x42** [comment]
If you save a preset, this effectively make the plugin use the preset (and keep track of modification relative to the preset).
When saving a preset, the file must be copied to the preset folder. That is the only way to ensure that the preset will remain available and independent.

**Comment by sadko4u** [comment]
@cyrusadkisson , again: the plugin just maps/unmaps paths with LV2 calls which are supposed to work as described. If calls don't work as described, then that's all the problem of **lilv**.

**Comment by cyrusadkisson** [comment]
@x42 There's more. Keep reading. If you delete the plugin entirely and try again from scratch, choosing the wav files directly and avoiding presets altogether, it will STILL link through the presets folder because the link in $SESSIONFOLDER/externals never got deleted and is not overwritten with your new preferences.

**Comment by x42** [comment]
Obviously the plugin state is still there. even though you remove it from a session.

**Comment by cyrusadkisson** [comment]
Why is that obvious? You remove the plugin. The state should be removed. 

And if you add the plugin again, the new state should overwrite whatever stale state exists.

No?

**Comment by sadko4u** [comment]
I think @drobilla should take an attention to this case which probably will speed-up fix of lilv bugs.

**Comment by sadko4u** [comment]
I'll mark it as an 'UPSTREAM BUG' currently.

**Comment by drobilla** [comment]
These are host bugs.  Please stop randomly pointing at lilv and expecting me to sort everything out.

Issues with Ardour are best filed as, well, issues with Ardour.  _If_ they are lilv issues too, then they will make it there.

**Comment by sadko4u** [comment]
I think this issue can be closed at this moment.
