### ISSUE TITLE
(regression) Limiter oversampling causes stereo phase mismatch

### ISSUE THREAD

**Issue by marcan** [sadko4u/lsp-plugins#134]
In at least 1.1.22 and 1.1.24, steps to reproduce:

* Have a 2ch mono source (L=R)
* Send it to LSP Limiter Stereo
* Set Oversampling to something other than None
* Invert the phase of one channel in the output and downmix to mono

The output should be silent. Instead you get some audio. It seems the phase offset between L and R is equal to the number of lobes in the kernel (3 samples for 3L, 2 samples for 2L).

With songs this causes subtle stereo issues (output is lopsided) and also kills mono compatibility (severe comb filtering).

This did not happen in 1.1.10, so it's a regression.

**Comment by sadko4u** [comment]
Thanks for finding out the problem and submitting the patch.

Changes merged to **devel** branch and will be available in 1.1.26 release: b4f7f9b183191d9db0e32d461b899b4902b3bf41
