### ISSUE TITLE
Convolver leaks raw signal with large FFT buffers

### ISSUE THREAD

**Issue by x42** [sadko4u/lsp-plugins#137]
I found this when doing NULL tests:

 * play the same signal into two convolvers, polarity invert one. 

**Expected behavior**: The signal should zero out to below -100 dB (due to processing in the freq domain subtle difference depending on implementation are expected).

**Issue**: LSP convolver produces audible results around -20dB, if and only if the FFT-frame size is above 4K
http://robin.linuxaudio.org/tmp/conv-test.mp3  -- opening the LSP GUI and changing the FFT size to 4K or lower and it nulls to -105 dB.

Ardour6 session -- http://robin.linuxaudio.org/tmp/conv-test.tar.xz comparing to (https://x42-plugins.com/x42/x42-zconvolver, but any other convolver will do, too)

Ardour test-setup:

![image](https://user-images.githubusercontent.com/30246/92281747-922fd900-eefc-11ea-8427-8a37d71426c5.png)

**Comment by x42** [comment]
This is 1.1.24 (c95e356aee1) compiled from git, on x86_64 linux on an AVX capable processor (in case this matters).
If you need more information.. please let me know.

**Comment by sadko4u** [comment]
I've performed the capture of difference: https://imgur.com/kDMewat I don't see anything in the diff but the output of LSP convolver gives audible pops in the signal. Hmmm.

**Comment by sadko4u** [comment]
Reproduced the issue, got stable clicks:

![image](https://user-images.githubusercontent.com/12834464/92285882-248ca880-ef0e-11ea-9731-e96e5373c183.png)

**Comment by sadko4u** [comment]
Pushed changes to **github-issue-137** branch.
@x42 please verify on your system, too.

**Comment by x42** [comment]
Fix confirmed.
Now NULL tests succeeds for all FFT frame sizes! Thanks for the quick fix!

It also works correctly with partial cycles (non power of two process callbacks - e.g. looping, vari-speed).
This issue can be closed.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: bc905c3881d5c5fb8da92669eb493bf9726cd33f

**Comment by sadko4u** [comment]
Will close the issue after release.

**Comment by sadko4u** [comment]
Removed **github-issue-137** branch.

**Comment by sadko4u** [comment]
Available in 1.1.26 release
