### ISSUE TITLE
Sampler issue with LV2 1.18

### ISSUE THREAD

**Issue by janisl** [sadko4u/lsp-plugins#138]
After upgrading lv2 to version 1.18 I have the following issues with stereo sampler plugin in Ardour:

- When loading existing project sampler plugins have no audio pin configuration.
- Add new MIDI track doesn't list LSP samplers as available instruments anymore.
- If I add new MIDI track with general midi synth, remove it and add sampler using plug-in manager audio pins are not automatically connected.

Using Gentoo Linux.

**Comment by sadko4u** [comment]
Which version of Ardour do you use to reproduce the case?
Which build of plugins do you use? Have you tried to build plugins from source?
Which version of plugins do you use?

**Comment by janisl** [comment]
Ardour 6.2
LSP plugins 1.1.24, built from source.

**Comment by sadko4u** [comment]
Currently I can not reproduce the issue on my system.
At least, Ardour allows me to select the Sampler/Multisampler plugin as an instrument for MIDI track.
Have you tried the official build of plugins?
Did you build plugins from source using portage or manually according to the build instruction?
I suppose something is dependent on your system compilation flags or some other system problems.

**Comment by janisl** [comment]
Plugins are built with portage. Will try official build. The problem appears to be related to lv2 library, if I downgrade it to 1.16 it works fine.

**Comment by sadko4u** [comment]
Try also to build plugins manually. I'm currently building with 1.1.18 library and don't meet any issues.

**Comment by sadko4u** [comment]
@janisl Any results/observations?

**Comment by janisl** [comment]
I did some digging into the source code and found the issue. In lv2 version 1.18 the category was changed from "Instrument" to "Instrument Plugin", so the first check for instrument that Ardour does fails. And the second check also fails because sampler plugins have audio inputs (why?). Will report this to Ardour team.

**Comment by sadko4u** [comment]
> I did some digging into the source code and found the issue. In lv2 version 1.18 the category was changed from "Instrument" to "Instrument Plugin"

The diplayed category name has been changed? I see no changes in TTL.

> And the second check also fails because sampler plugins have audio inputs (why?)

This is useful when you want to chain instruments one by another on the same bus/track. The next just adds something new to the signal from previous instrument.

**Comment by janisl** [comment]
https://github.com/lv2/lv2/blob/master/lv2/core/lv2core.ttl
Line 418

**Comment by sadko4u** [comment]
> https://github.com/lv2/lv2/blob/master/lv2/core/lv2core.ttl
> Line 418

Ah, label has changed, not URI of the class.

**Comment by sadko4u** [comment]
Is there any related discussion/bug in upstream?

**Comment by janisl** [comment]
I have no idea

**Comment by sadko4u** [comment]
@x42 please take attention to this topic.

**Comment by x42** [comment]
Likely fixed in https://github.com/Ardour/ardour/commit/c01b7b78423e2eef98a061f960d49e94a2bf2502

**Comment by sadko4u** [comment]
@janisl is is possible for you to check on your system?
@x42 thanks for changes.

**Comment by janisl** [comment]
Yes, that fixes it.

@x42 The ID of the bug I created in Ardour bug tracker is 8407. You can close it now.

**Comment by sadko4u** [comment]
Good!
