### ISSUE TITLE
tag scheme broken

### ISSUE THREAD

**Issue by dvzrv** [sadko4u/lsp-plugins#139]
@sadko4u it seems you have a typo in your latest release. It is [lsp-plusings-1.1.26](https://github.com/sadko4u/lsp-plugins/releases/tag/lsp-plusings-1.1.26) but should really be `lsp-plugins-1.1.26`.

This is a bit problematic, because this tag will now always order before any `lsp-plugins-` prefixed tags. Additionally this release breaks assumptions of download locations when packaging lsp-plugins (e.g. the link for the sources would usually be https://github.com/sadko4u/lsp-plugins/releases/download/lsp-plugins-1.1.26/lsp-plugins-src-1.1.26.tar.gz but now it is https://github.com/sadko4u/lsp-plugins/releases/download/lsp-plusings-1.1.26/lsp-plugins-src-1.1.26.tar.gz)

Would it be possible to entirely drop prefixing for the next release (e.g. just `1.1.27`) as prefixing is not really useful (and potentially error-prone).

**Comment by sadko4u** [comment]
Sorry. Just fixed.
I'm already thinking on getting rid of prefixing.

**Comment by sadko4u** [comment]
I've set up tags for all releases without prefixes (previous tags have also been kept).

**Comment by sadko4u** [comment]
Further releases will be tagged without `lsp-plugins-` prefix.
