### ISSUE TITLE
Multiband Limiter

### ISSUE THREAD

**Issue by v-fox** [sadko4u/lsp-plugins#140]
ML was often [previously discussed](https://github.com/sadko4u/lsp-plugins/issues/122#issuecomment-656901985) which lead to great improvement to the limiter with ALR & compression features and analysis of CML's shortcomings (mainly, deficient crossover and lack of latency reporting) which is for a long time was considered a golden standard of limiters for Linux distros.

However, LSP's own potential future ML might have its own caveats in its design. For example, I've noticed that low-frequency/bass droning is less distorted and annoying, when hit with ALR, when having massive release time, something close to a second or more. But that might not work well for the whole spectrum. That might explain why CML automatically puts different release time for each band with massive difference between lowest and highest frequencies. Optimal attack might also differ but I'm not sure about that.

**Comment by sadko4u** [comment]
Yes, Multiband limiter is a very interesting plugin that should be added to the LSP plugin set. I believe I'll start development of such plugin in the nearest future.

**Comment by sadko4u** [comment]
Finally, it became available in 1.2.8!
