### ISSUE TITLE
Change ladspa label to not include the project URI

### ISSUE THREAD

**Issue by kazuoteramoto** [sadko4u/lsp-plugins#148]
I use the ladspa plugins on various cli and config files, for example on either [`dsp`](https://github.com/bmc0/dsp), `ffmpeg` or `pulseaudio`. In those scenarios we need to set the correct label, currently lsp-plugins set the label to something like:

```
http://lsp-plug.in/plugins/ladspa/compressor_stereo
```

I feel like this is too verbose and make writing a command line or a config file a little cumbersome. For example on ffmpeg:
```
ffmpeg -i input.flac -af ladspa=file=lsp-plugins-ladspa:'http\\://lsp-plug.in/plugins/ladspa/compressor_stereo' -y output.flac
```

The value is defined by the macro `MOD_PLUGIN(plugin, ui)` in `src/container/ladspa.cpp` that call `LSP_PLUGIN_URI(ladspa, plugin)` we could change the last part to just `#plugin` and use the plugin name as label. In this case the example becomes:

```
ffmpeg -i input.flac -af ladspa=file=lsp-plugins-ladspa:compressor_stereo -y output.flac
```

What you think about this?

**Comment by sadko4u** [comment]
I think that it will at least break all saved sessions where LADSPA plugins are used.
Since LADSPA is currently used very rarely and replaced with LV2, I believe there are not so many hosts that will use pure LADSPA plugins.

From the ladspa.h:
```C

  /* This numeric identifier indicates the plugin type
     uniquely. Plugin programmers may reserve ranges of IDs from a
     central body to avoid clashes. Hosts may assume that IDs are
     below 0x1000000. */
  unsigned long UniqueID;

  /* This identifier can be used as a unique, case-sensitive
     identifier for the plugin type within the plugin file. Plugin
     types should be identified by file and label rather than by index
     or plugin name, which may be changed in new plugin
     versions. Labels must not contain white-space characters. */
  const char * Label;
```

So changing label is pretty risky for compatibility.

**Comment by sadko4u** [comment]
By the other side, using URI in the label allows to uniquely identifiy plugin within any shared object file.
This was deliberately taken from LV2 standard.

**Comment by kazuoteramoto** [comment]
> So changing label is pretty risky for compatibility.
> ...
>  This was deliberately taken from LV2 standard.

I see, now I understand why this is different on lsp-plugins compared to the others ladspa plugins I usually use, that have simple labels.

Thanks for the answer, I'm gonna close the issue, considering the current value is by design and the risk involved for a pure UX change.
