### ISSUE TITLE
Multi-tap delay plugin

### ISSUE THREAD

**Issue by unsaph3** [sadko4u/lsp-plugins#149]
Is it possible to create a LSP based version of the LV2 plugin pitch-delay that allows for multiple configurable hits, either in MS or synced to tempo and using musical notation?

**Comment by sadko4u** [comment]
The description is very messy.
Please try to provide more detailed information:
- What plugin should do and how the base algorithm should work.
- What are main settings.
- How do these settings affect the behaviour of plugin.

**Comment by sadko4u** [comment]
Also I believe your request is some way similar to #136

**Comment by unsaph3** [comment]
I can't find a link to the lv2 plugin I mentioned, but it's in the repositories if you wanted to check it out.

A multitap delay would be (as an example) one that allows for a delay on the half note, then the quarter note, then the 8th note - because these are all different ms values, it gets messy to just try to get a tap-tempo function to make it work (which is why it's similar to 136, but not identical).

A good multitap delay plugin to look at as an example is https://www.tracktion.com/products/daw-essentials-collection/attachment/daw-essentials-delay-studio_2x - they have their example set as a straight delay, but it can be configured to where each delay is a different ms value.

**Comment by sadko4u** [comment]
I've got the delay prototype plugin:
![image](https://user-images.githubusercontent.com/12834464/101843294-f5b04f00-3b5a-11eb-855e-566d5dee837c.png)

- Allows to select up to 8 different tempos.
- Allows to use up to 16 delay lines.
- Each delay line allows to compute the delay time based on:
  - another delay processor's time;
  - specified tempo and notation-based delay;
  - exact delay time specified in seconds;
- Each delay line allows to set the feedback delay which should be not greater than the processor's self delay.
- Up to 256 seconds delay is possible. To not to consume a lot of memory, the maximum delay time is configured via dedicated combo.
- Gain, panning and delay values are smoothed and can be automated without clicks/pops/etc.

Any ideas of what else can be added to the plugin?

**Comment by unsaph3** [comment]
Wow. I am floored.

Making sure we have all the bases covered:
- The tempo will sync to a project in a DAW correct? (This is super
important since there are songs I have in Ardour that change tempo over
time and I'd like the delay to change with that)
- I'm seeing an overall panorama %. Is that going to go from -100 to 100?
If so, what do the negative values do?
- In that vein, I'd make the stereo spread of the delays a little clearer.
Having a pan knob and spread knob per delay would add more to the UI, but
create no need for the panorama. If you're doing a panorama, I'd have a
panning and then spread for the master section of the plugin.

All in all, great work. Can't wait for this to be finalized so I can play
with some crazy multi-tap delay stuff on guitar!

Thanks again for your hard work.
- Jeff

**Comment by sadko4u** [comment]
> The tempo will sync to a project in a DAW correct?
You may use synced and unsynced tempos, overall are 8. To make it sync with DAW, just 'Sync' button should be pressed and lighting.

> Is that going to go from -100 to 100
Here -100 means leftmost, +100 means rightmost channel.

> Having a pan knob and spread knob per delay would add more to the UI, but
Here (for the mono example) you may pan the first delay straight to left, another delay - straight to right, the third delay - whenever you want (for the center, for example).
For the stereo version, each of the stereo channels will be possible to pan to left and right. So with two panning knobs you'll be able to control the panorama and spread of the signal.

> Can't wait for this to be finalized so I can play
I'm still thinking what else can be improved...

**Comment by unsaph3** [comment]
Okay - do you have a screen shot of what the stereo version would look
like? I don't work much with mono - even if I use a mono signal by the time
we get to delay in the signal chain, I'm usually using stereo plugins. I
suspect this is true of most experienced users who are familiar with signal
chain best practices.

I appreciate the sync option per tap. That is genius! Being able to create
tension as a tempo escalates is so cool!

I'd recommend the values on the panorama go from L100 to R100 on the
display to make that a little clearer for end-users, or having a L and R at
the furthest points on the knob might also do the trick.

Let's dive a little deeper.
- Will the individual delay values, sync option, and pan be able to be
automated?
- What about simply giving the user the option to add taps (starting with
2), and having them operate on a scroll bar? (This could get super CPU
intensive and if the code behind this is a nightmare, hard nope)
- Is there a global feedback option - as a hypothetical 0 being the single
tap that's programmed (scaling all the feedback values to 0) and 100 just
using the track feedback values? This is more for automation and may not
actually need to be a value with a knob.

Finally, how do you feel about me sharing the screenshot on Unfa's discord
and crowd-sourcing some suggestions?

**Comment by sadko4u** [comment]
> do you have a screen shot of what the stereo version would look like

Currently no, it's in design. But it won't differ much except that panorama knobs will be doubled (for left and right channel).

> I'd recommend the values on the panorama go from L100 to R100 on the
display to make that a little clearer for end-users, or having a L and R at
the furthest points on the knob might also do the trick.

I'm currently following the same pattern as for other plugins panning is done. Maybe after we get the 1.2.0 with many UI improvements, I'll be able to review this.

> Will the individual delay values, sync option, and pan be able to be automated?

All values can be automated. The only one thing that can give zipper noize is the equalizer.

> What about simply giving the user the option to add taps (starting with 2), and having them operate on a scroll bar?

This is not trivial for current UI generator. Maybe after the 1.2.0.

> Is there a global feedback option

It's currently possible to turn-off the feedback for all delay lines with single button at the top in 'Master' section.
Do you mean I also need to add the gain control that attenuates all feedback values for all delays simultaneously?

> Finally, how do you feel about me sharing the screenshot on Unfa's discord and crowd-sourcing some suggestions?

That would be good.

**Comment by unsaph3** [comment]
Okay, like most of your plugins, do not drink and operate. Now that I'm not
drinking, distracted studying network technologies and basic A+ cert
material ... I dove into this again. The panorama function is per delay,
the same as the EQ?! My mind is blown! This is the tits. Easily will become
my new favorite delay plugin (currently been using Calf Vintage Delay).

Not really related to this, but do you have any inclination to take
submissions of user presets for your plugins and add them into the core
plugins? This is a plugin that could definitely use that, but the multiband
compressor and gate might also be good candidates.

Thanks again for all your hard work.

- Jeff

**Comment by sadko4u** [comment]
> The panorama function is per delay, the same as the EQ

Yes, you may delay the original signal, EQ it and then pan it as you wish.

> Not really related to this, but do you have any inclination to take
submissions of user presets for your plugins and add them into the core
plugins?

Presets are supported in the UI. You just need to export configuration files and submit them to another future request or to the pull request. Here is the example of preset files:
https://github.com/sadko4u/lsp-plugins/tree/master/res/presets/simulation/room_builder

**Comment by unsaph3** [comment]
Gotcha. I will work on some presets for the various plugins that I use and
submit them :)

So far nobody on Discord has had any suggestions for you as far as
features, and now that you've walked me through the features you've already
added, the only thing I would wish for is a master gain on all the
feedback, rather than a simple on/off. For automation and mixing, having
the feedbacks of the delays come in and go out rather than simply turn on
and off is more useful.

Keep up with the great work. I've been keeping track of the hardware
drivers work you do for the Scarlett devices too and I know a ton of people
appreciate it.

- Jeff

**Comment by sadko4u** [comment]
We're almost done. Here's the stereo version with a bit polished UI:
![image](https://user-images.githubusercontent.com/12834464/102287243-16a5e500-3f4b-11eb-8ae6-71663ecf77e4.png)

**Comment by unsaph3** [comment]
This looks a lot more polished than the version I saw!

**Comment by sadko4u** [comment]
Merged all related changes into **devel** branch: 819a54b2bef5e7453d424519a6fdac74dba13cb2

**Comment by sadko4u** [comment]
Available in 1.1.28 release!

**Comment by unsaph3** [comment]
Hey Vladmir, I've finally cracked open your awesome plugin, and I have some
feedback for you after playing with it in Carla. I hope it's useful.

To start, this is the deepest delay plugin I have ever used, and it took me
almost a half an hour to get my bearings in it. That's a good thing in this
case, as it means that you have a lot to work with. I strongly suggest
having a delay line set up as the default that behaves like a normal delay,
i.e. half notes linked to tempo or quarter notes. It took me almost 5
minutes of playing with the delay lines to get delay at all.

Each delay line added adds noise. Not sure if that's intentional, but it's
definitely there.

The delay knobs should work on a logarithm when you move them (so it goes
from 0ms-1sec at the same rate it goes from 1sec-15sec, and 15sec-150sec.
This would make it much easier to get immediate slapback delay type effects
in the plugin, independent of tempo.

I'd make the tempo menu open on click or right click on the time signature.
This would make it more immediately apparent that it can be manipulated.

The single biggest thing though, is set the multiplier on the tempo to 1 as
both its lowest value and as the default value, have it be able to be an
integer (so values of 1.5 are possible), and again, move on a logarithm -
1-10 would go at .5 intervals, 10-50 at single values, and 50+ at 10. This
would make it way more configurable, as well as making dotted note type
delays easier to program.

I really appreciate being able to set gain, EQ, and panning independent on
each delay line - that's the coolest thing. I'm working on designing a tape
delay type effect with muted bass, low highs, and emphasized mids (attached
configuration file for you to be able to play with).

Thanks again for your hard work. Where do I go to subscribe and donate
monthly instead of create a one time donation (paypal preferred)?
- Jeff

**Comment by sadko4u** [comment]
Hello, @unsaph3!

> Hey Vladmir, I've finally cracked open your awesome plugin, and I have some
feedback for you after playing with it in Carla. I hope it's useful.

Nice.

> Each delay line added adds noise. Not sure if that's intentional, but it's
definitely there.

There is no special noise suppression for the signal. The signal goes 'as is', I mean, as it was captured by your device. If you have relatively noticeable noise at the input , then it will be repeated by each delay line and added to the original track. So yes, in this case it will add the noise.

> The delay knobs should work on a logarithm when you move them

Good suggession. I also thought to make it logarithmic but ended up with linear scale. Maybe I was wrong.

> The single biggest thing though, is set the multiplier on the tempo to 1 as
both its lowest value and as the default value, have it be able to be an
integer (so values of 1.5 are possible), and again, move on a logarithm -
1-10 would go at .5 intervals, 10-50 at single values, and 50+ at 10. This
would make it way more configurable, as well as making dotted note type
delays easier to program.

OK, this is knob tuning. Not too hard to fix.

> I really appreciate being able to set gain, EQ, and panning independent on
each delay line - that's the coolest thing. I'm working on designing a tape
delay type effect with muted bass, low highs, and emphasized mids (attached
configuration file for you to be able to play with).

Nice to see that plugin was very useful for you.

> Where do I go to subscribe and donate monthly instead of create a one time donation (paypal preferred)?

All available donations are listed in the **Sponsor this project** section of the Github project's page:
![image](https://user-images.githubusercontent.com/12834464/103817324-89e8d580-5077-11eb-81db-f10dbca9dfd0.png)

You may use Liberapay or Bountysource. I believe I'll add Patreon ASAP, too.

Anyway, I think your suggestions should be moved to a dedicated issue since this issue is closed.
