### ISSUE TITLE
Please consider removing architecture from the name of the shared library

### ISSUE THREAD

**Issue by yurivict** [sadko4u/lsp-plugins#15]
On amd64 it installs ```lib/lsp-plugins-jack-core-1.1.4-x86_64.so```, and on i386 this name changes.
The name change only makes packaging more difficult because the file name needs to be adjusted for different architectures.
Please consider removing the architecture name from it.

**Comment by sadko4u** [comment]
The architecture was added in case that someone could install both x86_64 and i586 binaries on the same machine. But I think it's too uncommon mistake, so actually *.so file does not need to have architecture in it's name.

**Comment by sadko4u** [comment]
Created branch **github-issue-15**.
This commit should help: a90d634737d74646626a09a0cf77df9d452dfc45

**Comment by sadko4u** [comment]
Merged changes to **devel** branch: 383ac6784fd1793fe8095039a0047103dcf24971
Closing issue
