### ISSUE TITLE
LSP Limiter starts crunching on loud bass when enabling oversampling

### ISSUE THREAD

**Issue by unfa** [sadko4u/lsp-plugins#152]
Today I've discovered that LSP Limiter starts crunching on loud bass a lot when you turn on oversampling. It actually sounds way cleaner without it. I wonder if it's caused by oversampling inadvertently affecting the attack/release times...

To reproduce:

1. Make some very loud bass sounds.
2. Use LSP Limiter and hit it for about 3-6 dB of gain reduction on default settings.
3. Turn on oversampling (even the 2x does this)
3. Watch the graph become more jagged and listen to the limiter starting to produce distortion on the bass note peaks.

Can anyone confirm this?

**Comment by sadko4u** [comment]
@unfa 
Do you use ALR option?

**Comment by sadko4u** [comment]
Also please look at #122

**Comment by unfa** [comment]
I think I've learned how to set LSP Limier to avoid this problem.
Making the ALR release time longer seems to fix it.
I should read up on what that actually means :D

**Comment by sadko4u** [comment]
@unfa OK, thanks
