### ISSUE TITLE
LSP sampler mono: velocity knob reversed?

### ISSUE THREAD

**Issue by grammoboy2** [sadko4u/lsp-plugins#155]
The less % velocity, the louder the sound? Looks like that knob is working in reverse?

**Comment by sadko4u** [comment]
Thanks for the report, I'll check the behaviour in the nearest future.

**Comment by sadko4u** [comment]
The **velocity** knob defines the upper range of the MIDI velocity value for which the sample should trigger. The sample with highest (among other) velocity value also will trigger when the MIDI velocity is above the upper limit specified by the **velocity** knob. The loudness of the sample is computed by dividing the MIDI velocity value by the upper range of the velocity. So it's not surprise that your samples become highly amplified.
