### ISSUE TITLE
LSP Sampler: sfz support

### ISSUE THREAD

**Issue by grammoboy2** [sadko4u/lsp-plugins#156]
feature suggestion: given the fact how open and easy the sfz format is and that it's use is likely spreading on Linux with sfizz and liquidsfz, (simple) sfz support might be nice to have. Let's say you've a script which can turn a folder of samples into a sfz file suitable to use in LSP sampler. 

edit: Something like TAL sampler has also SFZ support for example https://tal-software.com/products/tal-sampler

**Comment by grammoboy2** [comment]
FYI: Example script to make a sfz file: https://github.com/rock-hopper/makesfz

**Comment by sadko4u** [comment]
I won't start so quick on SFZ support since it is a change that requires some huge refactoring of the device.
Probably after 1.2.0 release.

**Comment by porzione** [comment]
I can write simple script to convert SFZ to LSP cfg format. The problem is parameters mapping because full SFZ spec is too [complicated](https://sfzformat.com/opcodes/) and multisampler doesn't support most of sfz features. Beside samples we can import channel pan, fade in/out, midi notes, but I'm not sure what to do with the rest .

**Comment by sadko4u** [comment]
Hello. Is there any good full specification of SFZ format to write parser for it?
I found this but it seems that it is not up to date: https://sfzformat.com/legacy/

**Comment by Audiojunkie** [comment]
This is the ultimate resource on the internet:

https://sfzformat.com/

:)

**Comment by sadko4u** [comment]
Are there any good resources that provide different examples of SFZ files?

**Comment by grammoboy2** [comment]
https://sfzinstruments.github.io/ 
https://github.com/sfzinstruments/

**Comment by Audiojunkie** [comment]
> https://sfzinstruments.github.io/
> https://github.com/sfzinstruments/

Agreed. These are good sources. 🙂

**Comment by sadko4u** [comment]
Basic support of SFZ will be added in 1.2.6.
Not all SFZ files load well because we have the restricted of number of instruments (12, 24 and 48) but some of them are loading pretty good.

**Comment by grammoboy2** [comment]
Thx, maybe best to prioritize drum related sfz files? At least that why I added this feature request. Cymbal stuff etc. can be tricky though it seems. Here I found some docs:
https://sfzformat.com/tutorials/cymbal_muting
https://sfzformat.com/tutorials/brush_stirs

**Comment by sadko4u** [comment]
I think we can improve all this stuff further. At this moment the algorithm is simple: we're reading the whole SFZ file and sorting the regions by `group_label` and `key` or `pitch_keycenter` (depending on what is present). The samples with the same `group_label` and `key` are grouped together into a single instrument in the sampler.

**Comment by sadko4u** [comment]
Available in 1.2.6
