### ISSUE TITLE
LSP Sampler: add new sample on next midinote? 

### ISSUE THREAD

**Issue by grammoboy2** [sadko4u/lsp-plugins#157]
Tried to add a second sample, which seems to get the same midinote as my first sample. Might be more logical and userfriendly to put it on the next midinote.

edit: it seems you can only have one midinote per plugin?

**Comment by grammoboy2** [comment]
Bumping my head against this again. You can only assign one midi key per plugin? Not one midi key per sample?

**Comment by sadko4u** [comment]
Yes, in sampler you may use only one note for mapping samples.
For using set of notes, please consider using Multisampler plugin.

**Comment by grammoboy2** [comment]
This is the multisampler version.

Changing midi notenumber for sample 1, does change sample0 to the same midinumber.

**Comment by grammoboy2** [comment]
I need to change instrument I see.
