### ISSUE TITLE
LSP Sampler: manually edit midinote

### ISSUE THREAD

**Issue by grammoboy2** [sadko4u/lsp-plugins#158]
Might be handy to be able to edit/change the midinote number by hand/ keyboard.

**Comment by sadko4u** [comment]
Created **github-issue-158** branch for feature.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 8cac3d8cf3239575db95c1009b1b1728f528881f

**Comment by sadko4u** [comment]
Removed branch **github-issue-158**.

**Comment by sadko4u** [comment]
Available in 1.1.28 release!

**Comment by grammoboy2** [comment]
Merci!
