### ISSUE TITLE
Low & High Pass filters not working

### ISSUE THREAD

**Issue by Harishankar-G** [sadko4u/lsp-plugins#162]
Cannot enable low & high pass filter in equaliser of microphone section.

The slider gets greyed out and cannot be moved.

My System:
Ubuntu 20.04
GCC 10

Built from source.
![Before High Pass](https://user-images.githubusercontent.com/67601573/102134062-0d9a1280-3e7c-11eb-84b5-d0dbec1a82c2.png)
![High pass](https://user-images.githubusercontent.com/67601573/102134066-0f63d600-3e7c-11eb-97d9-37ffbe67dbc4.png)
![High pass 2](https://user-images.githubusercontent.com/67601573/102134067-0ffc6c80-3e7c-11eb-93b4-7f843db935a1.png)

**Comment by sadko4u** [comment]
Not clear your case.
Could you please send a screenshot which shows your problem?

**Comment by Harishankar-G** [comment]
@sadko4u I attached the files you asked for.

**Comment by sadko4u** [comment]
Sorry but I have nothing related to PulseEffects except that LSP plugins are used by the wrapper.
Consider better posting the issue here: https://github.com/wwmm/pulseeffects/issues

@wwmm @Digitalone1 Please take an attention.

**Comment by Digitalone1** [comment]
@Harishankar-G please open an issue on pulseeffects repository and copy the same post.

**Comment by Digitalone1** [comment]
I see from the code that this is an intended behaviour introduced by @wwmm

I don't use that filter and admit my ignorance, but @sadko4u does band gain have effect on hi/lo-pass?

**Comment by sadko4u** [comment]
@Digitalone1 
If it is a parametric equalizer, any filter can be used in any configuration. All filters have just serial connection one to another.
In the original UI there is no restriction from the plugin related to any special filter. You just can turn on all 16/32 filters, configure and use them according to your requirements.

**Comment by sadko4u** [comment]
The band gain does not have any effect on Hi-pass Low-pass since it is not reasonable. Hi-pass just cuts-off the frequency above some threshold. The same is for low-pass filter. Maybe @Harishankar-G mixed up them with low-shelving and high-shelving filters?

**Comment by wwmm** [comment]
>The band gain does not have any effect on Hi-pass Low-pass since it is not reasonable

That was the reason why I decided to disable the gain sliders when these filters are selected.

**Comment by Digitalone1** [comment]
> The band gain does not have any effect on Hi-pass Low-pass since it is not reasonable. Hi-pass just cuts-off the frequency below some threshold frequency, low-pass - above some threshold frequency. The same is for low-pass filter. 

Then that's because @wwmm disabled the band gain slider on hi/lo-pass. It's not a bug.

> Maybe @Harishankar-G mixed up them with low-shelving and high-shelving filters?
Maybe.

But anyway thanks to @Harishankar-G because I found out that `Allpass` filter is missing in Pulseeffects. I will add it.

**Comment by Harishankar-G** [comment]
@Digitalone1 The reason I wanted high pass and low pass filters in the equaliser is that, I have a pretty bad quality microphone. There's this static noise below 10Hz that triggers the compressor even when not needed. This makes everything I speak compressed.

I tried using just the filter plugin, the fourth one in the sidebar. But still the noise existed.

**Comment by sadko4u** [comment]
@Harishankar-G If you're using your mic only for voice, then just cut everything below 100 Hz. You also can change the hi-pass filter type to butterworth (BWC) filter type and increase the filter slope to 2x or more. Probably this will help much more than just cutting low frequencies below 10 Hz.

**Comment by Harishankar-G** [comment]
@sadko4u Thanks. Fixed my issue.
