### ISSUE TITLE
LSP Parametric Equalizers : 'soloing a band' behaviour

### ISSUE THREAD

**Issue by sub26nico** [sadko4u/lsp-plugins#163]
Hello,
I don't know if it's a bug or not, but i notice that soloing a band in LSP Parametric Equalizers only 'remove' other bands active processings but doesn't 'cut' the signal around the band. In Graphical Equalizer, if I set a band on solo, I can hear 'only' the band selected. 
Is the difference between the 2 plugins for soloing is wanted ? Or a bug in Parametric's versions ?

**Comment by sadko4u** [comment]
No, it's not the bug. It just enables the filter to work in solo mode. 'Solo' means that only this filter is active (and others selected for soloing). Moreover, how do you understand cutting the band around the low-pass or high-shelving filter?

**Comment by sub26nico** [comment]
Thanks for explanations. Not sure to understand correctly 'how do you understand cutting the band around the low-pass or high-shelving filter' (my english skills are not good) but, i was expecting to found the same behaviour in Parametric Eqs that I use in Graphical ones when i press on 's' button. I'd like to have this solo behaviour in Parametric Eqs, it is the main reason why i use Graphical Eqs. It's great to clean tracks or remove noise or bad frequencies. But the workflow of Parametric Eqs is nicer and more versatile. 

By the way, if it is not a bug, I can close here.
