### ISSUE TITLE
Surplus (?) direct outs in the Multi-Sampler x12

### ISSUE THREAD

**Issue by cooltehno** [sadko4u/lsp-plugins#169]
Hi, Sadko!
When I connect outs (in Ardour's matrix) to different audio tracks (12 stereo tracks) - I use 3/4 - 25/26 outs for L/R inputs. I usually disable "Insrument # Enabled" yellow knobs in the mixer of the sampler - which are connected to 1/2 out (as I understood). But in the Ardour's matrix I see also some 27-32 outs - when I connect them to any track - I can't hear anything. Are these outs used for something or they are just redundant?

LSP dayet kopati!!! Thanks!))
![ardour_s_matrix](https://user-images.githubusercontent.com/19673308/102878838-eafa9180-4459-11eb-99b4-4120dba1d2ae.png)

![ardour_s_editor_ _sampler_s_mixer](https://user-images.githubusercontent.com/19673308/102878227-fbf6d300-4458-11eb-9377-473524a4e607.png)

**Comment by sadko4u** [comment]
Direct otuputs are usable when you want to render each instrument into a separate track. Otherwise, just use non-direct output version. When you connect them to track, then you probably won't hear anything because Ardour doesn't bypass the sound of track in default configuration. If you connect the direct output to bus and route it to master, you'll hear the same you hear in first two stereo outputs but only for the specified instrument.

**Comment by cooltehno** [comment]
Yes, I use direct outputs for separate sound processing. 

> 27-32 outs - when I connect them to any track - I can't hear anything
- that's not. (Sorry! I've not figured it out right away). These outs give the sound of the last (№11) instrument. No problem, but in my opinion, this makes some jumble during the connection to the different tracks/buses.

**Comment by cooltehno** [comment]
I mean, when I open the matrix for the first time - it would be comfortable to have only 24 outs for direct connections (LSP Multy Sampler **_x12_**  - logically). But when I have 32 outs in the LSP Multy Sampler **_x12_** - I begin to search which out is for what..

**Comment by sadko4u** [comment]
That's strange how did you get 32 outputs. For me, if I add Multisampler to the bus, I get exact 26 outputs: 2 for stereo mix and 24 for 12 stereo outputs.

Probably you're using **strict** routing instead of **flexible** for your bus?

**Comment by cooltehno** [comment]
I've got the ground. )) Big Sorry!! It's not related to LSP! I used the midi track, which had a 32outs plugin before. I've deleted that plugin and inserted the LSP Sampler x12 - but Ardour didn't delete outs of the previous plugin from the track. When I've added a brand new midi track and insert LSP Sampler x12 - it has 26 (2+24) outs - as must be! Sorry again and thanks!
