### ISSUE TITLE
About multisampler reverse option

### ISSUE THREAD

**Issue by ChekPuk** [sadko4u/lsp-plugins#172]
Hello. It's nice to see reverse play option appeared, but it's not perfect yet. 
Now if I set range in a sample and then press "reverse" - selected area goes wrong. You should apply reverse to set range with right attacks and decays, not reverse sample and then apply range and attacks/decays.

And more to that - It would be perfect if reverse function was per instrument, not just per sample. And then it should be accessible for direct control on MIDI, so I could map it for every instrument on my controller and reverse on the fly.

And thank you for your patience and hard work.

**Comment by sadko4u** [comment]
The sample reversal behaviour is completely copied from the Impulse Responses/Impulse Reverb plugin.
The overall use case was expected to be:
- Select the sample being normal or reversed.
- Cut head and tail of the reversed sample.
For this case, the head is always at the left and the tail is always at the right.

The instrument reversal requires the sampler core to implement reverse playback. This is currently not supported but I believe is possible to implement quickly.

Reversing instrument by some MIDI event - that requires some additional design I believe. Which event would you like to use for sample reversal?

**Comment by ChekPuk** [comment]
More I use this plugin - more I realize that I am using it wrong. First I wanted reverse, then looping (with midi tempo), then a pitch shifter (two kinds, with and without stretching, yeah) and so on and so on. But this multisampler is pretty consistent as is and more oriented on multilayered drums, and really, reverse playing and other looper features are out of his scope. Implementing all the bells and whistles will make it a monstrous сhymera. So... I withdraw my request. Sorry for bothering.

**Comment by sadko4u** [comment]
Finally, in 1.2.4 we got the `reverse` option as you described. And added many features from your request (but not all). I think it can be closed now.
