### ISSUE TITLE
Wrong VST plugin return values for effGetInput/OutputProperties (and other) properties

### ISSUE THREAD

**Issue by emuell** [sadko4u/lsp-plugins#174]
The switch case for the VST property `effGetVendorVersion` at https://github.com/sadko4u/lsp-plugins/blob/63c93b0318b4200ae9fa572610bedb889f69a939/src/container/vst.cpp#L564 also handles 
`effString2Parameter, effGetProgramNameIndexed, effGetInputProperties, effGetOutputProperties, effOfflineNotify, effOfflinePrepare, effOfflineRun` and thus returns a non zero value (the VST version), claiming that it supports those properties. It should return 0 for them instead. 

This is causing troubles in [Renoise](https://www.renoise.com/), but we've already added a workaround for this by testing for a return value of zero for effGetInput/OutputProperties. You may still want to fix this for other hosts.

Let me know if you need more info please.

**Comment by sadko4u** [comment]
Ow, wow. Silly mistake. Thanks for the report.

**Comment by sadko4u** [comment]
Submitted patch to **github-issue-174** branch: ca973fac462953acee11d6e25aa9c2ac99ef9e69

@emuell Are you available to test?

**Comment by emuell** [comment]
This looks good to me. I can't build from source right now, but could test binaries if there are nightly builds or pre-releases somewhere which include this fix.

**Comment by sadko4u** [comment]
No, there are no nightly builds currently.

**Comment by sadko4u** [comment]
Added changes to the **hotfix** branch: f5ae41cd9b4dc25e0eb2f1ccfb9772d09ce2768c

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 03187de44e8e5476dbe3bc6cfc32120fb05e3091

**Comment by sadko4u** [comment]
Removed **github-issue-174** branch.

**Comment by sadko4u** [comment]
Available in 1.1.29!
