### ISSUE TITLE
Multi-Sampler: Cannot play simultaneously two samples.

### ISSUE THREAD

**Issue by wujekbrezniew** [sadko4u/lsp-plugins#176]
I've discovered with my Arturia Minilab that if i play two midi notes simultaneously sampler does not play two sounds as i expected but plays nothing. Is this a normal behaviour for this plugin?

**Comment by sadko4u** [comment]
No, that's not normal. Each instrument should play when the **Note On** MIDI event is received.
Which version and format of plugins do you use?

**Comment by wujekbrezniew** [comment]
At the beginning i thought that this is LMMS related as i was using beta version of it but as turned out it is not and the same problem exists in standalone Carla host.
When im using other plugin f.e. ZynAddSubFx i can play two notes simultaneously without problems using both controller pads or keys.

My whole setup:
Jack 1.9.16
Carla 2.2.0
Newest LSP (1.1.28)
KDE Neon (Ubuntu 20.04 with Plasma)
Arturia Minilab MK2.

**Comment by sadko4u** [comment]
Reproduced the behaviour for standalone version of plugins. LV2 works just fine.

**Comment by sadko4u** [comment]
Not reproducible for Ardour 6.2.245 with JACK version of plugins.
From Ardour 5.12 I got invalid MIDI signals at the input of JACK MIDI buffer.

Are you available to build plugins from source and perform the test?

**Comment by sadko4u** [comment]
Ah... It seems that Mutisampler is improperly bypassing notes... That's the case...

**Comment by sadko4u** [comment]
Found the case of the problem.

**Comment by sadko4u** [comment]
Dumb error (but very destructive), committed related fix: a86f5be51c578fbc5bb0805697ed6e133aa74f52

@wujekbrezniew are you available to build plugins and perform check?

**Comment by sadko4u** [comment]
Changes are available in **github-issue-176** branch.

**Comment by wujekbrezniew** [comment]
Builded and tested mentioned branch. Problem gone.

**Comment by sadko4u** [comment]
Nice.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: f297526291a8958b20e6609479b08376248e57ee

**Comment by sadko4u** [comment]
Removed **github-issue-176** branch.

**Comment by sadko4u** [comment]
Available in 1.1.29!
