### ISSUE TITLE
Filename field not filled when selecting saved settings for Import on 1.1.28

### ISSUE THREAD

**Issue by neildarlow** [sadko4u/lsp-plugins#178]
Hi,

When exporting plugin settings to a file, you can select an existing settings filename and it is transferred to the filename entry field after which you can click the Save button to overwrite the settings file.

Since version 1.1.28 the same is not true for a settings import operation. Clicking an existing settings file does not transfer the filename to the entry field. You either have to type the settings filename or double-click the existing settings file which loads the settings and closes the Import dialog immediately.

**Comment by sadko4u** [comment]
The file name field in open dialog acts as a filter. You don't need to type-in the full file name there.
You're only required to select file in the list box and press 'Open' to get things done.
This behaviour didn't change for a long time. So you're probably confused by the behaviour of the save dialog.

**Comment by sadko4u** [comment]
Anyway, I've found that dialog is not working properly when applying filters. This should be fixed.

**Comment by neildarlow** [comment]
Hi,

Thank you. I must have been expecting non-existent behaviour.

Yes, a filtered file e.g. "eq" for "equaliser" followed by Open results in a non-existent file message.

At least this issue wasn't totally wasted. Thank you.

Regards,
Neil

**Comment by sadko4u** [comment]
Created **github-issue-178** branch and pushed related changes: 7320ba322bf972f61cc87d322e51fe3f33bec6a6

**Comment by sadko4u** [comment]
@neildarlow Are you available to build and validate that problem has gone?

**Comment by neildarlow** [comment]
I can certainly try. I'd need to spin-up a build environment, either chroot or under VirtualBox, do you have any suggestions for a quick setup? I'm using Linux Mint 20.1 (Ubuntu 20.04 based).

Regards,
Neil

**Comment by sadko4u** [comment]
You don't need special environment. Please consider reading README.txt file for package requirements and the build process.

**Comment by neildarlow** [comment]
OK, cloned, checked-out, built and installed. :-)

Previous version:
1) Select Import settings dialog.
2) Type characters to filter settings.
3) Click resulting single filename and click Open button.
4) A "Selected file does not exist" error is shown.

This version:
1) Select Import settings dialog.
2) Type characters to filter settings.
3) Click resulting single filename and click Open button.
4) The settings file is successfully opened and applied.

I changed a few plugin settings before importing to be sure that the opened file restored them.

Looks good to me Vladimir. Thanks for the quick turnaround on this.

Regards,
Neil

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 38722323a6d477b99716ce54cc7a573fdaabc630
Will close issue after release

**Comment by sadko4u** [comment]
Available in 1.1.29!
