### ISSUE TITLE
Invalid TLS certificate on lsp-plugin.in

### ISSUE THREAD

**Issue by dvzrv** [sadko4u/lsp-plugins#18]
The current TLS certificat used on https://lsp-plug.in is not valid (but it used to be!):

```
lsp-plug.in uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. The certificate is only valid for . The certificate expired on 5 April 2011, 01.15.59 GMT+2. The current time is 30 December 2018, 17.13. Error code: SEC_ERROR_UNKNOWN_ISSUER
```

**Comment by sadko4u** [comment]
The domain lsp-plug.in currently does not use SSL. How you became redirected to the HTTPS link?

**Comment by dvzrv** [comment]
I used it, when I introduced the package, and it was valid back then (IIRC).
Are you up for creating a valid https setup for it (e.g. using letsencrpyt)? Otherwise it might be good to do a permanent redirect to port 80 or not making port 443 available at all.

**Comment by sadko4u** [comment]
I think I'll get valid signed certificate after upcoming new year and upload it to the server. Then we'll test the result.

**Comment by sadko4u** [comment]
Fixed the problem, got new free SSL certificate using Let's Encrypt service.
https://letsencrypt.org/
