### ISSUE TITLE
Noise Generator

### ISSUE THREAD

**Issue by v-fox** [sadko4u/lsp-plugins#183]
[Discussion of a potential problem of digital "receivers"](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/705) forcibly shutting themselves off not just on lack of signal but also simple silence in regards to PipeWire have made me think about pushing inaudible noise in such case. Using LV2 host with an appropriate plugin would be a quick workaround but having ability to generate different types of noise at particular amplitude could be useful in other ways.

But I did not find such a tool in LSP. It seems that adding such modes of noise of different types in lsp-plugins-oscillator-mono might do the job. Similarly to https://github.com/x42/testsignal.lv2 / https://x42-plugins.com/x42/x42-testsignal but with all of LSP's glory. It would also need explicit "volume" knob though, likely at safe default volume such as something in -36 to -24 dB range and going down to -144 dB for ability to be inaudible at max hardware volume.

**Comment by sadko4u** [comment]
This should be not an oscillator feature.
It should be a dedicated plugin.

**Comment by sadko4u** [comment]
I think this will be interesting for @CrocoDuckoDucks after he completes #70.

**Comment by sadko4u** [comment]
Available in 1.2.4!
