### ISSUE TITLE
FIR and FFT EQs make phase crazy

### ISSUE THREAD

**Issue by wargreen** [sadko4u/lsp-plugins#184]
Hi and thanks for your work.
When graphic and parametric EQ are put in FFT or FIR mode, the phase of the out signal is weird, even with all band disabled.
![Screenshot in ardour](https://user-images.githubusercontent.com/5098493/110560128-b9828f80-8145-11eb-9c4d-06182f45d8b7.png)

**Comment by sadko4u** [comment]
According to the design, FIR and FFT equalizers have linear phase response
https://www.dspguide.com/ch19/4.htm
This is not a problem, this is just a constant delay added to the signal since equalizer introduces finite impulse response.

**Comment by sadko4u** [comment]
The problem was the invalid latency report by the plugin which was fixed in 1.1.29 release.
