### ISSUE TITLE
Plugin bypass does not apply latency

### ISSUE THREAD

**Issue by marcan** [sadko4u/lsp-plugins#187]
When using a plug-in with latency (e.g. compressor with lookahead), the Bypass toggle causes it to cease having latency, but the latency is still reported to the host. This causes latency over-compensation, as well as an audible glitch when the Bypass code fades between two out-of-phase signals.

Since Bypass is automatable (and faded so it works cleanly), while trying to change the latency reported to the host would be unlikely to end up glitch-free and cannot be faded, I would suggest adding a latency buffer to Bypass.cpp, so the plug-in retains its latency in Bypass mode. This will allow Bypass to be automated cleanly. The downside is that a bypassed plug-in still introduces (useless) latency, so users cannot reduce their overall latency by temporarily bypassing plug-ins.

**Comment by sadko4u** [comment]
@marcan 

Committed all related changes to github-issue-187 branch.
Please verify.

**Comment by marcan** [comment]
Verified, seems to be fixed. Thanks!

**Comment by sadko4u** [comment]
Please don't close issues until they get released.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch.

**Comment by sadko4u** [comment]
Available in 1.1.30
