### ISSUE TITLE
UI suggestions: linear knob dragging, scrolling on knobs, color for active items

### ISSUE THREAD

**Issue by wolftune** [sadko4u/lsp-plugins#190]
Hi, finally getting to use LSP plugins more, sent a donation, thanks for your huge contribution to free software audio!

I have a few simple UI suggestions:

- The knobs should work with a linear up/down style dragging. So, clicking on the knobs and dragging up should turn them clockwise, and dragging down should turn them counterclockwise
- The knobs should also respond to scroll-wheel actions as well as dragging
- The colors for "active" such as in Delay Compensator need to be fixed. They currently are all green no matter what is active, just a bolder green for the active one. That means a glance at anything looks like it is active. Please make the inactive items red instead of green.

Cheers

**Comment by sadko4u** [comment]
Hello!

> The knobs should work with a linear up/down style dragging.

That's surprising for me but this should work out of the box. Just click on the knob's cap and drag up/down to adjust the value. Also you may use right mouse button for more precise adjustments.

> The knobs should also respond to scroll-wheel actions as well as dragging

That's surprising too but knobs also should properly act with scroll actions. Scrolling up/down should work. Additionally, you can press Shift Key to make more precise adjustment.

> The colors for "active" such as in Delay Compensator need to be fixed. They currently are all green no matter what is active, just a bolder green for the active one.

That's also surprising. Could you please make a screenshot?

**Comment by wolftune** [comment]
Well, the knobs all are working correctly now. Weird, I don't know what was going on when I was using them yesterday, how strange.

But the green color is still a problem, tested in both Carla and Ardour:

![all-green-active-lights-fs8](https://user-images.githubusercontent.com/2801853/113428555-da788200-938b-11eb-8fa1-3307e08fb348.png)

**Comment by sadko4u** [comment]
@wolftune sorry but I don't see any green color problem. The UI looks like it should look:
![image](https://user-images.githubusercontent.com/12834464/113458216-53beb600-941a-11eb-9992-b8101a39368e.png)

Ah, I just found the point you're talking about. The green controls are designed as LEDs work: when it is off, it's dark-green. When it is on, it is lighting with bright green. I think the UI for this plugin will be changed and completely reworked in 1.2.0.

**Comment by wolftune** [comment]
Yeah, for reasons I don't understand, your screen-shot has much clearer *off* sense. I wouldn't have minded if it was like that. Compare the two screen shots. Yours is bright green vs very dark green. But in mine, they are all bright green, just larger and smaller. I don't see any other difference, no idea why the rendering is different.

**Comment by sadko4u** [comment]
Aaah, I got it. In new version LEDs look almost same to yours. The screenshot I've attached is from official documentation.
It seems that rendering of  LEDs has changed once and now they are more birght-looking.

**Comment by sadko4u** [comment]
It seems that after releasing 1.2.0 and changing the look of the UI, this problem is not actual anymore, right?

**Comment by wolftune** [comment]
probably, but I haven't tested it yet, I'm still on older version via KXStudio. I opened https://github.com/KXStudio/Repository/issues/285

**Comment by sadko4u** [comment]
Is the problem still actual?

**Comment by wolftune** [comment]
It's fixed. Even with the legacy UI, the issue seems resolved, and it's also clear what's happening with the newer UI options. Cheer!
