### ISSUE TITLE
Feature Request: summing amplifier

### ISSUE THREAD

**Issue by eufex** [sadko4u/lsp-plugins#194]
Now that the input and crossover stage of the Multiband processors has been pulled out into the superb Crossover plugins it would sense to also split out the summing amplifier stage of the Multiband processors into a separate plugin. That way, rather than having to route all the Crossover outputs to busses, everything could (if required) stay in the same mixer channel. For example if I want to frequency split a kick Into, say three bands, phase rotate the lower band, saturate the miss and compress the highs it’s quicker, more convenient, and uses far less screen real-estate, to route that within the single channel in (for example) Ardour then resum and go out through the single mixer channel. It can be done currently but the only summing amp I’ve found is within the ALSA modular synth plugins (and it took some finding). The summing amp should be available in the same plugin suite as the crossover, otherwise it’s an ‘incomplete’ process.

Thanks :)

**Comment by sadko4u** [comment]
Available in 1.2.6 as a Mixer plugin

**Comment by eufex** [comment]
Just saw notification of this. Fantastic :) This is such a powerful tool for Linux users.
