### ISSUE TITLE
Multisampler Export

### ISSUE THREAD

**Issue by jeffbeale** [sadko4u/lsp-plugins#197]
Rather than export a configuration file, would it be possible to add an entire kit export where Multisampler packages all the samples used, and creates a .cfg file that points at those samples in relation to the newly created .cfg file? This feature would make it much easier to share kits made with LSP Multisampler.

**Comment by sadko4u** [comment]
Hello!
It is a good feature but I think it will be implemented not earlier than after 1.2.0 release.
Sorry but the work on the 1.2.0 release is lasting more than one year and we want to end this long refactoring.

**Comment by unsaph3** [comment]
Totally understandeable - this wasn't a time sensitive thing, just a general idea. I'm excited for the 1.2 release!

**Comment by sadko4u** [comment]
Added possibility to export drumkit ('Sampler bundle') as a single binary file. Also added support of import this file in the UI. 
Change set: cd19dd5a5df8be31532fbfff09c88377007aa8e8

WIll be available in 1.2.4.

**Comment by sadko4u** [comment]
@chrisanthropic FYI

**Comment by sadko4u** [comment]
Available in 1.2.4!
