### ISSUE TITLE
Why `make VERBOSE=1` doesn't work?

### ISSUE THREAD

**Issue by Logarithmus** [sadko4u/lsp-plugins#199]
Usually it's used to see compiler invocations and is very useful for debugging Makefiles in general. But for unknown reason your project just ignores it. The only way to see compiler invocations I found is `make SHELL="sh -x"`.
@sadko4u

**Comment by Logarithmus** [comment]
I've founded out that `VERBOSE=1` isn't implemented in `make` itself, instead every `Makefile` should handle it manually: https://stackoverflow.com/a/11015111. So I'll make a pull request to add `VERBOSE` support.

**Comment by sadko4u** [comment]
Thanks, I'll work on your PR this evening.

**Comment by sadko4u** [comment]
Added the feature without introducing extra variables.
The changes are available in the **devel** branch: ef111ef79cc106f1f911f6b95111504d6f9fb9b2

**Comment by sadko4u** [comment]
Available in 1.1.31 release!
