### ISSUE TITLE
malloc.h file not found

### ISSUE THREAD

**Issue by ish3lan** [sadko4u/lsp-plugins#2]
After downloading the repo and navigating to the folder, I ran `make` and got this error:
`/lsp-plugins-master/include/core/sugar.h:11:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~`
maybe this is related? https://github.com/RIOT-OS/RIOT/issues/2361

**Comment by sadko4u** [comment]
Hello!
Seems to be right relation. I've looked at the 'man malloc' and it says that I should use <stdlib.h> library instead of <malloc> one. Thank you for a report, it will be fixed in development branch.
What target operating system are you using to build sources?

**Comment by ish3lan** [comment]
Thank you for the fast response, I was trying it on MacOS High Sierra 10.13.4
Nevertheless, I was not able run it in Ubuntu. I face a problems:

fatal error: lv2.h: No such file or directory
fatal error: cairo.h: No such file or directory
fatal error: sndfile.h: No such file or directory

I faced more errors but these are the one that I gave up on them.

**Comment by sadko4u** [comment]
MacOS is currently not supported and I don't know when it will be supported, currently MacOS support is not in the nearest plans.

The errors you get is the result of lack of  '-devel' packages on your system. Please read secion 'BUILDING' in the  README.txt file for packages that you need to have to to successfully build plugins:
https://github.com/sadko4u/lsp-plugins/blob/c7b4d92bdb8c89f8f122fe6e94e450e57e0011a7/README.txt#L170

Please notify me if you have any problems while building, that will help to update development documentation.

**Comment by sadko4u** [comment]
I've updated the current set of requirements, here's the most actual one:
https://github.com/sadko4u/lsp-plugins/blob/724b8a5523ba48f7f5e71056d2455ab5ef373874/README.txt#L152

**Comment by sadko4u** [comment]
The release 1.1.4 has been published with this change. Closing topic.
