### ISSUE TITLE
[suggestion] plugin to abx two plugins

### ISSUE THREAD

**Issue by capoei** [sadko4u/lsp-plugins#201]
I wouldn't call it a [request], but rather a sugestion for a new plugin. if there is any intrest from others it might be an intresting idea.
what would this plugin do? it would basicly enable you to abx two (or more) plugins you have in the same plugin chain by soloing one of them blindly and ask you which sounds better

**Comment by sadko4u** [comment]
Hello. You mean, implement a circuit switcher which will switch between different inputs?

**Comment by capoei** [comment]
yes, and do so blindly. and then you rate the better input, and than you can reveal which it was

**Comment by sadko4u** [comment]
It will be a useful plugin, not only for A/B testing but also for different switching solutions.

**Comment by sadko4u** [comment]
Another one question: how do you imagine the rating mechanism for the plugin UI?

**Comment by capoei** [comment]
not sure. when comparing two plugins a simple "which sounds better: A or B?" button would do it. but I can imagine that a rating could be usefull, too. you could have 5 stars for every plugin which you could check (1-5). than with another button you could reveal which was which

**Comment by sadko4u** [comment]
> yes, and do so blindly

If we have a rating option, then we can randomize the input channels when pressing the 'Blind' button and after unpressing the `Blind option`, your rating and remarks will be set to the right place so you could get familiar with your choice.

**Comment by capoei** [comment]
I betrayed the comunity lol
I am back to Windows after all these years.
hoped to be able to use LSP via WSL, but this is still impossible.

LSP sure is one of the few things I miss.

**Comment by sadko4u** [comment]
Available in 1.2.6
