### ISSUE TITLE
Basic Windows support

### ISSUE THREAD

**Issue by ktheticdev** [sadko4u/lsp-plugins#203]
Currently there are no parametric EQs that work in DAW, repeat the APO filters and are 16-band. Would be really nice if at least LADSPA plugin could be built for Windows so that it could be loaded through ladspashell into DAWs.

**Comment by capoei** [comment]
shouldn't it be possible to use LV2 in Windows?

also is there a way to conect jack in WSL2 to jack for windows?

**Comment by ktheticdev** [comment]
> shouldn't it be possible to use LV2 in Windows?
> 
> also is there a way to conect jack in WSL2 to jack for windows?

It just won't build on Windows because of using some Linux-specific stuff, I believe.

**Comment by capoei** [comment]
> > shouldn't it be possible to use LV2 in Windows?
> > also is there a way to conect jack in WSL2 to jack for windows?
> 
> It just won't build on Windows because of using some Linux-specific stuff, I believe.

yea, you are right. possibility to make it work via WSL2 would be perfect

**Comment by sadko4u** [comment]
To make plugins work natively under Windows, some stuff (especially graphical) should be ported to the Windows platform.
Partially 1.2.0 repositories already support building for Windows but not all.

**Comment by oiwn** [comment]
would be cool to have osx support as well.

**Comment by sadko4u** [comment]
The plugins now are possible to build and run on Windows. Available formats are:
- LADSPA;
- LV2;
- VST2;
- CLAP.
