### ISSUE TITLE
Feature request: named instruments in sampler

### ISSUE THREAD

**Issue by porzione** [sadko4u/lsp-plugins#204]
It would be nice to name the instruments because it is not easy to remember everything by numbers. Or at least show first sample file name in instrument selector.

**Comment by sadko4u** [comment]
Hello!
Good feature. Will be introduced after 1.2.0.

**Comment by sadko4u** [comment]
Will be available in 1.2.1 for Multisampler:
![изображение](https://user-images.githubusercontent.com/12834464/164089609-b1a05750-d663-45b9-9356-b3821ac9e3e9.png)
![изображение](https://user-images.githubusercontent.com/12834464/164089652-d283883b-5e84-4381-af50-e7f4592c1c31.png)

**Comment by porzione** [comment]
nice, really long awaited feature!

**Comment by sadko4u** [comment]
Available in 1.2.1.
