### ISSUE TITLE
Buggy window decorations in fluxbox

### ISSUE THREAD

**Issue by thulle** [sadko4u/lsp-plugins#207]
When using fluxbox as window manager I get window-decorations on the popup-menu in lsp-plugins-para-equalizer-x16-stereo. Since the popup disappears as soon as I hover the "window title" of the menu, or anything else, I can't move the cursor to "Export settings to file...", making it impossible to save the configuration file. 

![2021-11-06-220040_7680x1440_scrot](https://user-images.githubusercontent.com/1105866/140623798-0ac0c277-3782-4cf9-bc78-58877627ff62.png)

I can toggle window decorations for the whole window, but that doesn't seem to apply to the popup-windows, assumingly because they're named "Unnamed" instead of anything related to the plugin.

I think this can be worked around by popping up the menu, listing all X11-windows and using the info about the window to write a decorations-exclusion for fluxbox apps-file, but it's been so long since I happened upon an app where this doesn't work out of the box so I thought it might be worth filing an issue.

Running lsp-plugins-1.1.29

**Comment by sadko4u** [comment]
Hmm, interesting.
I need some time to try to reproduce it with fluxbox.

**Comment by sadko4u** [comment]
Committed changes that fix the problem: 7e373361a2ea4e94abad156e1ce25f8e5e2b378b

**Comment by thulle** [comment]
I applied the commit on top of lsp-plugins-1.1.29 and it works great:

![PEQ-fluxbox](https://user-images.githubusercontent.com/1105866/145290480-a90c98f1-e72e-4c60-aa43-7a52b9aeeefc.png)

Thank you very much!

**Comment by sadko4u** [comment]
Available in 1.1.31 release!
