### ISSUE TITLE
GUI pauses/hangs intermittently - 1.1.30

### ISSUE THREAD

**Issue by windowsrefund** [sadko4u/lsp-plugins#217]
Hello,

I'm very new to lsp-plugins. Thank you very much for what appears to be an incredible collection of Free Software plugins. Some details about my system:

OS: Ubuntu Studio 20.04
Kernel: 5.15.0-6.2-liquorix
DAW: Qtractor 0.9.24
LSP-Plugins: lsp-plugins-lv2 1.1.30-kxstudio1

I've added LSP Limiter Stereo to Qtractor's Master Output. While playing my track and monitoring the GUI, I see that it will "pause" intermittently. I can always get it back by reopening the plugin. However, there's clearly something going on which I'd like to figure out. I've tried disabling all Calf plugins (operating on other tracks/busses) in an attempt to validate something I remember reading on the sourceforge threads... something about Calf not playing nicely. That didn't get me past the problem as I can still reproduce this intermittent GUI freeze.

Happy to provide any additional information or conduct further testing. Please keep in mind though that I'm really somewhat of a newb with these plugins (and audio Jedi trickery in general) so my limited insights may get in the way of any exotic testing proposals.

Thanks in advance.

**Comment by sadko4u** [comment]
Also, have you tried the official builds instead of provided by kxstudio?

**Comment by windowsrefund** [comment]
Thank you for the responses. I use lv2 and the GUI does freeze indefinitely. As for the official vs. kxstudio builds, I didn't think of that but will try the swap tonight and report back.

**Comment by windowsrefund** [comment]
Greetings
So I uninstalled the lsp-plugins, lsp-plugins-data, and lsp-plugins-lv2 packages from my system. Next, I downloaded lsp-plugins-lv2-1.1.30-Linux-x86_64.tar.gz and copied the included usr/local/lib/lv2/lsp-plugins.lv2 directory to ~/.lv2.

Running the same test as I previously reported, the GUI still freezes intermittently as I play the track with the stereo limiter assigned to my master output. Qtractor's log doesn't capture or report anything when this happens. As mentioned previously, I can always get the GUI back by reopening the window.

**Comment by sadko4u** [comment]
Thank you for information, I will try to reproduce the case on my system. Just have already bulit the specified version of Qtractor from source yesterday.

**Comment by windowsrefund** [comment]
Thank you

**Comment by sadko4u** [comment]
For me it was impossible to reproduce the case.
How long should I wait until the UI of plugin freezes?
In my case all is as expected:
![image](https://user-images.githubusercontent.com/12834464/146455201-4ad49dd5-ab7f-4d56-aa66-3cb1de1d6b16.png)

**Comment by windowsrefund** [comment]
Interesting. It happened rather quickly over here, although intermittent. I'll attempt to reproduce again tonight.

**Comment by windowsrefund** [comment]
Happy to report I can not reproduce this situation now that I've moved to 1.1.31. Looks great! Thank you for the try on your end and for your continued enthusiasm behind this incredible free software.

**Comment by mahlonsmith** [comment]
Chiming in on an old ticket rather than opening a new to carry discussion forward.

I recently discovered LSP and am seeing similar behavior.   The UI freezes during usage.  Well, not freezes, exactly.  It is still responsive to interaction, but it no longer updates/draws to screen.   This is a seemingly arbitrary timeframe -- it can happen within 10 seconds, or a few minutes.   Closing the window and reopening it 'resets the timer'.

OS: Ubuntu 22.04
Kernel: 5.15.0-43-generic
DAW: Ardour 6.9, Carla
LSP-Plugins: lsp-plugins-lv2 1.2.2

This doesn't seem DAW related, it happens in both Ardour, Carla, and loading a plugin "standalone" via jalv.  I've tried using the kxstudio 1.2.2 build, the official download, and building from source.

Interestingly, I also use the i3 window manager, so I'm curious if there is a connection there.  Another bit of data:  this happens with the VST2 variants as well.

I'm happy to help attempt to debug this (have a build with DEBUG=1 ready to go), but not sure how/what to capture for ya, as there's no crash/core to backtrace.

**Comment by sadko4u** [comment]
Hmm. That's weird. Never could met such behaviour.
I think we can add the message to the log that will indicate that the plugin's window gets redrawn and watch if there messages disappear from log when the `freeze` happens.

**Comment by sadko4u** [comment]
@mahlonsmith I also would like to ask you to build from the `devel` branch. There are tons of changes related to the UI introduced in the `devel` branch. Is the problem still reproducible for you?

**Comment by mahlonsmith** [comment]
> @mahlonsmith I also would like to ask you to build from the `devel` branch. There are tons of changes related to the UI introduced in the `devel` branch. Is the problem still reproducible for you?

Ok, done!  It is indeed reproducible.  Additionally on the devel branch, the 'menu' button doesn't function - the screen just flickers.  (That wasn't the case with -master.)

**Comment by sadko4u** [comment]
@mahlonsmith  Could you please do some screen recordings?

**Comment by mahlonsmith** [comment]
> @mahlonsmith Could you please do some screen recordings?

You bet.  (Zipped it as github didn't support `.mkv`).

[capture.zip](https://github.com/sadko4u/lsp-plugins/files/9419920/capture.zip)

Captured the 'menu' menu item being weird, and the initial described behavior.  This is with the `-devel` branch.  It stops being responsive about 45 secs in, I show how clicks are still affecting change by closing and reopening the window.

Thanks for your responsiveness, sadko4u!  Please don't hesitate if I can provide any additional info.

**Comment by sadko4u** [comment]
Thanks. I've installed Ubuntu 22.4.1 in virtual environment and will try to reproduce the problem.

**Comment by mahlonsmith** [comment]
Nice!  I suspect it's likely something with i3 rather than ubuntu, but I haven't seen any similar behavior with anything elsewhere, and I'm probably tainted with the knowledge that the prior issue reporter was also running i3.

Another piece of information I hadn't considered before:  I'm running the nvidia binary drivers.  I'd be surprised if that's the culprit considering their popularity, but worth mentioning.   (Version 510.73.05).

**Comment by mahlonsmith** [comment]
Actually, when I'm back at home I'll just try it again in Gnome to verify/eliminate i3.

**Comment by sadko4u** [comment]
Ubuntu 22.04.1:
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Using Gnome over X11. Can not reproduce.
Maybe need to discard X11 to verify, too.

**Comment by mahlonsmith** [comment]
I just installed default lsp-plugins (no kxstudio) on my laptop here -- no nvidia drivers, al intel graphics, but I **am** running i3 here as well.   Apt installed an older version of LSP (1.1.3), and I see the problem there too!   Hilariously, I can see the knobs moving in Carla but not in LSP.

I'll still try at home later today under Gnome to confirm, but outside of Ubuntu, I think we can eliminate nvidia at least.

[another.zip](https://github.com/sadko4u/lsp-plugins/files/9428212/another.zip)!

**Comment by sadko4u** [comment]
i3 also works pretty well for me. No hangs/freezes.
https://youtu.be/SRZMQ8duDuk

Have you tried to completely rebuild the plugins? I mean, issuing the following commands:
```
git pull
make prune
make config
make fetch
make
make install
```

**Comment by sadko4u** [comment]
Also it would be nice if you could reproduce the case with standalone JACK plugin. Because it is much easier to debug it then.

**Comment by sadko4u** [comment]
> I think we can eliminate nvidia at least.

According to what I saw in your first video, it just looks like the window is suddenly losing mouse movement events.
Or, the second reason can be that the window stops redrawing at all.

**Comment by mahlonsmith** [comment]
I had completely rebuilt everything on my other machine, and JACK -- gotcha, will do.


.... I just noticed something on the last attached screenshare.   My cursor disappears momentarily, right before things go wonky.

I am running a cursor hiding app called "unclutter", and I now see there is a fork that fixes miscellaneous issues.   Just replaced things with that, and everything seems good so far.

I want to verify this on my workstation later, but at first blush this seems to be the culprit.  I'll reply here with confirmation (or otherwise).


As before, thanks so much for your attention (and your work on these!)

**Comment by sadko4u** [comment]
Just read about `unclutter`. OMG:

> Unclutter is a tool from the early 90s and has not been updated since. It works by creating fake windows or active pointer grabs, both of which often cause problems. By now, the X11 extensions Xinput2 and Xfixes have been released and are commonly found on most user systems. Using those, [unclutter-xfixes-git](https://aur.archlinux.org/packages/unclutter-xfixes-git/)AUR can provide the cursor hiding functionality without interfering with any application.
> As of December 2018, community/unclutter will actually ship this rewrite instead of the original[[2]](https://github.com/Airblader/unclutter-xfixes/issues/33#issuecomment-446209712)[[3]](https://github.com/archlinux/svntogit-community/commit/e652764bc5e55caefd3cd0df886554d3c76253ee).

Taken from [Arch Linux Wiki](https://wiki.archlinux.org/title/unclutter).

**Comment by mahlonsmith** [comment]
Ironically (perhaps), I've been running it for probably that long.  :\   Didn't even realize that was how it works.  OMG indeed.

**Comment by mahlonsmith** [comment]
Back home.  Confirmed (with forked unclutter, even) -- that was the problem.   Running any LSP plugin in any of the previously mentioned environments seems to be fine in perpetuity.

@sadko4u -- I really appreciate your attention to the problem, but this was 100% my environment.   Let this ticket serve as a Google landing space for future generations.  ;)   Sorry to temporarily divert your attention, but thanks for reasoning through this with me.  Satisfaction++.

**Comment by mahlonsmith** [comment]
.... oh.  with the exception of the "menu" item issue under -devel (I know, this conversation diverged) -- I can open another ticket for that if you prefer, or just standby for next release.

**Comment by sadko4u** [comment]
> oh. with the exception of the "menu" item issue under -devel (I know, this conversation diverged) -- I can open another ticket for that if you prefer, or just standby for next release.

Is it reproducible with standalone version of plugin?

**Comment by mahlonsmith** [comment]
> Is it reproducible with standalone version of plugin?

It is.  Just doublechecked that it is currently specific to the devel branch, everything seems fine under master.

WIth enough clicks, something paints over the entire screen and I have to kill it from a remote terminal.  

[capture.zip](https://github.com/sadko4u/lsp-plugins/files/9435292/capture.zip)

**Comment by sadko4u** [comment]
Hmmm. Then I need to check what happened between `master` and `devel` branch related to the UI.

**Comment by sadko4u** [comment]
Additional question: are drop-down combo boxes behaving well or in the similar case?

**Comment by sadko4u** [comment]
Reproduced almost the similar behaviour on Ubuntu 20.04.

**Comment by mahlonsmith** [comment]
> Additional question: are drop-down combo boxes behaving well or in the similar case?

Oh, yep.  Dropdowns are doing the same.

**Comment by sadko4u** [comment]
Seems that I've found the bug. Just need to understand the reason.

**Comment by sadko4u** [comment]
Oh, seems I've found the reason. Please try to rebuild from the latest `devel` branch (with `make fetch` update).

**Comment by mahlonsmith** [comment]
Yeah!  Looking good from here.  :+1:

**Comment by sadko4u** [comment]
There was a silly bug related to determining the position of the appearing popup window and it's size. Strange, but it wasn't reproducible for other machines. Your case helped to eliminate potential new bug for the 1.2.3 release. Thanks.
