### ISSUE TITLE
1.1.31: Failing test dsp.filters.dynamic

### ISSUE THREAD

**Issue by dvzrv** [sadko4u/lsp-plugins#218]
Hi! When trying to build 1.1.31 for Arch Linux I ran into a failing test:

```
Unit test 'dsp.filters.dynamic' has failed at file utest/dsp/filters/dynamic.cpp, line 360 with message:
  Output of functions for test 'avx::dyn_biquad_process_x8_fma3' differs at sample 502: -0.150797 vs -0.151848
```

Full build log: 
[lsp-plugins-1.1.31-build.log](https://github.com/sadko4u/lsp-plugins/files/7748927/lsp-plugins-1.1.31-build.log)

Build script (for previous version): https://github.com/archlinux/svntogit-community/blob/packages/lsp-plugins/trunk/PKGBUILD

**Comment by sadko4u** [comment]
Hello! Nothing has changed related to filters. This may be flacky.

**Comment by dvzrv** [comment]
hm, it is consistently failing unfortunately. Is there a way to disable particular tests on the CLI?

**Comment by sadko4u** [comment]
Is there information about previous build? Did the CPU changed since then?

**Comment by dvzrv** [comment]
The previous build was done on the same machine (back in November):
[lsp-plugins-1.1.30-2-x86_64-build.log](https://github.com/sadko4u/lsp-plugins/files/7750994/lsp-plugins-1.1.30-2-x86_64-build.log)
[lsp-plugins-1.1.30-2-x86_64-check.log](https://github.com/sadko4u/lsp-plugins/files/7750995/lsp-plugins-1.1.30-2-x86_64-check.log) <- that's where 1.1.31 fails

**Comment by sadko4u** [comment]
Could you try to build 1.1.30 now?

**Comment by dvzrv** [comment]
> Could you try to build 1.1.30 now?

Yes, that still works.

**Comment by sadko4u** [comment]
Magic. I mean, FMA instruction set is more precise since uses only one rounding per computation instead of two roundings when not using FMA. But the final difference is too huge (1e-3) at the end of array.

**Comment by sadko4u** [comment]
You can pass `-i <test-name>` flag to exclude the execution of some specific test in the command line.

**Comment by sadko4u** [comment]
The 1.2.0 release of plugins has been introduced and all DSP-related tests have been moved to library:
https://github.com/lsp-plugins/lsp-dsp-lib

Is the problem still actual?

**Comment by dvzrv** [comment]
@sadko4u I'll check as soon as I'm back from holidays in less than a week.

**Comment by dvzrv** [comment]
@sadko4u I am now on updating packages again. However, I fail to understand how to run the tests now. Could you please elaborate?

Do I have to run them in the modules/lsp-dsp-lib/ directory somehow?

Only somewhat related: Why are no git submodules used for the included projects? [modules.mk](https://github.com/sadko4u/lsp-plugins/blob/d2f660a8416313948011b1ee41f6124cb3404a72/modules.mk) basically implements that from scratch in a Makefile.

**Comment by dvzrv** [comment]
Looking at [the source tarball for 1.2.0](https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-src-1.2.0.tar.gz) it seems that the included lsp-dsp-lib/modules/ directory is empty, but [the project's modules.mk](https://github.com/lsp-plugins/lsp-dsp-lib/blob/da21db8cd55eb8361e64d799f3508ba6c29bc567/modules.mk) states things that it likely needs.

Sorry, that I am asking many questions/ poking around here, but the way of building with 1.2.0 is quite opaque to me at this point.

Looking at the implied way of building from a source tarball (that is auto-generated) using make to clone many repositories is unfortunately also contra to how Linux distributions handle sources of projects they are building. Usually all sources are acquired (and locked) before the build and some build environments already start to switch off network access during build.
So it 's great that you are providing combined source tarballs, I am just wondering whether all required files are currently contained in it.

**Comment by sadko4u** [comment]
Yes, almost all unit tests have been moved to the `lsp-dsp-lib` and to launch them you need to build `lsp-dsp-lib` for that.
Building test binaries can be achieved by issuing `TEST=1` option:
```
make config TEST=1
```

Then, after build, we get the `lsp-plugins-test` binary in the `.build/host/lsp-plugin-fw` subdirectory. But it shows that there are no unit tests are available:
```
.build/host/lsp-plugin-fw/lsp-plugins-test utest
No unit tests available
```

The second question, about submodules. The `modules.mk` file does not only hold the version and URL of the repository. It also impacts how the dependency should be built or handled. As you see, there are not only source-code based dependencies, but system, too. If you look deeper, some of submodules also can be built as a standalone libraries. So I need to add submodules there, too. And, if I am not wrong, this may cause the recursive dependencies between modules and submodules. Maybe I did something wrong and you're welcome for ideas.

**Comment by sadko4u** [comment]
> Looking at [the source tarball for 1.2.0](https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-src-1.2.0.tar.gz) it seems that the included lsp-dsp-lib/modules/ directory is empty, but [the project's modules.mk](https://github.com/lsp-plugins/lsp-dsp-lib/blob/da21db8cd55eb8361e64d799f3508ba6c29bc567/modules.mk) states things that it likely needs.

It is the result of how the current build system works. We specify the overall list of dependencies required to build the sources in the `modules.mk` file. Then, we have a `dependencies.mk` which define the required dependencies of the project, depending on the target architecture, operating system and other factors.

So to properly build, we need to check out the dependencies from the repositories according to the specified list and put it into the `modules` directory. As you understand, each module can depend on another one. For example, `lsp-dsp-lib` is dependent on `lsp-common-lib` and `lsp-test-fw`. But we don't need to have multiple instances of this submodule for building `lsp-plugins`. We just can have a plain directory with all submodules laying at the same path, build and link them together.

That's why the `lsp-dsp-lib` doesn't have anything in the `submodules` directory.

**Comment by dvzrv** [comment]
> Then, after build, we get the lsp-plugins-test binary in the .build/host/lsp-plugin-fw subdirectory. But it shows that there are no unit tests are available:

Okay, but how do I run the unit tests then?

As there is now no specific `install_lv2` target anymore I am also unable to run lv2lint against the built plugins, because the install target for the jack executables is broken:

```
make[4]: Entering directory '/build/lsp-plugins/src/lsp-plugins/.build/target/lsp-plugin-fw/jack'
install: target 'test//usr/local/bin/' is not a directory: No such file or directory
make[4]: *** [Makefile:292: install] Error 1
make[4]: Leaving directory '/build/lsp-plugins/src/lsp-plugins/.build/target/lsp-plugin-fw/jack'
make[3]: *** [Makefile:927: install_jack] Error 2
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/build/lsp-plugins/src/lsp-plugins/modules/lsp-plugin-fw/src'
make[2]: *** [Makefile:67: install] Error 2
make[2]: Leaving directory '/build/lsp-plugins/src/lsp-plugins/modules/lsp-plugin-fw'
make[1]: *** [Makefile:147: install] Error 2
make[1]: Leaving directory '/build/lsp-plugins/src/lsp-plugins/src'
make: *** [Makefile:68: install] Error 2
make: Leaving directory '/build/lsp-plugins/src/lsp-plugins'
```

I usually installed the lv2 plugins to a temporary location so that I could use lv2lint on them.

**Comment by sadko4u** [comment]
Hello again!

> Okay, but how do I run the unit tests then?

I think, in context of `lsp-plugins` package this is not possible at this moment. You need to run unit tests for the `lsp-dsp-lib` project.

> Personally, I would probably opt for a more feature-rich build system (e.g. meson) to deal with feature toggles and the various submodules/subprojects.

According to my understanding, meson doesn't allow to build project using different compiler options for different files. This is a requirement for the `lsp-dsp-lib` to have possibility to use different implementation of SSE and AVX-optimized routines.

That worked for me to reach LV2 installation only:
```
make install FEATURES=lv2 DESTDIR=<target directory>
```

**Comment by dvzrv** [comment]
> According to my understanding, meson doesn't allow to build project using different compiler options for different files. This is a requirement for the lsp-dsp-lib to have possibility to use different implementation of SSE and AVX-optimized routines.

Yes it does (and it's fairly straight forward). You can have a look at how this is done e.g. in [jack-example-tools](https://github.com/jackaudio/jack-example-tools), when overriding options for e.g. `jack_unload`:

https://github.com/jackaudio/jack-example-tools/blob/546d65f26b8a0437bf442a7b3a85f1b39978d329/tools/meson.build#L77-L89

> That worked for me to reach LV2 installation only:
> 
> ```
> make install FEATURES=lv2 DESTDIR=<target directory>
> ```

Thanks, that worked for me as well! I will open another ticket for the issues with lv2lint.

As this issue here was in regards to the unit tests, which I can not run in the context of this project anymore, I guess we can close this issue.

I only have a remaining question: Will the lsp-dsp-lib, as it is now a separate project and used by others (e.g. [zrythm](https://www.zrythm.org/en/index.html)) continued to be used as a static lib for lsp-plugins going forward or be linked dynamically? I'm asking because eventually I will have zrythm in the repos and will need to package lsp-dsp-lib for that anyways.
I guess static linking always makes more sense for plugins (although dynamically linking may make sense for distribution provided plugins).

**Comment by sadko4u** [comment]
> Will the lsp-dsp-lib, as it is now a separate project and used by others (e.g. [zrythm](https://www.zrythm.org/en/index.html)) continued to be used as a static lib for lsp-plugins going forward or be linked dynamically?

It will be used as a static part of the `lsp-plugins` bundle because the best principle for plugins is: the less external dependencies, the more stable behaviour is.

**Comment by sadko4u** [comment]
But you always can change the dependency type from `src` to `lib`, and then LSP Plugins will use the dedicated `lsp-dsp-lib` library.

**Comment by sadko4u** [comment]
I think since tests have been moved to a dedicated project, this issue can be closed now.
