### ISSUE TITLE
GUI doesn't fit correctly in Reaper For Linux

### ISSUE THREAD

**Issue by TobbeT** [sadko4u/lsp-plugins#22]
As shown in the picture the right side isn't showing all information.

![screenshot from 2019-01-18 10-16-14](https://user-images.githubusercontent.com/76429/51381245-e7468d80-1b13-11e9-8c85-4915f701575e.png)

**Comment by sadko4u** [comment]
Is it always reproducible on your system with any plugin?

**Comment by sadko4u** [comment]
No, it's not necessary. Just two plugins where the behaviour is always OK and where it's always not OK.

**Comment by sadko4u** [comment]
Seems that after this commit the problem has been solved: f1edd02b6b4445a98b7dce12446281445d0b12e4

At least, I can not reproduce the problem any more.

**Comment by sadko4u** [comment]
Merged changes into the **devel** branch: 0a80cc85db0e4889c54f07c3f4ef991193918d25

**Comment by sadko4u** [comment]
All changes are available in the 1.1.7 release that was just published.
