### ISSUE TITLE
1.1.31 Fails to build on armhf in Debian and Ubuntu

### ISSUE THREAD

**Issue by eeickmeyer** [sadko4u/lsp-plugins#222]
Ubuntu build logs: https://launchpadlibrarian.net/589180986/buildlog_ubuntu-jammy-armhf.lsp-plugins_1.1.31-1_BUILDING.txt.gz

Debian build logs show the same.

Let me know if there's anything I can do to assist or if this is already fixed and I just need to patch it with a commit.

Thanks!

**Comment by sadko4u** [comment]
The 1.2.0 release of plugins has been introduced. Is the problem reproducible on 1.2.0?

**Comment by sadko4u** [comment]
I think this issue is outdated. Use the latest 1.2.3 release.
