### ISSUE TITLE
Hue settings getting reverted when I re-open plugin window (1.1.31)

### ISSUE THREAD

**Issue by elcalenx** [sadko4u/lsp-plugins#224]
Hi! I just noticed this weird behaviour: if I adjust the hue parameters in any of the plugins that have that feature (I tried EQs and multiband plugins), when I close and re-open the plugin UI, the hue changes have reverted back to default values.

This is with version 1.1.31, LV2 plugins. Host is Reaper 6.51, running on a 64-bit Debian Testing system with Gnome.

**Comment by elcalenx** [comment]
Ah well, in that case never mind. :)

**Comment by sadko4u** [comment]
The 1.2.0 version of plugins was just released. I think, this problem is not actual any more.
