### ISSUE TITLE
compressor lookahead doesn't delay the dry signal as it delays the wet signal

### ISSUE THREAD

**Issue by kiilerix** [sadko4u/lsp-plugins#226]
Using lsp-plugins-lv2-1.1.31-1.fc35.x86_64 in Ardour , using lookahead and mixing dry and wet to get some parallel compression gives artifacts - probably comb filtering.

I would expect the dry signal to be delayed as much as the wet signal so the user could combine the options freely without considering implementation specifics.

**Comment by sadko4u** [comment]
Hmm, thanks. I'll look at this.

**Comment by sadko4u** [comment]
Can confirm the problem. Fix in progress...

**Comment by sadko4u** [comment]
Fixed the problem for Compressor, Expander, Gate and Dynamic Processor plugin series.
The changes will appear in 1.2.0 release.

**Comment by sadko4u** [comment]
Available in 1.2.0.
