### ISSUE TITLE
Import Equalizer APO config files

### ISSUE THREAD

**Issue by buscon** [sadko4u/lsp-plugins#227]
hi,

[Equalizer APO](https://equalizerapo.com/) is a common Windows EQ. Because of that it is possible to find many EQ settings, especially for headphones or speaker correction, in the Equalizer APO format, for example on this forum:
https://www.audiosciencereview.com/forum/index.php

Equalizer APO stores the eq settings in a simple text file, see attachment: [demo.txt](https://github.com/sadko4u/lsp-plugins/files/8237379/demo.txt)
It should not be difficult to add an option to import such settings.

Thank you!

**Comment by sadko4u** [comment]
The file in demo is supported by the LSP UI at this moment.
You just need to import it from the popup menu.
Click 'LSP' -> 'Import' and choose the corresponding menu item (related to RoomEQ Wizard), then in the dialog box select your file.

**Comment by buscon** [comment]
hi,

When I try to import such a file, nothing gets imported.
I am using version 1.1.30, is it maybe related to that?

**Comment by sadko4u** [comment]
Hmm, I doubt that something in 1.1.30 is broken.
I'll try your example soon and check. Maybe it's just a file parsing issue.

**Comment by buscon** [comment]
thanks!

just that you know, I get no error or anything, the settings simply do not change.

**Comment by sadko4u** [comment]
Today inspected the file.
Looks like very dirty format: somewhere commas are used instead of dots, 'H z' instead of 'Hz'.
Anyway, I've added less strict parsing support to the REW file format and it loads pretty well now.
Changes will be available in 1.2.0.

**Comment by buscon** [comment]
thank you for looking into that!

I actually took that demo.txt file from the APO Equalizer demo config files...

Two questions:
1. if the file is formatted correctly, should the import work in the current version too?
2. I guess you mean it will be available in the 1.3.2 version, right?

**Comment by sadko4u** [comment]
1. Yes, if it is formatted correctly (commas replaced with dots), it should work.
2. The last release of plugin bundle is 1.1.31. I'm doing last steps on releasing 1.2.0 with huge core refactoring and new many  features introduced.

**Comment by buscon** [comment]
> 1. Yes, if it is formatted correctly (commas replaced with dots), it should work.

excellent, I just tried that out and yes, it works!

>     2. The last release of plugin bundle is 1.1.31. I'm doing last steps on releasing 1.2.0 with huge core refactoring and new many  features introduced.

I see, thank you for the information.

**Comment by sadko4u** [comment]
Available in 1.2.0
