### ISSUE TITLE
Hardcoded SHAREDDIR

### ISSUE THREAD

**Issue by KottV** [sadko4u/lsp-plugins#229]
Hi,

Config var `SHAREDDIR` is ignored by `make config SHAREDDIR=/path/to` and seems to hardcoded in the `modules/lsp-plugins-shared/res/main/xdg/Makefile`

**Comment by sadko4u** [comment]
Can confirm the issue.
These patches should fix the problem:
https://github.com/lsp-plugins/lsp-plugin-fw/commit/4e14de436932b69fe89f21f73d80bdfab6d00856
https://github.com/lsp-plugins/lsp-plugins-shared/commit/b570746dbcf4e60ee5ef6ac58a5b05d61afdf1f8

**Comment by KottV** [comment]
fixed, thnx

**Comment by sadko4u** [comment]
Please don't close tickets until they get released.

**Comment by sadko4u** [comment]
Available in 1.2.1.
