### ISSUE TITLE
1.2.0 spectrum not working in equalizers

### ISSUE THREAD

**Issue by RattusSolarus** [sadko4u/lsp-plugins#230]
I have been using 1.1.30 from KX repo where the spectrum showed in the Parametric EQ LR. Old version was purged. 
In the new version 1.2.0 spectrum does not show in any EQ I have tried, both Parametric and Graphic. Tried PEQ x16 LR, PEQ x32 Stereo, PEQ x16 Mono, GEQx32 LR, and GEQ x16 Mono . 
These are the standalone JACK versions.
Dedicated analyzers such as Spektrumanalysator x2, x4, and Mono appear to work perfectly.
Checked all dependencies listed in README file and all are above minimum versions.

System:    Host: bullseye-brain Kernel: 5.15.0-16.1-liquorix-amd64 x86_64 bits: 64 Desktop: KDE Plasma 5.20.5 
           Distro: Debian GNU/Linux 11 (bullseye) 
Memory:    RAM: total: 15.59 GiB used: 2.24 GiB (14.4%)
CPU:       Info: Quad Core model: Intel Core i5-6500 bits: 64 type: MCP L2 cache: 6 MiB 
Graphics:  Device-1: NVIDIA GM204 [GeForce GTX 970] driver: nvidia v: 470.103.01 
           Display: x11 server: X.Org 1.20.11 driver: loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 3840x2160~60Hz 
           OpenGL: renderer: NVIDIA GeForce GTX 970/PCIe/SSE2 v: 4.6.0 NVIDIA 470.103.01

**Comment by sadko4u** [comment]
Yes, can confirm the problem for standalone version of plugins.
LV2 and VST2 versions work well, by the way.

**Comment by sadko4u** [comment]
The problem was releated to improper UI status update that caused the backend DSP code not to transfer the FFT data to the UI. Fixed in this commit:
https://github.com/lsp-plugins/lsp-plugin-fw/commit/27e47463ef5a39decc436bd4dbe27c4d616afbad

Changes will be available in 1.2.1

**Comment by RattusSolarus** [comment]
Excellent. I confirm LV2 works but use PEQ for room correction so better to use standalone and not to need an extra plugin host.

**Comment by sadko4u** [comment]
Available in 1.2.1.
