### ISSUE TITLE
LV2 version - Host crashes when saving template / config

### ISSUE THREAD

**Issue by christ-offer** [sadko4u/lsp-plugins#231]
When saving a config / template in at least LSP Impulse Reverb and a couple other plugins, both Carla and Ardour crash when saving a template. Both Ardour and Carla only reports a segfault.

The config is also not actually saved. The file exists, but loading it does nothing. (they are empty cfg files)

I am running pipewire, but don't know if that should matter.

`Segmentation fault (core dumped) carla`

and

`segmentation fault (core dumped) ardour6`

**Comment by sadko4u** [comment]
Hmmm, that's strange.
Oh, got invalid characters in the config for my case:
```
Package:             test ( @�XUU)
```
That may be the reason.

**Comment by sadko4u** [comment]
Seems to be a silly bug with invalid pointer dereference.
This patch should fix it: https://github.com/lsp-plugins/lsp-plugin-fw/commit/214a688865138430248de71b0ddd3a013044dc93
Are you available to build plugins from source and validate that problem has gone?

**Comment by aenemic** [comment]
Hey, didnt see your reply before now! I will test it tomorrow, it's a little late now :)

Do I just clone the main repo and build or?

**Comment by aenemic** [comment]
After building devel (it says 1.2.1 so i assume i did it right enough :)) it seems to be working fine! :) Saved and loaded a config without problem.

**Comment by sadko4u** [comment]
Nice to see!
The version of package is updated immediately after the release, so yes, it says 1.2.1 at this moment.
Will be available in 1.2.1.

**Comment by drtebi** [comment]
Just to let you know... loading configuration files via the command line works just fine in 1.2. As a workaround, while waiting for your distro to have the 1.2.1 version, one could manually configure configuration files and load them via the command line with the -c switch. Works just fine, and configuration files are very "human readable".

**Comment by sadko4u** [comment]
Available in 1.2.1.
