### ISSUE TITLE
LSP for system-wide audio equalization

### ISSUE THREAD

**Issue by mpeter50** [sadko4u/lsp-plugins#232]
In the past days I've been struggling with setting up a system-wide equalizer. I'm very new to the Linux sound infrastructure so probably I misunderstand quite a lot of things now, please let me know when I say something silly.

I've installed the `lsp-plugins` package on my openSUSE Leap system, and then also `jack-rack`, but the latter when started shows an error message titled "No LADSPA plugins were found", and detailing that there is a problem with the `LADSPA_PATH` environment variable.
This env var is actually nonexistent, running `echo $LADSPA_PATH` shows nothing.

Is it expected that I set this up manually? If so, how should I set it up?
The [website](https://lsp-plug.in/?page=manuals&section=installation) does not mention this env var.

Also, I've read in an other issue that since 1.2.0, LSP plugins has a GUI. But how do I access that? haven't found information on that either.

My goal is setting up the Equalizer APO config-compatible EQ plugin for my pipewire based system. So far I've found out how to set up LADSPA plugins for it, but I don't know what the plugins filename is, neither what parameters should I give it to set it up.

As I said, I'm pretty confused, and I'm possibly heading in the wrong way.
I'm searching for a solution in LSP plugins and LADSPA plugins because none of the GUI based off-the-shelf solutions work for me, because all of them have dependencies that would require me to use a bleeding edge system.

---

All text above was written when opening the issue, below I'll try to answer my questions for quick reference from the below comments and other sources.

### The `LADSPA_PATH` environment variable
According to [ladspa.org](https://www.ladspa.org/), the `LADSPA_PATH` environment variable is only needed if the plugin host I use doesn't find the plugins in the directories where they are stored. In If that is the case the user is meant to set up this env var themselves; on how, the linked page has details.

It looks like JACK Rack doesn't know where to find the plugins in an openSUSE environment, but it doesn't find the said environment variable either, and so it throws an error message about it.
I haven't investigated this further because I also realized JACK Rack is not what I need right now. It can only handle LADSPA plugins, and as it is said both here below and on the LSP documentation webpage, these cannot have a GUI, which I wanted so I can change settings on the go until I find out the configuration I want.
Instead, I started using Carla by KXStudio, which is compatible with more plugin types, and can be used for example with the LV2 type of the lsp-plugins release, and show the GUI of the plugin in a new window.
Also, later it turned out, Carla is useful for managing stream connections too, which means I don't need to self build QjackCtl on openSUSE anymore.

As an additional note, something tells me JACK Rack has a different problem actually.
The above webpage says setting the `LADSPA_PATH` env var will also help `listplugins` find the plugins, but the things it, it already finds them, without that env var. Maybe JACK Rack *requires* that env var for working correctly, but it not finding the problems might have a different reason.

### GUI for plugins of LSP
LSP is offered in multiple variants.
- the LADSPA variant does not have a GUI, the plugin format does not make that possible
- the LV2 format has a GUI, but the plugin needs to be loaded by a program that is a **plugin host** (this is responsible for making the plugin available for the sound system, and also for making it possible to open it's GUI)
- the LinuxVST and JACK variants are probably working in the same way or similarly to LV2 plugins, I haven't tried them out
- the **standalone release also has a GUI, and does not need a plugin host**. You start it from the application launcher or from the terminal, and it automatically connects to the JACK server (or to PipeWire, if you have it and the JACK compat libs installed). If started from the terminal it's easier to troubleshoot if it's not working, because it will be able to print error messages.

### System-wide EQ similar to Equalizer APO on Windows
It's possible to do that with LSP's plugins, but the functionality is split to 2 seperate plugins, and an additional something that handles the connections.

The alternative to the Graphic EQ's (15 and 31 bands) are the `LSP Graphic Equalizer x16 Stereo` and the `LSP Graphic Equalizer x32 Stereo`. It is also available for a few non-Stereo channel layouts.
The difference in the number of bands is that LSP's Grahphic EQ's have an additional 16 Hz band, and it has all the other bands that the graphic EQ of Equalizer APO has.

The alternative to the paramteric filters is the `LSP Parametric Equalizer x16 Stereo`. There is also a 32 band variant and a few non-Setero channel layout variants.
The different kinds of filters (high pass, low pass, etc) are available in the `Filter` dropdown above the knobs. You probably also want to set the `Mode` dropdown to `APO (DR)`, but I don't know much about these so you'll know it better.

You can set these up according to your settings in EQ APO, but according to #227 the Parametric Equalizer can be set up by just importing your EQ APO config file. Be aware though that it's not compatible with all of the fields, like comments, device selectors and includes, but it will not crash, it will use what it can.
On the older UI design, you import/expor config files by clicking on the bright blue text plates, on the newer the option is on the header if I'm not mistaken.

The only thing left is connections.
You have already opened the standalone version or loaded the LV2 variant in Carla, but the sound is still the same. This is because the plugin is currently not used for processing your audio.

![image](https://user-images.githubusercontent.com/83356418/162634739-e5350c98-0c50-4c18-bee2-bce4683fbbfe.png)

How you do that depends on your audio system, and is off topic here, but you can do the connections by hand temporarily in Carla, in QjackCtl, with pw-link, or other tools depending on how your system is set up. If you want to make that permanent, you'll need to find it out what is the proper way for your system and your needs.
I'm using PipeWire, and I'll probably make the plugin's input the default sink, and then set up a fix connection between the plugin's output and my headphone, but I'm still undecided; the final solution depends on what can I do with WirePlumber, maybe there is a better solution.

**Comment by sadko4u** [comment]
Hello!
LADSPA doesn't offer any GUI for plugins. You need to use LV2 or VST2 format of plugins for that.
For all LADSPA plugins the host (application running the plugins) generates it's own 'generic' UI that allows to set values for different controls of plugin.
You need to ensure that LADSPA plugins have been properly installed, the usual locations are:
```
/usr/lib/ladspa
/usr/local/lib/ladspa
```
The files should be named in the following manner:
```
/usr/local/lib/ladspa> ls -1
lsp-plugins-ladspa-1.2.0.so
```

Also you may use the `listplugins` command-line tool to ensure that plugins are available in the system:
```
listplugins
...
/usr/local/lib/ladspa/lsp-plugins-ladspa-1.2.1.so:
        Artistic Delay Mono (5002170/http://lsp-plug.in/plugins/ladspa/art_delay_mono)
        Artistic Delay Stereo (5002171/http://lsp-plug.in/plugins/ladspa/art_delay_stereo)
        Delay Compensator Mono (5002065/http://lsp-plug.in/plugins/ladspa/comp_delay_mono)
        Delay Compensator Stereo (5002066/http://lsp-plug.in/plugins/ladspa/comp_delay_stereo)
        Delay Compensator x2 Stereo (5002067/http://lsp-plug.in/plugins/ladspa/comp_delay_x2_stereo)
        Compressor LeftRight (5002092/http://lsp-plug.in/plugins/ladspa/compressor_lr)
        Compressor Mono (5002090/http://lsp-plug.in/plugins/ladspa/compressor_mono)
        Compressor MidSide (5002093/http://lsp-plug.in/plugins/ladspa/compressor_ms)
        Compressor Stereo (5002091/http://lsp-plug.in/plugins/ladspa/compressor_stereo)
        Crossover LeftRight x8 (5002168/http://lsp-plug.in/plugins/ladspa/crossover_lr)
        Crossover Mono x8 (5002166/http://lsp-plug.in/plugins/ladspa/crossover_mono)
        Crossover MidSide x8 (5002169/http://lsp-plug.in/plugins/ladspa/crossover_ms)
        Crossover Stereo x8 (5002167/http://lsp-plug.in/plugins/ladspa/crossover_stereo)
        Dynamic Processor LeftRight (5002100/http://lsp-plug.in/plugins/ladspa/dyna_processor_lr)
        Dynamic Processor Mono (5002098/http://lsp-plug.in/plugins/ladspa/dyna_processor_mono)
        Dynamic Processor MidSide (5002101/http://lsp-plug.in/plugins/ladspa/dyna_processor_ms)
        Dynamic Processor Stereo (5002099/http://lsp-plug.in/plugins/ladspa/dyna_processor_stereo)
        Expander LeftRight (5002108/http://lsp-plug.in/plugins/ladspa/expander_lr)
        Expander Mono (5002106/http://lsp-plug.in/plugins/ladspa/expander_mono)
        Expander MidSide (5002109/http://lsp-plug.in/plugins/ladspa/expander_ms)
        Expander Stereo (5002107/http://lsp-plug.in/plugins/ladspa/expander_stereo)
        Gate LeftRight (5002116/http://lsp-plug.in/plugins/ladspa/gate_lr)
        Gate Mono (5002114/http://lsp-plug.in/plugins/ladspa/gate_mono)
        Gate MidSide (5002117/http://lsp-plug.in/plugins/ladspa/gate_ms)
        Gate Stereo (5002115/http://lsp-plug.in/plugins/ladspa/gate_stereo)
        Graphic Equalizer x16 LeftRight (5002086/http://lsp-plug.in/plugins/ladspa/graph_equalizer_x16_lr)
        Graphic Equalizer x16 Mono (5002082/http://lsp-plug.in/plugins/ladspa/graph_equalizer_x16_mono)
        Graphic Equalizer x16 MidSide (5002088/http://lsp-plug.in/plugins/ladspa/graph_equalizer_x16_ms)
        Graphic Equalizer x16 Stereo (5002084/http://lsp-plug.in/plugins/ladspa/graph_equalizer_x16_stereo)
        Graphic Equalizer x32 LeftRight (5002087/http://lsp-plug.in/plugins/ladspa/graph_equalizer_x32_lr)
        Graphic Equalizer x32 Mono (5002083/http://lsp-plug.in/plugins/ladspa/graph_equalizer_x32_mono)
        Graphic Equalizer x32 MidSide (5002089/http://lsp-plug.in/plugins/ladspa/graph_equalizer_x32_ms)
        Graphic Equalizer x32 Stereo (5002085/http://lsp-plug.in/plugins/ladspa/graph_equalizer_x32_stereo)
        Latency Meter (5002133/http://lsp-plug.in/plugins/ladspa/latency_meter)
        Limiter Mono (5002122/http://lsp-plug.in/plugins/ladspa/limiter_mono)
        Limiter Stereo (5002123/http://lsp-plug.in/plugins/ladspa/limiter_stereo)
        Loudness Compensator Mono (5002163/http://lsp-plug.in/plugins/ladspa/loud_comp_mono)
        Loudness Compensator Stereo (5002163/http://lsp-plug.in/plugins/ladspa/loud_comp_stereo)
        Multiband Compressor LeftRight x8 (5002136/http://lsp-plug.in/plugins/ladspa/mb_compressor_lr)
        Multiband Compressor Mono x8 (5002134/http://lsp-plug.in/plugins/ladspa/mb_compressor_mono)
        Multiband Compressor MidSide x8 (5002137/http://lsp-plug.in/plugins/ladspa/mb_compressor_ms)
        Multiband Compressor Stereo x8 (5002135/http://lsp-plug.in/plugins/ladspa/mb_compressor_stereo)
        Multiband Expander LeftRight x8 (5002148/http://lsp-plug.in/plugins/ladspa/mb_expander_lr)
        Multiband Expander Mono x8 (5002146/http://lsp-plug.in/plugins/ladspa/mb_expander_mono)
        Multiband Expander MidSide x8 (5002149/http://lsp-plug.in/plugins/ladspa/mb_expander_ms)
        Multiband Expander Stereo x8 (5002147/http://lsp-plug.in/plugins/ladspa/mb_expander_stereo)
        Multiband Gate LeftRight x8 (5002156/http://lsp-plug.in/plugins/ladspa/mb_gate_lr)
        Multiband Gate Mono x8 (5002154/http://lsp-plug.in/plugins/ladspa/mb_gate_mono)
        Multiband Gate MidSide x8 (5002157/http://lsp-plug.in/plugins/ladspa/mb_gate_ms)
        Multiband Gate Stereo x8 (5002155/http://lsp-plug.in/plugins/ladspa/mb_gate_stereo)
        Oscillator Mono (5002132/http://lsp-plug.in/plugins/ladspa/oscillator_mono)
        Oscilloscope x1 (5002172/http://lsp-plug.in/plugins/ladspa/oscilloscope_x1)
        Oscilloscope x2 (5002173/http://lsp-plug.in/plugins/ladspa/oscilloscope_x2)
        Oscilloscope x4 (5002174/http://lsp-plug.in/plugins/ladspa/oscilloscope_x4)
        Parametric Equalizer x16 LeftRight (5002078/http://lsp-plug.in/plugins/ladspa/para_equalizer_x16_lr)
        Parametric Equalizer x16 Mono (5002074/http://lsp-plug.in/plugins/ladspa/para_equalizer_x16_mono)
        Parametric Equalizer x16 MidSide (5002080/http://lsp-plug.in/plugins/ladspa/para_equalizer_x16_ms)
        Parametric Equalizer x16 Stereo (5002076/http://lsp-plug.in/plugins/ladspa/para_equalizer_x16_stereo)
        Parametric Equalizer x32 LeftRight (5002079/http://lsp-plug.in/plugins/ladspa/para_equalizer_x32_lr)
        Parametric Equalizer x32 Mono (5002075/http://lsp-plug.in/plugins/ladspa/para_equalizer_x32_mono)
        Parametric Equalizer x32 MidSide (5002081/http://lsp-plug.in/plugins/ladspa/para_equalizer_x32_ms)
        Parametric Equalizer x32 Stereo (5002077/http://lsp-plug.in/plugins/ladspa/para_equalizer_x32_stereo)
        Phase Detector (5002064/http://lsp-plug.in/plugins/ladspa/phase_detector)
        Sidechain Compressor LeftRight (5002096/http://lsp-plug.in/plugins/ladspa/sc_compressor_lr)
        Sidechain Compressor Mono (5002094/http://lsp-plug.in/plugins/ladspa/sc_compressor_mono)
        Sidechain Compressor MidSide (5002097/http://lsp-plug.in/plugins/ladspa/sc_compressor_ms)
        Sidechain Compressor Stereo (5002095/http://lsp-plug.in/plugins/ladspa/sc_compressor_stereo)
        Sidechain Dynamic Processor LeftRight (5002104/http://lsp-plug.in/plugins/ladspa/sc_dyna_processor_lr)
        Sidechain Dynamic Processor Mono (5002102/http://lsp-plug.in/plugins/ladspa/sc_dyna_processor_mono)
        Sidechain Dynamic Processor MidSide (5002105/http://lsp-plug.in/plugins/ladspa/sc_dyna_processor_ms)
        Sidechain Dynamic Processor Stereo (5002103/http://lsp-plug.in/plugins/ladspa/sc_dyna_processor_stereo)
        Sidechain Expander LeftRight (5002112/http://lsp-plug.in/plugins/ladspa/sc_expander_lr)
        Sidechain Expander Mono (5002110/http://lsp-plug.in/plugins/ladspa/sc_expander_mono)
        Sidechain Expander MidSide (5002113/http://lsp-plug.in/plugins/ladspa/sc_expander_ms)
        Sidechain Expander Stereo (5002111/http://lsp-plug.in/plugins/ladspa/sc_expander_stereo)
        Sidechain Gate LeftRight (5002120/http://lsp-plug.in/plugins/ladspa/sc_gate_lr)
        Sidechain Gate Mono (5002118/http://lsp-plug.in/plugins/ladspa/sc_gate_mono)
        Sidechain Gate MidSide (5002121/http://lsp-plug.in/plugins/ladspa/sc_gate_ms)
        Sidechain Gate Stereo (5002119/http://lsp-plug.in/plugins/ladspa/sc_gate_stereo)
        Sidechain Limiter Mono (5002124/http://lsp-plug.in/plugins/ladspa/sc_limiter_mono)
        Sidechain Limiter Stereo (5002125/http://lsp-plug.in/plugins/ladspa/sc_limiter_stereo)
        Sidechain Multiband Compressor LeftRight x8 (5002140/http://lsp-plug.in/plugins/ladspa/sc_mb_compressor_lr)
        Sidechain Multiband Compressor Mono x8 (5002138/http://lsp-plug.in/plugins/ladspa/sc_mb_compressor_mono)
        Sidechain Multiband Compressor MidSide x8 (5002141/http://lsp-plug.in/plugins/ladspa/sc_mb_compressor_ms)
        Sidechain Multiband Compressor Stereo x8 (5002139/http://lsp-plug.in/plugins/ladspa/sc_mb_compressor_stereo)
        Sidechain Multiband Expander LeftRight x8 (5002152/http://lsp-plug.in/plugins/ladspa/sc_mb_expander_lr)
        Sidechain Multiband Expander Mono x8 (5002150/http://lsp-plug.in/plugins/ladspa/sc_mb_expander_mono)
        Sidechain Multiband Expander MidSide x8 (5002153/http://lsp-plug.in/plugins/ladspa/sc_mb_expander_ms)
        Sidechain Multiband Expander Stereo x8 (5002151/http://lsp-plug.in/plugins/ladspa/sc_mb_expander_stereo)
        Sidechain Multiband Gate LeftRight x8 (5002160/http://lsp-plug.in/plugins/ladspa/sc_mb_gate_lr)
        Sidechain Multiband Gate Mono x8 (5002158/http://lsp-plug.in/plugins/ladspa/sc_mb_gate_mono)
        Sidechain Multiband Gate MidSide x8 (5002161/http://lsp-plug.in/plugins/ladspa/sc_mb_gate_ms)
        Sidechain Multiband Gate Stereo x8 (5002159/http://lsp-plug.in/plugins/ladspa/sc_mb_gate_stereo)
        Slapback Delay Mono (5002130/http://lsp-plug.in/plugins/ladspa/slap_delay_mono)
        Slapback Delay Stereo (5002131/http://lsp-plug.in/plugins/ladspa/slap_delay_stereo)
        Spectrum Analyzer x1 (5002068/http://lsp-plug.in/plugins/ladspa/spectrum_analyzer_x1)
        Spectrum Analyzer x12 (5002072/http://lsp-plug.in/plugins/ladspa/spectrum_analyzer_x12)
        Spectrum Analyzer x16 (5002073/http://lsp-plug.in/plugins/ladspa/spectrum_analyzer_x16)
        Spectrum Analyzer x2 (5002069/http://lsp-plug.in/plugins/ladspa/spectrum_analyzer_x2)
        Spectrum Analyzer x4 (5002070/http://lsp-plug.in/plugins/ladspa/spectrum_analyzer_x4)
        Spectrum Analyzer x8 (5002071/http://lsp-plug.in/plugins/ladspa/spectrum_analyzer_x8)
        Surge Filter Mono (5002164/http://lsp-plug.in/plugins/ladspa/surge_filter_mono)
        Surge Filter Stereo (5002165/http://lsp-plug.in/plugins/ladspa/surge_filter_stereo)
...
```

Hope my information could be usable for you.
Please ask any questions if you're still meeting some troubles.

**Comment by mpeter50** [comment]
First of all, after posting my issue, I realized my comment was a bit chaotic, sorry for that.

> LADSPA doesn't offer any GUI for plugins. You need to use LV2 or VST2 format of plugins for that.

Yes, I was ready to make that compromise, for the reason that I can load that directly into PipeWire.

>You need to ensure that LADSPA plugins have been properly installed, the usual locations are:
>```
>/usr/lib/ladspa
>/usr/local/lib/ladspa
>```

Aha! That's probably part of my misunderstandings. I've installed the `lsp-plugins` package for my distrubution, but I don't have these directories and after consulting my package manager it looks like this package installs files like `/usr/bin/lsp-plugins-art-delay-mono` and `.desktop` files for each of them so they can be started, but not files like those that would go into directories listed [here](https://lsp-plug.in/?page=manuals&section=installation).
So, I should copy the LADSPA binary to the `/usr/local/lib/ladspa` directory after downloading the appropriate one from the releases, right?

> Also you may use the `listplugins` command-line tool to ensure that plugins are available in the system:

It looks like I don't have this tool for my system, or I haven't yet installed the package that provides it.
I use openSUSE, but no problem if you don't know what is the case here, I'll try to look it up.

**Comment by mpeter50** [comment]
It looks like I've found out the second "mystery": the `lsp-plugins` package is not actually what I want, but it's variants with a different name:

![image](https://user-images.githubusercontent.com/83356418/161354790-532e0617-8663-456c-a5f9-0ca9af29fe92.png)

So this is how I install the LADSPA format of the plugins which are available in that format. And similarly for the other formats too.
I'll probably still download the binary release, though, because of the available version.

**Comment by sadko4u** [comment]
Standalone version is a set of executable files, each of them runs an instance of plugin as a standalone application that works with JACK. You can connect the output of any JACK application to the running plugin and perform the audio processing.

**Comment by sadko4u** [comment]
The `ladspa` package provides `listplugins` tool for openSUSE.

**Comment by sadko4u** [comment]
@mpeter50 
How are you with this topic?
Are you still having problems?

**Comment by mpeter50** [comment]
Sorry for the late reply! I've been writing it for a few days, but something unexpected popped in.

> Standalone version is a set of executable files, each of them runs an instance of plugin as a standalone application that works with JACK. You can connect the output of any JACK application to the running plugin and perform the audio processing.

~~Does this mean it should appear as sinks and sources in tools like QjackCtl?
If so, this might not work with PipeWire's JACK compatibility libraries.~~

When I first asked how should they be installed I did so because thex didn't work for me. The UI opened, but I didn't see any new nodes and ports to which I could connect streams.
Then I got the idea to start a standalone plugin from the shell, and I saw the error messages that it wasn't able to connect to the Jack server.. at this moment came to my mind that even though I've installed the PipeWire-JACK compat libs in my testing VM, I did not do so in my real installation. After I did so, standalone plugins are noew apearing as new nodes in connection manager tools, and they work as expected.

Would you please consider adding an additional error indicator mechanism to the standalone version of the plugins? Currently one can only know if something is wrong if they start it from the terminal and look for the output.
I think it's fine if it doesn't even show what the error is, but only that there is an error, and would let the user know with a tooltip or something similar to check the error output of the plugin in a terminal.

> The ladspa package provides listplugins tool for openSUSE.
Thanks! I need to learn that `zypper search` by default only searches in the package names.
Installed the package and now I have the listplugins tool as expected.

---

Also, it looks like I got the LV2 Stereo 16 band Graphic EQ working with KXStudio Carla, and I was able to set it up like how I have it in Equalizer APO on Windows.

To anyone reading this in the future, it looks like using the standalone plugins directly has the same latency as using the LV2 version of it in Carla with Carla being in Jack single-client or multi-client mode, but in the default configuration of Carla, which is (internal) patchbay mode, it has a much larger latency, as measured with the latency measurement plugin of LSP plugins.
It still has some latency though, but it looks like it's originating from PipeWire's conenctions, possibly it can be reduced/eliminated but not sure about that now.

**Comment by mpeter50** [comment]
updated the title and the first comment with useful info

**Comment by sadko4u** [comment]
Here's important notice.

> the LinuxVST and JACK

The standalone plugins are exactly the JACK format of plugins. I mean, they use JACK server to perform audio processing.

**Comment by sadko4u** [comment]
According to you question in https://github.com/sadko4u/lsp-plugins/issues/232#issuecomment-1094333511, it seems that you didn't realize at the first time that plugins require connection to JACK server or it's adaptors.
It not a good idea to show the full log but I think it is a good idea to put an indicator that will show that connection to JACK has been estimated for JACK plugins. What do you think? If it is enough, then you can create another issue with such feature request. If you don't have any additional problems related to this issue, I think, we can close this issue.

**Comment by mpeter50** [comment]
> According to you question in https://github.com/sadko4u/lsp-plugins/issues/232#issuecomment-1094333511, it seems that you didn't realize at the first time that plugins require connection to JACK server or it's adaptors.

That's true. Actually I didn't know how exactly the plugins work, other than how to use their GUI, which is described for every plugin; so I understood what do I need to do once I integrated a plugin into my audio system, but what I missed is how I integrate a plugin into my audio system.
Now I see that everything outside the GUI is handled by the JACK infrastructure (various other software), and I either use the standalone versions, or a plugin host software for that.

> It not a good idea to show the full log but I think it is a good idea to put an indicator that will show that connection to JACK has been estimated for JACK plugins. What do you think?

I think that's fine. I'll open a new issue later today.

I'll close this issue now, thanks for the help!
