### ISSUE TITLE
Multisampler: lost midi note

### ISSUE THREAD

**Issue by Daniele71** [sadko4u/lsp-plugins#234]
HI, after the upgrade to 1.2,0, old projects made with Ardour and multisampler Lv2, all midi note number is set to 57 (A3). All projects and all instruments !

**Comment by sadko4u** [comment]
Hello!
This looks like being the similar problem to #233.
There is already fix, changes will be available in 1.2.1.
Sorry for the problem.

**Comment by sadko4u** [comment]
Available in 1.2.1.
