### ISSUE TITLE
1.2.0 doc and xdg files removed forever?

### ISSUE THREAD

**Issue by Vascom** [sadko4u/lsp-plugins#235]
I am maintainer of lsp-plugins at Fedora.
Could you please answer: doc and xdg files removed forever or their return is planned?

**Comment by sadko4u** [comment]
Hello!

The documentation and XDG files are present.
They have been moved all to related plugins.

For example, here is the documentation file for parametric equalizer:
https://github.com/lsp-plugins/lsp-plugins-para-equalizer/tree/master/src/doc/manuals/plugins
And the corresponding xdg files:
https://github.com/lsp-plugins/lsp-plugins-para-equalizer/tree/master/res/main/xdg/apps

By default, the `xdg` feature is disabled for regular build during the problems with GNOME (and I got a lot of claims about it).
If you want to enable the `xdg` feature, you can add `ADD_FEATURES=xdg` option to the `make config` launch:
```
make config ADD_FEATURES=xdg
```

Then you can build as ususal and get the final XDG files installed when you issue `make install`.

The documentation is enabled by default and should be built as a directory with HTML files and all necessary resources.

If you have any additional questions, you're welcome to ask.

**Comment by Vascom** [comment]
I download sources from https://github.com/sadko4u/lsp-plugins/releases and there is no docs and xdg. There no target in CmakeLists to build them.
Can I download single tar.gz with all included as for 1.1.31?

**Comment by sadko4u** [comment]
Here is a build of documentation:
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-doc-1.2.0.tar.gz

Here are builds with XDG files included:
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-jack-1.2.0-BSD-i586.tar.gz
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-jack-1.2.0-BSD-x86_64.tar.gz
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-jack-1.2.0-Linux-aarch64.tar.gz
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-jack-1.2.0-Linux-arm32.tar.gz
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-jack-1.2.0-Linux-i586.tar.gz
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-jack-1.2.0-Linux-riscv64.tar.gz
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-jack-1.2.0-Linux-x86_64.tar.gz

Here's the right source code package with all submodules included:
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-src-1.2.0.tar.gz

So I suppose you have downloaded the automatically created source code package by GitHub rather than packaged when release happened.

**Comment by Vascom** [comment]
Thanks. I will try it.

**Comment by Vascom** [comment]
doc seems built.
But xdg still not.
I use
```
/usr/bin/make -O -j8 V=1 VERBOSE=1
/usr/bin/make install DESTDIR=/home/vascom/rpmbuild/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64 INSTALL="/usr/bin/install -p"
```
And can't find compiled desktop files neither in DESTDIR nor at builddir.

**Comment by Vascom** [comment]
Also please change `PREFIX                     := /usr/local` and `LIBDIR                     := $(PREFIX)/lib` in make/configure.mk to something that can be defined via parameter for `make` command line like `make PREFIX=%{_prefix}`

**Comment by sadko4u** [comment]
You can enable XDG and specify prefix by applying this command:
```
make config ADD_FEATURES=xdg PREFIX=<your prefix>
```
There is also a bug with shared directory location at this moment, so you can apply patches from #229 or additionally specify the SHAREDDIR variable.

**Comment by Vascom** [comment]
Finally I built it. But with build flags the same problem.
It will be good if can be used system defined CFLAGS, CXXFLAGS, LDFLAGS.
```
sed -i 's|$(CFLAGS_EXT) \\|$(CFLAGS_EXT)  $(CFLAGS) \\|' make/tools.mk
sed -i 's|$(CXXFLAGS_EXT) \\|$(CXXFLAGS_EXT)  $(CXXFLAGS) \\|' make/tools.mk
sed -i "s|\$\(LDFLAGS_EXT\) -r|\$\(LDFLAGS_EXT\) -r %{build_ldflags}|" make/tools.mk
```

**Comment by sadko4u** [comment]
You can pass these flags at the `make config` stage, too.
For more options, prease refer to the output of `make help`.

**Comment by Vascom** [comment]
When I use this command
```
make config ADD_FEATURES=xdg PREFIX=%{_prefix} LIBDIR="%{_libdir}" \
CFLAGS="%optflags" CXXFLAGS="%optflags" LDFLAGS="%{build_ldflags}"
```
I have an error:
```
g++ -o /builddir/build/BUILD/lsp-plugins/.build/target/lsp-tk-lib/main/widgets/specific/LedMeterChannel.o -c main/widgets/specific/LedMeterChannel.cpp -f
PIC -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASS
ERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasy
nchronous-unwind-tables -fstack-clash-protection -fcf-protection -DLSP_TK_LIB_BUILTIN -fvisibility=hidden -DUSE_LIBPTHREAD -DUSE_LIBDL -DUSE_LSP_COMMON_L
IB -DUSE_LSP_LLTL_LIB -DUSE_LSP_R3D_IFACE -DUSE_LSP_RUNTIME_LIB -DUSE_LSP_DSP_LIB -DUSE_LSP_WS_LIB -DUSE_LIBSNDFILE -DUSE_LIBX11 -DUSE_LIBCAIRO -DUSE_LIB
FREETYPE     -I"/builddir/build/BUILD/lsp-plugins/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN -I"/builddir/build/BUILD/lsp-plugins/modules/l
sp-lltl-lib/include" -DLSP_LLTL_LIB_BUILTIN -I"/builddir/build/BUILD/lsp-plugins/modules/lsp-r3d-iface/include" -DLSP_R3D_IFACE_BUILTIN -I"/builddir/buil
d/BUILD/lsp-plugins/modules/lsp-runtime-lib/include" -DLSP_RUNTIME_LIB_BUILTIN -I"/builddir/build/BUILD/lsp-plugins/modules/lsp-dsp-lib/include" -DLSP_DS
P_LIB_BUILTIN -I"/builddir/build/BUILD/lsp-plugins/modules/lsp-ws-lib/include" -DLSP_WS_LIB_BUILTIN -I/usr/include/opus   -I/usr/include/cairo -I/usr/inc
lude/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/incl
ude/libxml2 -pthread -I/usr/include/pixman-1  -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib
64/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -I"/builddir/build/BUILD/lsp-plugins/modules/lsp-tk-lib/include" -DLSP_TK_LIB_BUILTIN
make[5]: Leaving directory '/builddir/build/BUILD/lsp-plugins/modules/lsp-tk-lib/src'
make[5]: Entering directory '/builddir/build/BUILD/lsp-plugins/modules/lsp-tk-lib/src'
  ld   [lsp-tk-lib] lsp-tk-lib.o
make[5]: Leaving directory '/builddir/build/BUILD/lsp-plugins/modules/lsp-tk-lib/src'
ld: unrecognized option '-Wl,-z,relro'
ld: use the --help option for usage information
make[5]: *** [Makefile:141: /builddir/build/BUILD/lsp-plugins/.build/target/lsp-tk-lib/lsp-tk-lib.o] Error 1
```
%{build_ldflags} is:
`-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1`

**Comment by sadko4u** [comment]
Hmm, for build the `LDFLAGS` variable has a bit another meaning:
```
LDFLAGS                   Linker flags for merging object files for target build
```
So this are flags for the `ld` tool.
The `-Wl,-z,relro` option is an option that is suitable for `gcc` or `g++` tool. 

Probably you can try to define:
```
EXE_FLAGS                 Flags to link executable files for target build
SO_FLAGS                  Flags to link shared object/library files for target build
```

**Comment by dvzrv** [comment]
Related to XDG integration and icons I am running into the following issue:

For some reason the install target for the XDG integration and icons does not honor `PREFIX`. When e.g. setting `PREFIX=/usr`, the plugins are installed using the correct prefix, while the XDG integration and icons are still installed below `/usr/local/`.

**Comment by sadko4u** [comment]
About XDG: this is known issue. Please look at issue #229 . There are already available patches.

**Comment by sadko4u** [comment]
@Vascom @dvzrv 
Are there still any unresolved questions related to this topic?

**Comment by dvzrv** [comment]
@sadko4u thanks for pointing at the patches. They unfortunately do not apply cleanly on top of 1.2.0 though (because of the CHANGELOG modifications).

**Comment by dvzrv** [comment]
FWIW, I have just adapted the patches and used them instead of manually moving files around now :)

**Comment by Vascom** [comment]
> @Vascom @dvzrv 
> Are there still any unresolved questions related to this topic?

No, thanks.
Package built successfully.

**Comment by sadko4u** [comment]
Then I'll probably close the issue.
