### ISSUE TITLE
1.2.0: lv2lint fails on plugins due to Plugin and UI Symbols

### ISSUE THREAD

**Issue by dvzrv** [sadko4u/lsp-plugins#237]
Hi! When building 1.2.0 for Arch Linux I also ran lv2lint against the resulting lv2 plugins again.

This now fails in the following ways (only showing for one plugin, but it is the same for all, see below check log):

```
lv2lint 0.14.0
Copyright (c) 2016-2021 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
<http://lsp-plug.in/plugins/lv2/trigger_stereo>
    [FAIL]  Plugin Symbols
              binary exports superfluous globally visible symbols:
                * _ZN3lsp7plugins17spectrum_analyzer18update_sample_rateEl
                * _ZN3lsp7plugins12oscilloscopeD1Ev
                * _ZN3lsp7plugins10oscillator21get_oversampling_modeEm
                * _ZN3lsp7plugins14phase_detectorC2EPKNS_4meta8plugin_tE
                * _ZN3lsp7plugins10oscillator16get_dc_referenceEm
                * _ZN3lsp4meta16sc_expander_monoE
                * _ZN3lsp4core11KVTListener8detachedEPNS0_10KVTStorageE
                * _ZN3lsp7plugins14trigger_kernel8AFLoaderC2EPS1_PNS1_7afile_tE
                * _ZN3lsp4meta11expander_lrE
                * _ZN3lsp4core10JsonDumper5writeEPKc
                * ... there is more, but the rest is being truncated
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
    [WARN]  Plugin Fork
              binary has a symbol reference to the 'fork' function
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
  <http://lsp-plug.in/ui/lv2/trigger_stereo>
    [FAIL]  UI Symbols
              binary exports superfluous globally visible symbols:
                * _ZN3lsp2ui12PortResolver7resolveEPNS_4expr7value_tEPKcmPKl
                * _ZN3lsp7plugins9art_delay14dump_art_delayEPNS_4dspu12IStateDumperEPKNS1_11art_delay_tE
                * _ZN3lsp2ui8IWrapper15import_settingsEPNS_2io11IInSequenceEb
                * _ZN3lsp3ctl6Marker6notifyEPNS_2ui5IPortE
                * _ZN3lsp7plugins10slap_delay7processEm
                * _ZN3lsp3ctl11AudioSample8DataSinkC2EPS1_
                * _ZN3lsp7plugins10oscillator15update_settingsEv
                * _ZN3lsp7plugins12room_builder19kvt_cleanup_objectsEPNS_4core10KVTStorageEm
                * _ZThn208_N3lsp3ctl7IntegerD1Ev
                * _ZN3lsp4plug6path_tD2Ev
                * ... there is more, but the rest is being truncated
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
    [WARN]  UI Fork
              binary has a symbol reference to the 'fork' function
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
```

Full build logs: 
[lsp-plugins-1.2.0-1-x86_64-build.log](https://github.com/sadko4u/lsp-plugins/files/8441421/lsp-plugins-1.2.0-1-x86_64-build.log)
[lsp-plugins-1.2.0-1-x86_64-check.log](https://github.com/sadko4u/lsp-plugins/files/8441422/lsp-plugins-1.2.0-1-x86_64-check.log)
[lsp-plugins-1.2.0-1-x86_64-package_lsp-plugins.log](https://github.com/sadko4u/lsp-plugins/files/8441423/lsp-plugins-1.2.0-1-x86_64-package_lsp-plugins.log)
[lsp-plugins-1.2.0-1-x86_64-package_lsp-plugins-docs.log](https://github.com/sadko4u/lsp-plugins/files/8441424/lsp-plugins-1.2.0-1-x86_64-package_lsp-plugins-docs.log)

At the time of writing these are the CFLAGS, CXXFLAGS and LDFLAGS available in the build environment:
https://github.com/archlinux/devtools/blob/a17c9c6a703901bff12779ab3b5bebde5194c617/makepkg-x86_64.conf#L43-L47

NOTE: At first I thought this might be LTO related (Arch Linux by default uses LTO now), but after disabling it for a build, it showed the same results.

**Comment by dvzrv** [comment]
FWIW, I can circumvent a failing call to lv2lint by using `-t "Plugin Symbols" -t "UI Symbols"`, but given that this error used to be not the case with 1.1.x, I guess it should be investigated and fixed (if possible).

**Comment by sadko4u** [comment]
It is iteresting for me at this moment, how do you build the package.
I seems that there is missing `-fvisibility=hidden` option for the compiler in the compilation flags.
Could you please submit your version of the `.config.mk` file here?

**Comment by dvzrv** [comment]
This is how the package is built: https://github.com/archlinux/svntogit-community/blob/packages/lsp-plugins/trunk/PKGBUILD

Here you can find the requested file: 
[config.mk.txt](https://github.com/sadko4u/lsp-plugins/files/8459714/config.mk.txt)

**Comment by sadko4u** [comment]
From the file you've provided I see:
```
CFLAGS=-march=x86-64 -m64 -O2 -DLSP_TESTING -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall
```

My usual configuration is the following:
```
CFLAGS=-march=x86-64 -m64 -O2 -fvisibility=hidden -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_INSTALL_PREFIX=\"/usr/local\"
```

I think this is not pretty correct:
```
make config TEST=1 FEATURES='doc lv2 vst2 jack ladspa xdg' PREFIX=/usr -C $pkgbase
```

If you specify the `TEST=1` flag, then the build system doesn't hide symbols for debug purpose.
I think you need to reconfigure and rebuild plugins for release purpose without the `TEST=1` flag.
This is important.

**Comment by dvzrv** [comment]
> If you specify the TEST=1 flag, then the build system doesn't hide symbols for debug purpose.
I think you need to reconfigure and rebuild plugins for release purpose without the TEST=1 flag.
This is important.

I see, this was not clear to me.
Previously the build system had a separate target for test stuff. This means I would have to duplicate the code-base to do separate builds, but given that [I can not run the unit tests anymore](https://github.com/sadko4u/lsp-plugins/issues/218#issuecomment-1091323818) anyways I might as well remove them.

**Comment by dvzrv** [comment]
Thanks! Without `TEST=1` this works as expected now!
