### ISSUE TITLE
1.2.0: All VSTs are overlinked with libm and libgcc_s

### ISSUE THREAD

**Issue by dvzrv** [sadko4u/lsp-plugins#238]
Hi! When packaging 1.2.0 for Arch Linux (also happens in earlier versions, but I didn't have time to report it), I noticed that the VSTs are all overlinked.

This is the truncated output of [namcap](https://man.archlinux.org/man/namcap.1), which is run on a created package in the packaging process to identify things that can be improved:

```
lsp-plugins W: Unused shared library '/usr/lib/libm.so.6' by file ('usr/bin/lsp-plugins-art-delay-mono')
lsp-plugins W: Unused shared library '/usr/lib/libgcc_s.so.1' by file ('usr/bin/lsp-plugins-art-delay-mono')
```

The overlinking happens for all VST plugins, see full log:
[lsp-plugins-1.2.0-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/sadko4u/lsp-plugins/files/8441726/lsp-plugins-1.2.0-1-x86_64.pkg.tar.zst-namcap.log)

I can't say whether this is a false-positive or something that can be fixed.

**Comment by sadko4u** [comment]
I have updated build scripts and now if I launch `make VERBOSE=1`, I get the following compilation line for the VST2 shared object:

```
g++ -o impulse-reverb-mono.so -march=x86-64 -m64 -O2 -fvisibility=hidden -std=c++98 -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_INSTALL_PREFIX=\"/usr/local\" -DLSP_INSTALL_PREFIX=\"/usr/local\" -DLSP_PLUGIN_PACKAGE_MAJOR=1 -DLSP_PLUGIN_PACKAGE_MINOR=2 -DLSP_PLUGIN_PACKAGE_MICRO=1 -DLSP_PLUGIN_PACKAGE_BRANCH=\"\" -DLSP_INSTALL_PREFIX=\"/usr/local\" -DEXT_ARTIFACT_NAME=\"lsp-plugins\" -DEXT_ARTIFACT_GROUP=\"lsp-plugins\"  -I"/home/sadko/eclipse/lsp-plugins/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN -I"/home/sadko/eclipse/lsp-plugins/modules/lsp-3rd-party/include" -DLSP_3RD_PARTY_BUILTIN -I"/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include" -DLSP_PLUGIN_FW_BUILTIN impulse-reverb-mono.cpp /home/sadko/eclipse/lsp-plugins/.build/target/lsp-common-lib/lsp-common-lib.o   -march=x86-64 -m64 -Wl,-z,relro,-z,now -Wl,--gc-sections -shared  -fPIC  -lpthread -ldl  
```

As we see, we have only `-lpthread` and `-ldl` dependency here.
Anyway, the `ldd` shows:
```
        linux-vdso.so.1 (0x00007ffeb7d0d000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc57efa7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fc57eda3000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fc57e9c9000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fc57e691000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc57e478000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc57e0bd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc57f3ca000)
```

That's strange. Any ideas?

**Comment by dvzrv** [comment]
This is the verbose log with https://github.com/lsp-plugins/lsp-plugin-fw/commit/2149c439e2afe9fabe600663e46125c29109cd6b and https://github.com/sadko4u/lsp-plugins/commit/9c511b95dcb9b6cf9eac4e43e2c9f174951c3a28 applied to 1.2.0:
[lsp-plugins-1.2.0-verbose.log](https://github.com/sadko4u/lsp-plugins/files/8468033/lsp-plugins-1.2.0-verbose.log)

**Comment by sadko4u** [comment]
Here's an example compilation line from log provided by you:
```
g++ -o lsp-plugins-spectrum-analyzer-x4 -march=x86-64 -m64 -O2 -fvisibility=hidden -std=c++98 -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_INSTALL_PREFIX=\"/usr\" -DLSP_PLUGIN_PACKAGE_MAJOR=1 -DLSP_PLUGIN_PACKAGE_MINOR=2 -DLSP_PLUGIN_PACKAGE_MICRO=0 -DLSP_PLUGIN_PACKAGE_BRANCH=\"\" -DEXT_ARTIFACT_NAME=\"lsp-plugins\" -DEXT_ARTIFACT_GROUP=\"lsp-plugins\"  -I"/build/lsp-plugins/src/lsp-plugins/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN -I"/build/lsp-plugins/src/lsp-plugins/modules/lsp-plugin-fw/include" -DLSP_PLUGIN_FW_BUILTIN spectrum-analyzer-x4.cpp /build/lsp-plugins/src/lsp-plugins/.build/target/lsp-common-lib/lsp-common-lib.o  -march=x86-64 -m64 -Wl,-z,relro,-z,now -Wl,--gc-sections -ldl
```

As we see here, there's only `-ldl` linker option that tells the compiler to link the library. There are no other extra libraries.
Maybe this case is a false positive?

**Comment by dvzrv** [comment]
> Maybe this case is a false positive?

That is very likely. If I find any other evidence I'll let you know.
Meanwhile I guess this can be closed. Thank you for looking into it!

**Comment by dvzrv** [comment]
I am unfortunately still experiencing this with 1.2.6.
The standalone and VST variants are affected.

[lsp-plugins-1.2.6-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/sadko4u/lsp-plugins/files/11061024/lsp-plugins-1.2.6-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-1.2.6-1-x86_64-build.log](https://github.com/sadko4u/lsp-plugins/files/11061025/lsp-plugins-1.2.6-1-x86_64-build.log)

This is problematic, because the many lines of overlinking obfuscate issues in the other (split) packages.

In autotools projects I often see this type of overlinking because of weird libtool default behavior, but I guess this is not the case here.
Shouldn't `strip` also take care of these cases theoretically? :thinking:

**Comment by sadko4u** [comment]
From [build log ](https://github.com/sadko4u/lsp-plugins/actions/runs/4493216114/jobs/7904131432):

```
   g++ [vst2] trigger-stereo.cpp
g++ -o trigger-stereo.so -march=x86-64 -m64 -O2 -fvisibility=hidden -fno-exceptions -fno-rtti -fdata-sections -ffunction-sections -fno-asynchronous-unwind-tables -pipe -Wall -DLSP_INSTALL_PREFIX=\"/usr\" -DLSP_PLUGIN_PACKAGE_MAJOR=1 -DLSP_PLUGIN_PACKAGE_MINOR=2 -DLSP_PLUGIN_PACKAGE_MICRO=6 -DLSP_PLUGIN_PACKAGE_BRANCH=\"\" -DLSP_INSTALL_PREFIX=\"/usr\" -DEXT_ARTIFACT_NAME=\"lsp-plugins\" -DEXT_ARTIFACT_GROUP=\"lsp-plugins\"  -I"/__w/lsp-plugins/lsp-plugins/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN -I"/__w/lsp-plugins/lsp-plugins/modules/lsp-3rd-party/include"  -I"/__w/lsp-plugins/lsp-plugins/modules/lsp-plugin-fw/include" -DLSP_PLUGIN_FW_BUILTIN trigger-stereo.cpp /__w/lsp-plugins/lsp-plugins/.build/target/lsp-common-lib/lsp-common-lib.o    -march=x86-64 -m64 -Wl,-z,relro,-z,now -Wl,--gc-sections -shared  -fPIC  -ldl
```

As you see, there are no special flags to explicitly link with `libstdc++`, `'libgcc_s` and `libm`.

Moreover, there are some functions used from standard C library which should be defined in `libgcc_s`, so I think the `overlinked` status is some case of false positive.

You can try to strip them but it is already done by:
```
-fdata-sections
-ffunction-sections
-Wl,--gc-sections
```

**Comment by dvzrv** [comment]
Hi! I would like to get back to this issue as it is still problematic for packaging.

This project is the only where I experience this problem (in *all* built artifacts).

To reiterate: On Arch Linux we rely on the following integration to detect linking against unused libraries: https://gitlab.archlinux.org/pacman/namcap/-/blob/5ac0244522e35d727a0b3ddb3c6b028ad82eba1e/Namcap/rules/unusedsodepends.py

Under the hood, this uses `ldd --function-relocs --unused`.
To give a simple example with the clap plugin in version 1.2.20:

```bash
$ readelf -d /usr/lib/clap/lsp-plugins.clap

Dynamic section at offset 0xaac388 contains 31 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libsndfile.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXrandr.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcairo.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000c (INIT)               0x262000
 0x000000000000000d (FINI)               0x655ccc
 0x0000000000000019 (INIT_ARRAY)         0x7c72e8
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x7c72f8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x310
 0x0000000000000005 (STRTAB)             0x2198
 0x0000000000000006 (SYMTAB)             0x338
 0x000000000000000a (STRSZ)              4487 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000007 (RELA)               0x3728
 0x0000000000000008 (RELASZ)             2482752 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0x35a8
 0x000000006fffffff (VERNEEDNUM)         5
 0x000000006ffffff0 (VERSYM)             0x3320
 0x000000006ffffff9 (RELACOUNT)          103126
 0x0000000000000000 (NULL)               0x0

$ ldd -r -u /usr/lib/clap/lsp-plugins.clap
Unused direct dependencies:
        /usr/lib/libgcc_s.so.1
```

In this example we can see that the library is clearly links against libgcc_s.so.1

```
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
```

However, according to `ldd` this use of the shared library seems not needed, but it is also not stripped.
I have packaged thousands of packages by now where these issues do not occur (albeit e.g. autotools based projects sometimes require patching of the created `libtool` script before calling `make` to use `ld --as-needed`).
Therefore I have a hard time believing that this is a "false positive".

In effect, this leads to *hundreds* of lines of warnings, as all shared objects are affected.
This makes it very hard to spot issues in the resulting packages.
@sadko4u Please reopen and fix this! 🙏 

[lsp-plugins-1.2.21-1-x86_64-build.log](https://github.com/user-attachments/files/19067479/lsp-plugins-1.2.21-1-x86_64-build.log)

[lsp-plugins-vst3-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067480/lsp-plugins-vst3-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-vst-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067481/lsp-plugins-vst-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-standalone-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067490/lsp-plugins-standalone-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-lv2-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067482/lsp-plugins-lv2-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-ladspa-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067483/lsp-plugins-ladspa-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-gst-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067485/lsp-plugins-gst-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-docs-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067488/lsp-plugins-docs-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-debug-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067487/lsp-plugins-debug-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-clap-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067489/lsp-plugins-clap-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[lsp-plugins-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067484/lsp-plugins-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)
[liblsp-r3d-glx-lib-1.2.21-1-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/19067486/liblsp-r3d-glx-lib-1.2.21-1-x86_64.pkg.tar.zst-namcap.log)

**Comment by sadko4u** [comment]
@dvzrv as I found, the option `-Wl,-as-needed` was needed to pass to the linker to exclude non-used libraries from linked ones.
This patch should help, please try:
https://github.com/lsp-plugins/lsp-plugins/commit/4b5bae7fc0b3500b02e0717d4295c04d15b1bbc1
