### ISSUE TITLE
1.2.0 build looks for files in empty 'modules' directory and fails.

### ISSUE THREAD

**Issue by barjac** [sadko4u/lsp-plugins#239]
make config reports OK
make fails looking for file in empty modules dir.

[baz@localhost lsp-plugins-1.2.0]$ make config
make[1]: Entering directory '/home/baz/build/BLD/BLD_Mga9_13/lsp-plugins/SOURCES/lsp-plugins-1.2.0'
Configuring build...
Architecture: x86_64 (-march=x86-64 -m64)
Features:     doc ladspa lv2 vst2 jack 
Configured OK
make[1]: Leaving directory '/home/baz/build/BLD/BLD_Mga9_13/lsp-plugins/SOURCES/lsp-plugins-1.2.0'
[baz@localhost lsp-plugins-1.2.0]$ make
make[1]: Entering directory '/home/baz/build/BLD/BLD_Mga9_13/lsp-plugins/SOURCES/lsp-plugins-1.2.0/src'
make[2]: Entering directory '/home/baz/build/BLD/BLD_Mga9_13/lsp-plugins/SOURCES/lsp-plugins-1.2.0/src'
make[2]: *** /home/baz/build/BLD/BLD_Mga9_13/lsp-plugins/SOURCES/lsp-plugins-1.2.0/modules/lsp-plugin-fw: No such file or directory.  Stop.

How is VERBOSE enabled as announced in 1.1.31 changelog?

**Comment by sadko4u** [comment]
Hello!
If you're building plugins from tarballs, you need this tarball:
https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-src-1.2.0.tar.gz

Otherwise, if you're using the build from source, then you need to issue:

```
make config
make fetch
make
```

**Comment by barjac** [comment]
Yes we were building from tarball, but it was from github:
Source0:	https://github.com/sadko4u/%{name}/archive/%{version}/%{name}-%{version}.tar.gz
Now changed to:
Source0:	https://github.com/sadko4u/%{name}/releases/download/%{version}/%{name}-src-%{version}.tar.gz
We still need 'make config'.
This progresses well but stops at "make: *** No rule to make target 'install_xdg'.  Stop."
The full build log is here: http://mtf.duckdns.org/pub/linux/barjac/distrib/cauldron/x86_64/log/lsp-plugins-1.2.0-0.3.mga9_bcj.src.rpm/build.x86_64.0.20220409172452.log

**Comment by sadko4u** [comment]
Hello again!

There is no more `install_xdg` target.

Instead of this, you can issue:
```
make install FEATURES=xdg
```

Also don't forget to enable the `xdg` feature when issuing `make config` because it is disabled by default:

```
make config ADD_FEATURES=xdg
```

**Comment by sadko4u** [comment]
@barjac 
Are there sill any questions related to the topic? Do you have all of the related problems resolved?

**Comment by barjac** [comment]
Hello again,
At last this all seems resolved, however your advice did not work as expected.
'make install FEATURES=xdg' only allows xdg to be installed.
Adding other 'features' to the list e.g.  make install FEATURES=xdg ladspa lv2 doc etc. causes the build to fail with "No rule to make target" errors, for the additional ones.
I spent many many hours trying to resolve this, until I finally removed the 'FEATURES=xdg..." completely.
Simply using 'make config ADD_FEATURES=xdg' during config was enough to build everything.

Another issue was that using PREFIX=/usr was not enough to remove /local/ as implied by the notes in github. I had to provide paths for BINDIR, SHAREDDIR, LIBDIR as well.

Maybe the above points could be better documented.

Thanks for all your help, we now have all packages building for x86_64, i586, aarch64 and arnv7hl.

**Comment by sadko4u** [comment]
> Simply using 'make config ADD_FEATURES=xdg' during config was enough to build everything.

Maybe I have improperly understood your question but I thought that you needed the special `install_xdg` target of the 1.1.x branch for some purpose. Otherwise yes, you just need to use `ADD_FEATURES=xdg` to build and install XDG icons.

> Another issue was that using PREFIX=/usr was not enough to remove /local/ as implied by the notes in github. I had to provide paths for BINDIR, SHAREDDIR, LIBDIR as well.

This is the known issue #229, you can look at it to find patches that will solve your problem with need of definition of `BINDIR`, `SHAREDDIR` and `LIBDIR`.
