### ISSUE TITLE
Bypass not working in the multiband compressor

### ISSUE THREAD

**Issue by unfa** [sadko4u/lsp-plugins#24]
When I enable "Bypass" it sounds like the effect is still doing it's work. Only when I do "Bypass" in Ardour itself it does indeed work and I can compare what the compressor is actually doing to the dry signal.

**Comment by sadko4u** [comment]
The issue with bypass button is fixed in this commit: 21d6399b3f4b9dd243a2bddec011404d4d632723

**Comment by sadko4u** [comment]
Merged changes into **devel** branch.
Will be available in the nearest release.

**Comment by sadko4u** [comment]
All changes are available in the 1.1.7 release that was just published.
