### ISSUE TITLE
Show error indicator on the standalone plugins' GUI when a JACK error has occurred

### ISSUE THREAD

**Issue by mpeter50** [sadko4u/lsp-plugins#244]
In #232 I discovered that the standalone version of plugins require a JACK server to which they can connect for normal operation, but they don't show an indication when a problem occurred connecting to JACK.

This means that when connecting to JACK is not successful, the plugin fails half-silently: the GUI does not indicate that something went wrong, but instead it prints an error message to stderr.
The problem with this is that if a user just runs the plugin from the application launcher, and they don't know or forgot that they could try running it from the terminal, then they may not be able find out what the problem is.

In the mentioned issue we have already discussed that showing the log output in the plugin's GUI is not a good idea, but instead there could be a simple Error indicator that would light up if something went wrong, and would instruct the user with a tooltip or an other way to try starting the plugin from the terminal to see the exact error messages.
I would also like to add that I think besides the Error indicator a GUI display might also be possible in a simple and non-intrusive way, if it would happen similarly to the configuration save/load features:
- accessible in the [Menu](https://user-images.githubusercontent.com/83356418/164218891-004cf73b-15ce-47e1-bd1a-88ffe00ba18f.png) section on the header's main menu bar
- on clicking it's menu item a new window would be opened for the log messages alone

**Comment by sadko4u** [comment]
At this moment, there is possible to add only the jack connection indicator. This will be done in 1.2.1.
Adding separate log messages with the new window is not trivial since I don't have such widget in the toolkit yet.
If you really need the log messages, please create another one issue.

**Comment by sadko4u** [comment]
Available in 1.2.1.

**Comment by mpeter50** [comment]
> If you really need the log messages, please create another one issue.

It's not that important, I think the indicator is good enough.

Thanks!
