### ISSUE TITLE
Impulse Response plugin and FIR

### ISSUE THREAD

**Issue by buscon** [sadko4u/lsp-plugins#248]
hi,

I am wondering whether the Impulse Response plugin can also use FIR samples. I could not find any information about it in the documentation.

Thanks.

**Comment by buscon** [comment]
I am anot aexpert about it, but for what I understood, FIR samples usually have some silence before the beginning of the impulse (not only after). I was wondering whether loading such a sample in the IR plugin would work or cause problems.

**Comment by sadko4u** [comment]
The more silence at the beginning of sample you have, the more latency you will get in your signal. This is the only difference.

**Comment by buscon** [comment]
> The more silence at the beginning of sample you have, the more latency you will get in your signal. This is the only difference.

ok, thanks, that's good to know!
