### ISSUE TITLE
GUI takes a long time to open in Carla

### ISSUE THREAD

**Issue by unfa** [sadko4u/lsp-plugins#25]
I've heard about this problem before, and I'm experiencing it myself.

I'm using LSP plug-ins in Ardour with no issues, but all of them have the same problem when loaded in Carla.

When I try opening the GUI, nothing happens for as many as 20 seconds, then the plug-in window opens and everything works as expected.

In Ardour the GUIs open nearly instantly.

What could cause this?

**Comment by sadko4u** [comment]
What plugin do you use?
As far as I remember, it's a known problem of LV2 URID interface. LSP Plugins can request many URIDs from the host, and Carla is slow at resolving them because is forced to do a lot of IPC between host and plugin processes.
http://lv2plug.in/ns/ext/urid/

**Comment by falkTX** [comment]
What is the best plugin to use to reproduce this?
I am interested on getting these plugins working nicely there. Won't be for v2.0 series, but for v2.1

**Comment by sadko4u** [comment]
@falkTX i think the best is one of Multi-sampler plugins.

**Comment by falkTX** [comment]
Carla needs some optimizations for the atom message passing.
For now, in the develop branch at least, I made it so that LSP plugin UIs will not run in bridge mode (and thus work as expected).
See https://github.com/falkTX/Carla/commit/fc39645141a63e1834d94bcde8c7060a513b3d06

Need to package this version in the kxstudio repos...

**Comment by falkTX** [comment]
Carla master branch has this now too (forgot to come back here yesterday and report this).
It made it just in time for v2.0.0

With this, lsp-plugins UIs work nicely in carla.
It is a workaround, but anyway this is not an issue in lsp-plugins directly, but rather Carla that needs some optimizations.
I think this issue can be closed

**Comment by sadko4u** [comment]
Okay, that's nice. Then I'm closing this issue.
