### ISSUE TITLE
redrawing/resizing issue

### ISSUE THREAD

**Issue by Daniele71** [sadko4u/lsp-plugins#252]
HI, sometimes there are sono redrawing issue, part of the background inside the plugin (lv2 version) windows. Resizing the window fix the the problem.

Attacched image show it well.
Ardour 6.9
Lsp-plugins-1.2.1
openSUSE TW
AMD card (rx 550)
![lsb-draw](https://user-images.githubusercontent.com/40473719/170824137-48c36004-c7ae-4832-980e-36b5b546d384.jpg)

**Comment by sadko4u** [comment]
This is particularly related to how Ardour is embedding plugin window inside of it's wrapping window.
Sometimes it is behaving wrong. That could be avoided by the lv2ui:Resize extension if it didn't introduce another problems (possibility of setting the size of window less than lv2ui:Resize has reported).
I'm thinking on how to properly introduce the workaround.
Maybe @x42 can help me here.

**Comment by x42** [comment]
Not sure if Ardour has control over this, Ardour just calls `suil_instance_new` and libsuil manages the child window (here libsuil's adapter x11-in-gtk2). -- more likely you want to ask @drobilla

**Comment by sadko4u** [comment]
At this moment, the UI wrapper monitors all X11 resize events and should handle the window resize properly. But it seems that X11 resize events are not always delivered to the plugin's nested window. Maybe this is related of how GTK allocates the space for the plugin window inside of the parent wrapping window. By the other side, it also seems that GTK is not properly handling all resizes of the nested plugin window. LSP uses X11 Resize events to resize the window. This is my conclusion as a result of that fact that plugin window becomes sometimes improperly aligned inside of the parent wrapping window: it becomes clipped from left and top as it is placed not at the (0, 0) position of the parent window's container.

**Comment by sadko4u** [comment]
I'll be inspecting this issue soon but the window sizing was always a serious problem...

**Comment by drobilla** [comment]
There are probably holes in the wrapper.  I'm not sure, haven't gotten into it yet.  At this point it's clear that the resize extension was a mistake, so someone needs to dig into making the various wrapping situations work properly without it.  Essentially paying down the debt of leaning on resize kludges for years.

@falkTX has had some success with this in DISTRHO but I'm not on top of that.  My plan is to look into it when there's simple toolkit-free plugins in lv2kit that don't (ab)use the resize extension and can be used to test that everything works properly.  Then we'll have simple canonical examples of how to deal with UI size (among other things) properly and can finally put this mess behind us.

That will still take a while, though.  If you want to look into it first, feel free.  I just maintain Suil, really, I'm no Gtk expert.

**Comment by falkTX** [comment]
For my side, any lv2 plugin made with develop branch of DPF no longer relies on UI resize extension to adjust its size. It is used if host supports it, but ignored and with everything still working if not.
Cardinal is an example of such plugin, though d_info example plugin (part of DPF itself) can also be used for this and it is much simpler plugin.

For host side, Carla supports this without having to use any extensions. For that carla listens to some X11 sub-configure event (dont recall details now, but was an event for children configures).
With it, DPF based plugins can be resized by host without needing extensions, and plugin can also resize themselves and have the host resize its window to match.

I have tested to work on X11, with some success on Windows too (I think it "just works" there, havent retested recently).
macOS seems to be more tricky to deal with, but I have seen APIs that should in theory allow it too.

For the worst possible case, hosts can simply query the plugin ui size on a regular timer, reaper for vst2 does this, as vst2 uis tend to be quite broken in behaviour..

**Comment by sadko4u** [comment]
@drobilla is it a good reason to deprecate the lv2ui:Resize feature?

**Comment by sadko4u** [comment]
One more information: X11 allows to provide size constraints of the window:
https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/XSetWMNormalHints.html

LSP Plugins set there hints for any plugin window:
https://github.com/lsp-plugins/lsp-ws-lib/blob/aa3230b0219205a542d3f5e159f50c7a114bca55/src/main/x11/X11Window.cpp#L343-L384

So the property `WM_NORMAL_HINTS` can be used to obtain the minimum and maximum possible size of the child window.

**Comment by drobilla** [comment]
@sadko4u Yes, it was deprecated in the recent release https://lv2plug.in/ns/extensions/ui#resize

**Comment by sadko4u** [comment]
Here is an example of how the new feature of window sizing works in upcoming 1.2.2 release:
https://www.youtube.com/watch?v=APdBe8PXIZg

We see that VST2 plugin reports the window size to the host and the wrapping window changes the actual size.
It is a good behaviour since VST2 has the only one option of how to change the window size by the UI itself.
For LV2, the wrapping window should control the change of window size but it does nothing at this moment.
We can use the ui:Resize feature but the wrapping window will become strict borders without the possibility to change it's size.
