### ISSUE TITLE
LV2 plugins have many superfulous visible symbols

### ISSUE THREAD

**Issue by falkTX** [sadko4u/lsp-plugins#253]
At least the LV2 plugin, maybe LADSPA and VST2 (didnt check those yet) has extra useless visible symbols, for example:

* INT123_synth_1to1_s32_s_avx_asm
* INT123_dct64_real_avx
* INT123_getcpuflags
* INT123_synth_1to1_s_x86_64_accurate_asm
* INT123_dct36_x86_64
* INT123_synth_1to1_x86_64_accurate_asm
* INT123_synth_1to1_s32_s_x86_64_asm
* INT123_synth_1to1_s_avx_accurate_asm
* INT123_dct64_real_x86_64
* INT123_synth_1to1_real_s_x86_64_asm

Plugins should be self-contained, these symbols seem to be internal things from the LSP DSP lib, which should not get exported.
On LV2, in ideal conditions, plugins only export `lv2_descriptor` and `lv2ui_decriptor`.

**Comment by sadko4u** [comment]
That's not true:
```
nm -D lsp-plugins-lv2-1.2.2.so | grep 'T '
0000000000267a34 T _fini
000000000014e4c8 T _init
0000000000267a00 T lv2_descriptor
```

It seems that you're building plugins in some another way.

**Comment by falkTX** [comment]
you're right, these come from libmpg123, through the use of libsndfile.
nevermind this one then
