### ISSUE TITLE
JACK standalone needlessly links to libjack

### ISSUE THREAD

**Issue by falkTX** [sadko4u/lsp-plugins#254]
The JACK standalones are linking to libjack, but they do not use those functions.
Since you are loading libjack.so.0 at runtime, you should not link to libjack, which makes the entire thing a bit pointless..

**Comment by sadko4u** [comment]
Don't see any linking to `libjack`:

```
ldd /usr/local/bin/lsp-plugins-trigger-mono
        linux-vdso.so.1 (0x00007ffec4586000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f7c50c61000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f7c50887000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f7c5054f000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7c50336000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f7c4ff7b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7c51069000)
```

Or am I missing something?

**Comment by falkTX** [comment]
Link comes in the jack lib.
```
ldd /usr/lib/lsp-plugins/liblsp-plugins-jack-1.2.1.so  | grep jack
        libjack.so.0 => /lib/x86_64-linux-gnu/libjack.so.0 (0x00007f3bbb16d000)
```

**Comment by sadko4u** [comment]
Libjack is responsible for estimating connection to JACK, too. It contains the JACK wrapper inside of the library so I think that it is reasonable to link them together. The binaries are only responsible to find the proper `libjack` version and execute the main method with proper arguments which will launch the JACK wrapper with corresponding plugin.

**Comment by falkTX** [comment]
but you are talking to jack over dlopen+dlsym, no? not calling any jack functions directly.
so there is no need to link to jack.

I noticed this because debian packaging tools reported such thing.
They can detect when a shared library is used, but no symbols from that library are being used.
libjack is one of them, there were no others from the whole build

**Comment by sadko4u** [comment]
I mean the following lauch flow:
1. You launch, for example, `lsp-plugins-trigger-mono`
2. `lsp-plugins-trigger-mono` searches for `liblsp-plugins-jack-1.2.2.so`, ensures that it provides the required version of interface, and loads it to the memory by `dlopen`.
3. After that, it obtains the function `plug_fw_jack_main` and passes the unique identifier of the `lsp-plugins-trigger-mono` plugin and command line arguments.
4. The `plug_fw_jack_main` instantiates the `jack::Wrapper` and `jack::UIWrapper` classes.
5. The `jack::Wrapper` implements the main JACK workflow: it launches `jack_client_open`, `jack_on_shutdown`, `jack_get_sample_rate`, `jack_activate` etc.

So, actually, `libjack` is required for that.

**Comment by falkTX** [comment]
hmm today is not my day, I am unable to reproduce the issue now.
so nevermind this one either, I will reopen if I see it happening again, and make sure to give more details if so.
sorry for the noise

**Comment by sadko4u** [comment]
No problem, sometimes bad things happen.
