### ISSUE TITLE
Add CI for all subprojects and lsp-plugins

### ISSUE THREAD

**Issue by dvzrv** [sadko4u/lsp-plugins#259]
In continuation of https://github.com/lsp-plugins/lsp-plugins-expander/issues/3:

It would be very good to have build tests against a few of the downstream distributions on which lsp-plugins is packaged.
All subprojects should have this, so they can be tested before integrating e.g. a new version into lsp-plugins.

I can help you with the setup for an Arch Linux container in github CI.

When looking at issues around lv2lint failing on the plugins, it would be good to directly integrate that as well.

**Comment by sadko4u** [comment]
It would be a good idea. How should we integrate the CI with the project and other sub-projects?

**Comment by dvzrv** [comment]
As an example, there's the container setup for the builds that are non-Ubuntu [in the jack-example-tools projects](https://github.com/jackaudio/jack-example-tools/blob/c3d07f03454da5bb8f4a03acd1417efd53f2cff0/.github/workflows/build.yml#L19-L75) (you can ignore the pawpaw related stuff for now unless you want to target jack-related windows and macos builds).

Something similar to that already helps to ensure that changes do not affect downstreams (as much).

**Comment by sadko4u** [comment]
Will we use the Github CI or some other?

**Comment by dvzrv** [comment]
I'd recommend github CI for Linux/macOS/Windows builds. If you also target the BSDs, you'll need to integrate with [cirrus CI](https://cirrus-ci.com/) (see e.g. again [jack-example-tools as an example](https://github.com/jackaudio/jack-example-tools/blob/c3d07f03454da5bb8f4a03acd1417efd53f2cff0/.cirrus.yml)).

Both are fairly easy to configure using YAML files.

**Comment by dvzrv** [comment]
I could create a PR for one of the subprojects later and notify you about it here.

**Comment by falkTX** [comment]
Would be great to make use of valgrind to check for memory leaks and other runtime issues.
I can contribute that part as a 2nd stage of the PR after @dvzrv

**Comment by sadko4u** [comment]
@dvzrv that would be nice.

**Comment by sadko4u** [comment]
Propagated the changes for all available plugins.

**Comment by dvzrv** [comment]
> Propagated the changes for all available plugins.

Cool. Would have probably been good to wait a little for @falkTX to add the other changes for valgrind/carla though. It allows for a few more tests.

**Comment by sadko4u** [comment]
Today challenge helped a lot to improve the build process.
I have caught several memory leaks and accesses to the uninitialized memory.

**Comment by falkTX** [comment]
testing for macos and windows is also possible btw.
and you can also have it automatically upload release binaries

CI/CD stuff is super handy yes

**Comment by sadko4u** [comment]
I don't have versions for Windows and MacOS at this moment. Maybe sometimes.

**Comment by sadko4u** [comment]
I have added CI for almost all possible projects and base libraries.

**Comment by sadko4u** [comment]
Available in 1.2.3 release!
