### ISSUE TITLE
Dynamic processor volume spike 

### ISSUE THREAD

**Issue by thoth-amon** [sadko4u/lsp-plugins#260]
Found this in Dynamic Processor Stereo Jack Version. 1.2.2 When you have more than one threshold active, if the db dial is set close, but not exact,  then there is a big volume spike. I outputted into spectrum analyser and it maxed out everything.(don't advise testing with speakers on unless using a limiter)
![Screenshot_20220623_123859](https://user-images.githubusercontent.com/78971907/175290590-785a880d-13f6-4ebb-b288-6b51921170de.png)

Just tried it in lv2 and it doesn't happen there.

**Comment by sadko4u** [comment]
And the reason is the 15 dB knee.

![изображение](https://user-images.githubusercontent.com/12834464/175298053-c15db12a-8aba-46b6-a4dc-671a363270fe.png)

It's not a bug, it is how the knees are being processed.

**Comment by sadko4u** [comment]
No problem. Just be careful with setup :).
