### ISSUE TITLE
Feature/Documentation request: Eighth-order Linkwitz–Riley crossover

### ISSUE THREAD

**Issue by LebedevRI** [sadko4u/lsp-plugins#262]
For https://lsp-plug.in/?page=manuals&section=para_equalizer_x32_stereo,
for `LRX - Linkwitz-Riley based filters`, the available `Slope`s are 1..4.
Am i guessing correctly that said slope *is* the LR filter order,
so that LRX w/ Slope=4 is `Fourth-order Linkwitz–Riley crossover (LR4, LR-4)`?

My particular question is, is there a reason why higher orders are not implemented?
I'm looking at this in context of cobbling together a `Frequency Selector` effect:
X-Ref https://github.com/wwmm/easyeffects/issues/1596#issuecomment-1166357799

**Comment by sadko4u** [comment]
> Eighth-order Linkwitz–Riley crossovers (LR8) have a very steep, 48 dB/octave (160 dB/decade) slope. They can be constructed by cascading two 4th-order [Butterworth](https://en.wikipedia.org/wiki/Butterworth_filter) filters.

Do not consider the Slope being equal to the number of the LR filter.

LSP Plugins allow to set up filter slope up to 96 db/octave.
The short table:
LR2 - 12 db/octave
LR4 - 24 db/octave
LR8 - 48 db/octave.

So 96 db/octave is something like LR16 according to the classification of the LR filter.
More information here:
https://en.wikipedia.org/wiki/Linkwitz%E2%80%93Riley_filter

By the other side, it probably would be good to add the description about match to the LR classification in the combo box.

**Comment by sadko4u** [comment]
Updated text labels. Will be available in 1.2.3.

**Comment by LebedevRI** [comment]
Thank you!

**Comment by sadko4u** [comment]
Available in 1.2.3 release!
