### ISSUE TITLE
Separating Frequencies to Examine (Hear) for Parametric Equalizer

### ISSUE THREAD

**Issue by WielewickiRobert** [sadko4u/lsp-plugins#263]
I'd love to see an option to mute everything but the frequency curve we are modifying (maybe by pressing solo button with alt?). It would be great for every curve available, but would be most useful for resonance finding. I can boost them but it doesn't work too well always.

**Comment by XYC-EXP** [comment]
At the moment it can be substituted by lowering the volume and boosting a band. I am also looking forward to this feature, which will make the lsp plugin super professional.

**Comment by sadko4u** [comment]
Do I right understand that you need such behaviour in the UI: when changing some filter parameter, make this filter soloing. When releasing the parameter, make all filters work again?

**Comment by WielewickiRobert** [comment]
It might be soloing during changing parameters **and** separate button to hear ONLY these frequencies (and maybe by extension, everything expect? in other UI place). Cause when changing parameters you would hear wanted section, but when you stop changing them you would get all frequencies again. So need to be thought out well.

**Comment by XYC-EXP** [comment]
What we discussed maybe automatically add a high-pass filter and a low-pass filter according to the q-value and freq we are editing.(maybe other filter type?)

(I name it: auto-band-pass)

What you mentioned above is also a good feature.(I name it: auto-soloing)

**Comment by sadko4u** [comment]
> hear ONLY these frequencies

There is a `solo` button that allows to listen for a specific filter.
How do you consider the else way of hearing the shelving filter, for example?

> What we discussed maybe automatically add a high-pass filter and a low-pass filter according to the q-value and freq we are editing.(maybe other filter type?)

This works only for several filters like resonance, bell and notch. This won't work for other filters since they already work with large range of spectrum.

**Comment by XYC-EXP** [comment]
Emmm, such as only applying auto-high-pass when editing a high-shelf to hear those part separately.

And maybe another option can be used to control how accurately the auto-band-pass separate the freq range you are adjusting.(such as parameters like 20db/oct, 40db/oct....)

**Comment by WielewickiRobert** [comment]
![image](https://user-images.githubusercontent.com/109214142/181010834-d37b0bc8-c296-4c8c-a845-41d89f2a40f1.png)
`There is a solo button that allows to listen for a specific filter.`
Well, it does disable all other filters. What I would want is a way to hear only affected frequencies in filter (this narrow curve) to hear for unwanted sounds. 
`At the moment it can be substituted by lowering the volume and boosting a band.`
Works, but is a workaround and is not perfect

**Comment by sadko4u** [comment]
Available in 1.2.6.
