### ISSUE TITLE
Inverse option for the gate

### ISSUE THREAD

**Issue by sadko4u** [sadko4u/lsp-plugins#264]
There is an feature suggestion to implement the `inverse` option for the gate.
When there is no signal, the gate should be opened. When there is some signal above the threshold, the gate becomes closed.
It seems that the gate characteristics should look like:
![image](https://user-images.githubusercontent.com/12834464/179493768-1cc65480-2c72-408f-9454-78d20c050a6f.png)

**Comment by dstra2** [comment]
Hi @sadko4u

I would like to point out that the "inverse gate" curve shown is actually a compression curve. It therefore makes more sense to implement this curve in the compressor. For upward compression, the curve has already been implemented ("Boosting" mode, see #181). It would therefore only be necessary to additionally implement the curve for downward compression.

By the way, other compressors also realize both upward and downward compression with a curve of 3 lines (see e.g. [FabFilter Pro-MB manual](https://www.fabfilter.com/help/ffpromb-manual.pdf) p.12 or [Waves C4 manual](https://www.waves.com/1lib/pdf/plugins/c4-multiband-compressor.pdf) p.19ff).

Kind regards,
Dstra

**Comment by sadko4u** [comment]
Hello!
This is true but for the compressor the characteristics of the compression curve will be slightly different rather for the gate since compressor uses two knees while gate just introduces transition between two levels.

**Comment by dstra2** [comment]
> ...while gate just introduces transition between two levels.

What is the use case of this feature? If it is side-chain ducking (not to be confused with side-chain compression), the characteristic curve should probably look like this:
![Side-Chain Ducking](https://user-images.githubusercontent.com/24780672/184365018-6e825556-7a0f-4ef8-b72b-726a300a1c4d.jpg)
Picture: Gate of a Behringer X32 in Ducking-Mode

**Comment by sadko4u** [comment]
> Picture: Gate of a Behringer X32 in Ducking-Mode

Hmmm, this looks like a more correct gate curve for ducking mode than I suggested.

**Comment by sadko4u** [comment]
![изображение](https://user-images.githubusercontent.com/12834464/184666659-d205c237-9ffe-45ed-94d1-d76abbbf539e.png)

Seems that the new applied changes to the gate are behaving well.
I think I also need to dig into compressor and implement the characteristic at the start of the topic.

**Comment by sadko4u** [comment]
Added the limited gain reduction feature to the compressor:

![изображение](https://user-images.githubusercontent.com/12834464/185239698-05d34f51-ecb2-435a-8bbd-8e25b2c58703.png)

**Comment by sadko4u** [comment]
All changes will be available in 1.2.3 release.

**Comment by sadko4u** [comment]
Available in 1.2.3 release!
