### ISSUE TITLE
build issue with lv2@1.18.6

### ISSUE THREAD

**Issue by xhub** [sadko4u/lsp-plugins#268]
First thanks a lot for your work on these plugins, they are really wonderful!

Looks like the last version of lv2 no longer installs `/usr/include/lv2.h`. Hence the build fails.

The file is now in `/usr/include/lv2/core/lv2.h` and `/usr/include/lv2/lv2plug.in/ns/lv2core/lv2.h`.
To the best of my knowledge, the first one does not exists in prior versions of lv2, but the directory `/usr/include/lv2/lv2plug.in/ns/lv2core` seem to exists, see https://packages.debian.org/sid/amd64/lv2-dev/filelist

With the following patch, it compiles against 1.18.6:
```
--- a/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/lv2/lv2.h  2022-08-02 14:40:52.332308107 +0200
+++ b/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/lv2/lv2.h  2022-08-02 14:41:12.928667048 +0200
@@ -24,7 +24,7 @@
 
 
 // LV2 includes
-#include <lv2.h>
+#include <lv2/lv2plug.in/ns/lv2core/lv2.h>
 #include <lv2/lv2plug.in/ns/ext/atom/atom.h>
 #include <lv2/lv2plug.in/ns/ext/atom/forge.h>
 #include <lv2/lv2plug.in/ns/ext/atom/util.h>
```

I did not test against earlier version of lv2.

**Comment by sadko4u** [comment]
Hmmmm. I think we need to get the explanation from @drobilla about change in headers first.
After that, we will find the proper solution, I think.

**Comment by sadko4u** [comment]
Anyway, it looks like a breach of backward compatibility in lv2.

**Comment by xhub** [comment]
Hm it looks like I jumped the gun too soon. After https://github.com/lv2/lv2/commit/e4996396487babb5007c43f42d2b68eb50f08fec that file is again installed. Sorry for the noise. We can close the bug or wait for a new lv2 release.

**Comment by sadko4u** [comment]
Seems like being a reasonable commit in LV2.

**Comment by drobilla** [comment]
> To the best of my knowledge, the first one does not exists in prior versions of lv2

The "lv2/core/lv2.h" (etc) style has been around since LV2 0.16.0 (Feb 2019).

**Comment by sadko4u** [comment]
@drobilla so, what's the best option?

```C++
#include <lv2.h>
```

or

```C++
#include <lv2/core/lv2.h>
```

or

```C++
#include <lv2/lv2plug.in/ns/lv2core/lv2.h>
```

?

**Comment by drobilla** [comment]
I'd like everything to consistently move to the second style (`lv2/core/lv2.h` `lv2/atom/atom.h` etc) eventually.

**Comment by sadko4u** [comment]
This commit (with some refactoring) should fix the issue
https://github.com/lsp-plugins/lsp-plugin-fw/commit/9ff9fe56e3ff6829d8a7daff2c555bc5c0a28c7c

**Comment by drobilla** [comment]
Looks fine to me, thanks.  The URI-style ones are "fine" too if you prefer that, I just think no real benefit ever came from that scheme for LV2 anyway, so the newer shorter style just looks a lot cleaner and less weird/terrifying.

Anyway, I'll get out a point release with the `<lv2.h>` thing fixed shortly.
