### ISSUE TITLE
Can't access remote directories

### ISSUE THREAD

**Issue by tonebender** [sadko4u/lsp-plugins#27]
When loading a preset or impulse response or other file, I need to open it using the file explorer dialog of the plugins, and I'm having problems when accessing remote directories in my home directory.

I have most of my files on a server, whose directories are mounted in my home directory via sshfs on my small home network. This works great 99% of the time - I rarely, if ever, have any hickups when accessing them from the desktop computer. For example, I often save large images from The Gimp, or music projects from Reaper this way - running the app on the desktop computer and saving the data on the server. As far as the desktop applications are concerned, the remote directories are no different from local directories (?).

But in the file dialogs in lsp plugins, the remotely mounted directories in my home dir either don't show up, or don't lead anywhere. Sometimes when selecting them, the whole dialog just closes.

Any ideas?

I'm happy to do some testing, provide logs, etc. if you help me get started.

Thanks!

**Comment by sadko4u** [comment]
I need to test it. Seems that mounted directories have different file attributes so the algorithm that scans for files/directories simply does not detect them.
