### ISSUE TITLE
1.2.3: Issue with source tarball

### ISSUE THREAD

**Issue by dvzrv** [sadko4u/lsp-plugins#270]
Hi! upon trying to upgrade the Arch Linux package to 1.2.3, I ran into an issue with the source tarball, that you provide:

```
tar -tvf lsp-plugins-src-1.2.3.tar.gz
gzip: stdin: invalid compressed data--format violated
-rw-r--r-- sadko/users  109164 2022-09-06 22:55 lsp-plugins/modules/lsp-plugins-limiter/res/doc/screenshots/sc_limiter_mono.png
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

It seems something is not right with that file in the archive

**Comment by sadko4u** [comment]
Hmm, that's strange. Reloaded the archive.

**Comment by dvzrv** [comment]
Thanks! The new archive seems to be intact! :)
