### ISSUE TITLE
Changes introduced in 1.2.3 release

### ISSUE THREAD

**Issue by Digitalone1** [sadko4u/lsp-plugins#271]
Hello @sadko4u.

Can you please list which are the exact changes to plugin parameters in the new release? These will help to reflect those changes in EasyEffects.

Please refer also to this EE [ticket](https://github.com/wwmm/easyeffects/issues/1807).

**Comment by sadko4u** [comment]
Hello!

* The `Boosting gain` option for the compressor from (0 dB ... 72 dB) to (-72 dB .. +72 dB).
![изображение](https://user-images.githubusercontent.com/12834464/188931564-7dcf06bd-4dc6-43bf-b19d-21f332c30269.png)

* 'Reduction' option for the gate has extended range from (-inf..0 db) to (-inf ... +72 dB).
![изображение](https://user-images.githubusercontent.com/12834464/188931751-8e280afe-c201-455a-bce4-b8260ff2b9b1.png)

The same is true for multiband versions of plugins, too.

**Comment by Digitalone1** [comment]
Since you reported it also in the related EE ticket, I think this can be closed.
