### ISSUE TITLE
Plugins cause high cpu usage on Xorg process

### ISSUE THREAD

**Issue by ryze312** [sadko4u/lsp-plugins#272]
It seems that all plugins in some way make Xorg process to produce high cpu usage.
Different plugins cause different amounts of usage, but parametric equalizers use up to 100%.

Maybe there is a problem in communicating with X Server?
![Screenshot_20220909_204857](https://user-images.githubusercontent.com/50497128/189413940-2d77b239-c1b2-4b86-8662-a166d8aeea9d.png)

Version: 1.2.3
OS: Artix Linux OpenRC
CPU: Intel i7-3612QM

**Comment by sadko4u** [comment]
Seems that removing double buffering for the window is not a good idea for several systems.
Could you please check this patch?
https://github.com/lsp-plugins/lsp-tk-lib/commit/9afbda5b0db2909304248bdc69bb5c03a4278f74

**Comment by ryze312** [comment]
Usage is back to normal with patch applied. Thanks!
I am using Intel Graphics, maybe it has something to do with it.

**Comment by xhub** [comment]
I had the same issue in Ardour and the patch fixed the issue. Without it, it is unfortunately not possible to use the very good LSP plugins to mix more than a few tracks. Is version 1.2.4 around the corner or should this patch be applied downstream (in the linux distribution)? Thanks!

**Comment by xhub** [comment]
Thanks for your quick answer. I will take care of adding the patch in Gentoo.

Wishing you and your loved ones the best in these trouble times.

**Comment by sadko4u** [comment]
Available in 1.2.4!
