### ISSUE TITLE
Source='Max' for Sidechain for multi-channel plugins?

### ISSUE THREAD

**Issue by LebedevRI** [sadko4u/lsp-plugins#274]
Consider e.g. compression.

While source=middle works well in most of the cases,
if at some moment the left channel is relatively quiet,
and there's relatively loud sound only in the right channel,
the level between the two is, well, middle/average/median,
and the resulting gain reduction will be smaller than
if both of the channels got that loud sound.

So it may sometimes be useful to instead be able to use loudest (or quietest) of the two?

**Comment by sadko4u** [comment]
Good idea.

**Comment by sadko4u** [comment]
Available in 1.2.4!

**Comment by LebedevRI** [comment]
Thank you!
