### ISSUE TITLE
Lo-pass LRX(MT) x4 misbehaves or wrongly displayed

### ISSUE THREAD

**Issue by atskler** [sadko4u/lsp-plugins#275]
Lo-pass LRX(MT) x4 misbehaves or wrongly displayed

@44.1k
<img width="874" alt="at44100" src="https://user-images.githubusercontent.com/85284199/197289409-0d9c1168-2c84-4a81-84ba-33a468eb4931.png">

@96k
![at96000](https://user-images.githubusercontent.com/85284199/197289516-8236eef7-959e-41de-acf1-5678d1050b84.png)

**Comment by sadko4u** [comment]
This is the result of the aliasing effect.
From the documentation:
```
Bilinear Transform is easy to implement, and in most plugins this type of transform is used. The main disadvantage of this transform is that it distorts the form of the filter's curve while moving it's poles and zeros from low to high frequencies. Also it's noticeable that low-pass filters transformed by using bilinear transform have -INF dB amplification level at the Nyquist frequency.

Completely different is the behaviour of filters transformed by Matched Z Transform. These filters have identical to the analog filters frequency and phase graph but have another disadvantage: they have aliasing at high frequencies that is caused by reflecting high frequencies from the range limited by Nyquist Frequency. 
```

The LSP equalizer shows the curve of the ideal analog filter. But the aliasing actually gives the picture you see in the Reaper's curve analysis.

**Comment by atskler** [comment]
I see. Thank you for the explanation.
And sorry for not reading thoroughly the documentation.
