### ISSUE TITLE
Add loop feature to the sampler

### ISSUE THREAD

**Issue by sadko4u** [sadko4u/lsp-plugins#276]
While the note is pressed, it is a good feature to set up a part of the sample as a constantly looping part to make the sample sound infinitely until the note is released.
Typical controls should be provided:
* start of the loop range;
* end of the loop range;
* crossfade length between two sequential repetitions;
* crossfade type (constant power, linear, etc).

**Comment by gvnnz** [comment]
@sadko4u this is a cool feature to add. What about adding also loop directions? 
* Forward: loop goes from start to end
* Backward: loop goes from end to start
* Ping-pong: loop goes from start to end, then from end to start

**Comment by sadko4u** [comment]
Available in 1.2.4!
