### ISSUE TITLE
Automatic point creation in parametric eq

### ISSUE THREAD

**Issue by azim-sahim** [sadko4u/lsp-plugins#277]
It'll be more fast to equalize something if i can double click in a place to create a filter. Maybe you can define filter by coordinate of double click, for example in 0-100 Hz - Hi-pass; 100-300 Hz - Lo-shelf; 300-7k Hz - bell; 7k-15k Hz - Hi-shelf; 15k-20k Hz - Lo-pass. 

Also, how i can set that my issue is feature request?

**Comment by sadko4u** [comment]
Marked as a feature request.

**Comment by sadko4u** [comment]
Available in 1.2.4!
