### ISSUE TITLE
Can't launch LSP natively under Wayland, very slow under XWayland

### ISSUE THREAD

**Issue by IvanDSM** [sadko4u/lsp-plugins#278]
I'm trying to use the standalone versions of the LSP plugins on a Wayland and Pipewire based install of Arch Linux, but I find myself unable to use the plugins natively under wayland, as trying to run them with the DISPLAY env var set to empty or wayland-0 just leads the program to output "[ERR] Can not open display" and die.

Trying to run the plugins under XWayland results in slowness to the point of it being unusable. I'd be happy to provide any further information or debug logs as I'd really love to be able to use the LSP plugin suite on this install!

**Comment by sadko4u** [comment]
Never tried to launch plugins under Wayland compositor. At this moment, only X11 protocol is supported.

**Comment by sadko4u** [comment]
Oh, forgot about this issue. Maybe this also can be a cause of your UI problems under XWayland.
https://github.com/sadko4u/lsp-plugins/issues/272

You can apply the patch from the issue or wait until the 1.2.4 gets released.

**Comment by sadko4u** [comment]
Hello! Just released 1.2.4 please check if you still have troubles with XWayland.

**Comment by IvanDSM** [comment]
I apologize for the late response, but it did indeed solve my problems. Thanks a lot for your work! :)
