### ISSUE TITLE
Legacy LSP Theme - Manual entry is not visible

### ISSUE THREAD

**Issue by stefan-franz** [sadko4u/lsp-plugins#286]
Hello, first great plugins. 

One thing: In the Legacy LSP Theme: If i make double click to an entry, its not visible, what i put in - after return its visible. 
And only the . (point) works, not the , (comma) - e.g parametric EQ

OT:
Can your limiter act like brickwall limiter. Only cut the peaks e.g. drum and not reduce the signal?

**Comment by sadko4u** [comment]
> One thing: In the Legacy LSP Theme: If i make double click to an entry, its not visible, what i put in - after return its visible.
> And only the . (point) works, not the , (comma) - e.g parametric EQ

Oh, I need to check this. Probably this is because of missing some styles in the schema.

> Can your limiter act like brickwall limiter. Only cut the peaks e.g. drum and not reduce the signal?

Disable the ALR option.

**Comment by sadko4u** [comment]
We have had a long discussion here: https://discourse.ardour.org/t/lsp-plugins-1-2-4-released/108086/15

I think the only one thing to check is how the `xdg-open <path-to-some-plugin-file>` should handle. Probably the case can be in access permissions to the files.

**Comment by stefan-franz** [comment]
Don't worry about that. Thats ok for me. I have not the knowledge and the time to find out a solution - and on your online manual i can read all.

**Comment by sadko4u** [comment]
Then I suppose we can close this issue.
