### ISSUE TITLE
Can't compile 1.2.4 tar.gz  - no modules directory

### ISSUE THREAD

**Issue by jrigg** [sadko4u/lsp-plugins#288]
I just tried compiling lsp-plugins-1.2.4 from the source tar.gz (on Void Linux x86_64 glibc).

The tar.gz  is  only 73kB and an extra 'make fetch' step was needed before it would compile.
Is this change since 1.2.3 intentional?

**Comment by sadko4u** [comment]
Probably you have downloaded the wrong source code package?
Here's the package you need:

https://github.com/sadko4u/lsp-plugins/releases/download/1.2.4/lsp-plugins-src-1.2.4.tar.gz

**Comment by jrigg** [comment]
I did indeed download the wrong source code package.  I need to read the list of package names more carefully. Sorry for the noise.

Thanks for your work on these plugins, especially in these difficult times.
