### ISSUE TITLE
Sampler: Loop and Stretch Overlay only goes so far.

### ISSUE THREAD

**Issue by thoth-amon** [sadko4u/lsp-plugins#291]
See the screenshot below. The end point is further than the overlay shows. The overlay only follows the dial up to a certain point which differs per sample. The same happens with the stretch overlay (it stops at the exact same point).

![Screenshot_20221230_155357](https://user-images.githubusercontent.com/78971907/210089617-908f5972-c328-4f2b-83de-6e247b870671.png)

**Comment by sadko4u** [comment]
I think I need to refactor the rendering mechanism of the sample. At this moment, the `Stretch` and `Loop` don't show the real size for the sample. That was done due to the complexity but finally I find that providing another solution just gave another one complexity. Should be redone.

**Comment by sadko4u** [comment]
Fixed in 1.2.5
