### ISSUE TITLE
Knob: add modifier key for circular mode 

### ISSUE THREAD

**Issue by jean-emmanuel** [sadko4u/lsp-plugins#292]
Hi! I often find myself clicking and dragging the knob's scale by accident and the resulting behavior (a big jump of value) can be quite harsh when applied to a Makeup or a Gain. Wouldn't it be safer to add a modifier key for this interaction mode ?

Many thanks for the hard work :)

**Comment by sadko4u** [comment]
All knobs are pretty big to hit their centers pretty accurate. Do you use touchpad or some other controller instead of mouse?
Also, we already have `Ctrl` key as an accelerator and `Shift` key as a decelerator.

**Comment by jean-emmanuel** [comment]
Nope, just using the mouse on a rather big screen. I guess I could pay more attention though ;). Out of curiosity, do you have feedback on how much the circular mode is used ? To me (and that's very subjective) this mode has always seemed somewhat useless at best, hazardous at worse, especially when there are accelerator and decelerator modifiers available.

**Comment by sadko4u** [comment]
In some cases it is useful, when the knobs are very stiff because have a pretty large range.
Maybe having just a global switch that turns off any reaction on the knob's s scale clicks could be your preference.

**Comment by jean-emmanuel** [comment]
That'd be great indeed !

**Comment by sadko4u** [comment]
Available as an option in 1.2.5.

**Comment by jean-emmanuel** [comment]
The default knob behavior added to the extremely high makeup max value got us again in studio this week, a simple misclick made our ears go boom... I know this is documented but it felt somewhat absurd to explain the operator « oh sorry I forgot about that : be careful where you grab the knob, you might just set a +60dB makeup if you don't pay attention ». Related to https://github.com/lsp-plugins/lsp-plugins/issues/334
