### ISSUE TITLE
Oscilloscope plugins cause crash within Reaper

### ISSUE THREAD

**Issue by trochitv** [sadko4u/lsp-plugins#294]
Every other plugin I tested so far works fine. Opening the oscilloscope plugins within Carla is a functioning workaround.
Thanks for making these awesome plugins :)

**Comment by sadko4u** [comment]
What plugin format do you use?
How the things are going with Carla?
Any additional information?
What about stack traces when the crash occurs? Is it possible to obtain them?

**Comment by sadko4u** [comment]
Reproduced the problem and fixed. The commit with fix: https://github.com/lsp-plugins/lsp-plugin-fw/commit/37c2823860ec1a2c4e1e8a3533799ef1be7a1f6d
