### ISSUE TITLE
[lsp-plug.in] feedback page is broken

### ISSUE THREAD

**Issue by RubenKelevra** [sadko4u/lsp-plugins#295]
Hey @sadko4u,

love your project and just wanted to drop a message via the feedback page on `lsp-plug.in`. Issue is: The page seems to be broken – there's no way to type/send feedback on it.

The page even lists itself as a method to send feedback and provides a link which sends users to the same page again.

Here's how the page looks like with `Firefox 109.0` under Linux:

![Screenshot 2023-01-28 at 14-37-13 Linux Studio Plugins Project](https://user-images.githubusercontent.com/614929/215269436-cc4f3e12-c5c6-4bc4-af20-f318c19c3c8b.png)

**Comment by sadko4u** [comment]
I was using GMail to send feedback by email. After Google has restricted the API access to OAuth, I wasn't able to update the code that sends notificaitons. That's why I removed the feedback page from the top menu.

**Comment by sadko4u** [comment]
Feedback page is back again. Since the site has moved to VDS, we have had a good option to install the `postfix` mail service and set up message delivery for the desired e-mail address.
