### ISSUE TITLE
Add a hint to the Linux Studio Plugins Project in the README.md

### ISSUE THREAD

**Issue by sjaehn** [sadko4u/lsp-plugins#298]
Please add a link to https://github.com/lsp-plugins were all plugins, libs and toolkits are located.

**Comment by sadko4u** [comment]
Committed changes to the `devel` branch: https://github.com/sadko4u/lsp-plugins/commit/0527547062186cd7e3535ca8094e25801ddf8474

**Comment by sadko4u** [comment]
Available in 1.2.6 release
