### ISSUE TITLE
drag&drop function in the samplers

### ISSUE THREAD

**Issue by cooltehno** [sadko4u/lsp-plugins#30]
Hello, dear Sadko! :)
Once I was asking about the sample pre-listening possibility in the samplers (through the feedback function in your site http://lsp-plug.in/?page=feedback). May be it could be not so complicated to add a drag&drop function from Adrour's import window or from any file manager (like Nautilus, Thunar etc. in Linux), instead of making a preview function in the sampler's browser? Sorry if my question is stupid -  I'm not a programmer, just an idea...
(At this time I browse my samples in the Ardour's import window, simultaneously opening the sampler's browser and find the sample there.)
Many thanks! :)

**Comment by sadko4u** [comment]
Hi!
First of all, thank you for a new ticket!
Yes, I remember your request. It's written down here:
https://github.com/sadko4u/lsp-plugins/blob/1d41a52f6b2236f38670c2d3a28ab97c419a4754/TODO.txt#L144

Making Drag&Drop is a good Idea but I'm currently very busy with the new plugin. I believe when I finish, I'll have more time to close some feature requests related to the UI.

**Comment by sadko4u** [comment]
Created **github-issue-30** branch and pushed set of commits to it.
Are you available to build from this branch and test drag&drop feature on your system?

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: c10e3f6f144f74fe06a1102b789a297030dfa289

**Comment by sadko4u** [comment]
Available in the 1.1.11 release!
