### ISSUE TITLE
Weird issue with external sidechain input with CLAP version in REAPER

### ISSUE THREAD

**Issue by elcalenx** [sadko4u/lsp-plugins#300]
I was trying out the CLAP version of the LSP Sidechain Compressor Stereo and ran into this weird issue. I've only been able to trigger it when loading presets with REAPER's built in preset functionality and with certain audio routing conditions, so I'm not 100% sure if this is a REAPER issue or a bug in the CLAP plugin, but I figured I should report it here as well, anyway. (I wrote about it on the REAPER forum as well, but as of now haven't had any replies...)

The gist of the issue is this: if I have a track with external sidechain routing set up, then add an LSP Sidechain Compressor CLAP plugin instance, and load a REAPER preset for it with the sidechain source set to "external",  initially the external detection does not function; it appears that the detection is using the regular track audio (channel 1/2). But if I tweak any of the plugin's GUI controls after that, the external detection (channel 3/4) suddenly starts working as it should!

This would only appear to happen if I'm adding the compressor plugin *after* the audio routing is already in place. If I add the sidechain input channel after the plugin is in place and the appropriate preset loaded, it would appear to work fine immediately.

Here's a link to my post on the REAPER forums, in case anything happens there (though currently it's pretty much just the same info I wrote above): https://forum.cockos.com/showthread.php?t=275797

EDIT: oh yeah, and I should also mention that I've used LV2 versions of the plugins in the past and haven't encountered similar issues with those.

**Comment by sadko4u** [comment]
It is possible to provide the minimum reproducible case for you?
I mean, all manual steps that should trigger the problem?

**Comment by elcalenx** [comment]
OK, so I'm testing this in REAPER (the current version, 6.75). I don't have other DAWs around at the moment that I could test with. The only plugin I've tested this with is the Sidechain Compressor Stereo. (Version 1.2.5, naturally.)

1. I need a project with at least two tracks producing audio, one to host the plugin, and one to act as the sidechain source. (For testing purposes the audio on the tracks should be quite different, so you can easily tell which one the compressor is reacting to.) I also need a preset (saved using REAPER's preset dialogue at the top of the window) for the plugin, with the sidechain source changed to "external". (Nothing else needs to be changed from the default values, as far as I can tell.)

2. I create a send from the sidechain source track to the track that will host the plugin. (This is a sidechain send, so it needs to go from channel 1/2 to channel 3/4.)

3. I add an instance of the CLAP version of Sidechain Compressor Stereo to the other track. I then use the preset dropdown menu at the top of the GUI window to load the preset I saved earlier. I'm not touching anything else in the plugin GUI.

4. I hit play. I can see from the meters/graph that the compressor is reacting to the audio from the track the plugin is on, not the sidechain source track.

5. I tweak some control in the plugin GUI a little. Doesn't seem to matter which one. I can immediately tell from the graph that the compressor is now responding to the audio from the sidechain source track.

**Comment by bor-T** [comment]
Can't reproduce bug in reaper with clap plugin.
[https://www.youtube.com/watch?v=IsWvlIecmBY](url)

**Comment by elcalenx** [comment]
Hmm, well, one thing you're doing different there, I think, is you appear to be saving an FX chain, not a plugin preset, which is different. I'm talking about the "save preset" option under the "+" button at the top of the window, and loading it via the dropdown menu next to it. I've only been able to reproduce this issue when loading one of those presets and not touching the plugin's controls after that.

Using the LSP plugin's own "save settings" feature does not reproduce the issue for me either.

**Comment by bor-T** [comment]
With "+" button.
[https://youtu.be/aZoONggYsoQ](https://youtu.be/aZoONggYsoQ)

**Comment by elcalenx** [comment]
I have to create the send from the kick *before* loading the preset in order to reproduce the issue. I did mention that in my earlier posts.

This is obviously a very narrow corner case. Probably the only reason I even noticed it was because I have a script that automatically sets up routing from a kick track, adds a compressor, and loads a preset. For some reason the script didn't work with the CLAP version, so I started digging into why, and discovered this sequence of events, which I found I could reproduce manually as well...

**Comment by bor-T** [comment]
Yes, now I was able to reproduce the bug. 
 But in the future, under such difficult conditions, better make a video of the process of reproducing the bug, it is much easier to understand how to reproduce it.

[https://youtu.be/D_68ZBAtlKk](https://youtu.be/D_68ZBAtlKk)

**Comment by elcalenx** [comment]
Yeah, I know, I've just never done that kind of screencapturing so it would have been a lot to figure out right now...

Anyway, good to know it's not just on my end. It feels like the inputs aren't being properly refreshed/initialised when loading the preset. But either changing the parameters or changing the routing afterwards triggers a refresh and it starts working correctly.

I have no idea if the bug is in REAPER or LSP. I first thought REAPER was more likely, since it involved the routing and preset loading there, but it seems a little weird that changing the parameters inside the plugin would fix it if that was the case...

**Comment by sadko4u** [comment]
Thanks @bor-T for the video of reproducing the problem. The video was very helpful since I'm not an experienced REAPER user. Can confirm that the problem exists.

The cause is, when loading the state of plugin by the plugin wrapper, we do not perform `update_settings` call for the plugin that will make the plugin's internal state in sync with the input parameter configuration loaded from the state BLOB. Changing at least one input parameter helped to trigger the `update_settings` call and make the internal state of wrapped plugin in sync with the parameters.

Here's the fix that will be available in 1.2.6 release:

https://github.com/lsp-plugins/lsp-plugin-fw/commit/d37930596c509eba71c2bc0b63efa68ba3551d77
