### ISSUE TITLE
Provide stable shared library names

### ISSUE THREAD

**Issue by Atemu** [sadko4u/lsp-plugins#301]
Hi, I was trying to use `lsp-plugins-ladspa` in pipewire for noise suppression. To do that, I need to specify the shared library name. However, lsp-plugins' build only provides `lsp-plugins-ladspa-1.2.4.so` which is obviously not stable would break my audio setup on every update.

I fixed it up in our packaging but it'd be better if upstream just provided stable symlinks; `lsp-plugins-ladspa.so -> lsp-plugins-ladspa-1.2.4.so` etc.

**Comment by sadko4u** [comment]
Won't these symlinks be interpreted as a duplicate plugin library?

**Comment by Atemu** [comment]
Not sure. I've never used these plugins inside a DAW; my only use-case so far has been real-time processing via pipewire.

**Comment by sadko4u** [comment]
At this moment I'm thinking that providing version number for several shared object files is not necessary anymore.
I think I'll change this in 1.2.6.

**Comment by sadko4u** [comment]
Available in 1.2.6
