### ISSUE TITLE
Brick-wall low-pass filter?

### ISSUE THREAD

**Issue by LebedevRI** [sadko4u/lsp-plugins#306]
LSP can already oversample and then downsample the stream,
e.g. in limiter, to achieve higher precision of the resulting limiting,
while still keeping the actual stream at a "low" frequency.

Some other audio processing solutions provide an ability to do that
in more plugins, see e.g. overview in https://www.youtube.com/watch?v=-jCwIsT0X8M
Supposedly (i have not verified), that allows to get rid of some induced noise.

What i'm wondering if a new plugin could be provided,
that took an input, downsampled it (would be nice to be able to specify
the target sample rate though, not the factor), and then upsampled it back
to the original rate, thus removing unwanted high frequencies.

There is a number of different sampling algorithms,
i don't know if the one used by LSP is best suited for this

Is that something that might be worthwhile?

**Comment by sadko4u** [comment]
Hello! And what's the problem just to apply the low-pass filter with steep filter curve like Butterworth x4 filter in LSP with some Q adjusted or even LRX x4 filter?

The downsampling procedure already means that we need to filter-out high frequencies above the half of the sample rate first, then perform the downsampling. Otherwise we will get the same aliasing effect as described in the video you've provided.

**Comment by LebedevRI** [comment]
> Hello! And what's the problem just to apply the low-pass filter with steep filter curve like Butterworth x4 filter in LSP with some Q adjusted or even LRX x4 filter?

That is the obvious solution, yes. I have two considerations:
1. it's a bit not obvious how many `LRX x4 filters` are needed to fully eliminate those high frequencies,
2. and i'm wondering how doing so compares to using an actual downsample+upsample steps,
    e.g. using Xiph.org Speex / PipeWire's Spa.

**Comment by sadko4u** [comment]
1. You need to understand first that each pole of the IIR (recursive) filter gives -6 dB/octave attenuation. The more poles you have, the more steep attenuation curve you get.
2. The x4 BWC filter of LSP Para Equalizer consists of 8 poles which give you -48 dB/octave attenuation.
3. The x4 LRX filter of LSP Para Equalizer is similar to two x4 BWC filters which means 16 poles and -96 dB/octave attenuation.
4. Adjusting q can give additional steepness to the curve but making it too high gives extra non-linearity of the magnitude in the passed spectrum.
5. LSP Para Equalizer is limited to maximum x4 steep filters. But the core DSP library allows to build much more steep recursive filters.

I don't know how Xiph.org Speex / PipeWire's Spa is implemented and can not give any recommendations and comments about it.

**Comment by LebedevRI** [comment]
Right. I have previously observed that behavior by applying the Oscillator plugin. 
Effectively, if in lieu of an actual standalone module, i guess i'm asking for having some rule-of-thumb
in the documentation that would mention, how much of an attenuation is enough in that case?
E.g., how much does the limiter itself apply when downsampling?

> 5\. LSP Para Equalizer is limited to maximum x4 steep filters. But the core DSP library allows to build much more steep recursive filters.

Plus, one could just have all 16/32 filters of Parametric Equalizer be the same filter.

**Comment by sadko4u** [comment]
Ideally, you need an -inf db/octave attenuation to have an ideal filter. But that's not possible.

If we consider 48 kHz sample rate, then we can compute the desired steepness of the filter.
We have the 24 kHz Nyquist frequency and around 20 kHz of audible range.
Dividing 24 by 20 gives 1.2 octave of the filter transition zone.

If we have 16-bit quality audio, then we have the dynamic range of `20 * log10(2 ^ 16)`, or 96 dB. For the 24-bit audio the dynamic range will be around 144 dB.

So actually for 16-bit audio we need an attenuation of `96 / 1.2 = 80` dB/octave filter attenuation which gives `80/6 = 14' poles.

LSP oversampling/downsampling module uses 30-pole butterworth filter with `q=0.5` which doesn't give serious magnitude vibrations in the audible range.

**Comment by LebedevRI** [comment]
Thank you, that is what i wanted to hear i believe!
It would be really nice to put this somewhere in the docs.

**Comment by sadko4u** [comment]
@atskler 

Here's the update:

https://github.com/lsp-plugins/lsp-plugins-para-equalizer/commit/a1df62a29cc11abb4baa7a9d72c4b7fa9bc76e9c

**Comment by LebedevRI** [comment]
@sadko4u thank you!

**Comment by atskler** [comment]
@sadko4u thank you!

**Comment by sadko4u** [comment]
Te new **Filter** plugin was introduced. It allows to use extra high-slope brickwall lowpass filters.

**Comment by LebedevRI** [comment]
Wow, that is unexpected, thank you!
