### ISSUE TITLE
The 3d window is blank in roombuilder.

### ISSUE THREAD

**Issue by justdnld** [sadko4u/lsp-plugins#310]
Is this just a dependency issue?  Installed on Ubuntu 22.04 via KXstudio repo, also tried binary from Sourceforge.  I'm running nvidia and 3D works for games, KDE effects, etc.  What's missing?
![Screenshot_20230226_133600](https://user-images.githubusercontent.com/30353358/224518351-6196079e-adf1-4418-9a70-0f593a49cdd9.png)

**Comment by sadko4u** [comment]
Please check if you have `lsp-r3d-lib` binary installed. If not, then that's the issue.

**Comment by sadko4u** [comment]
LSP Plugins have their own mechanism for loading for 3D rendring backends. At this moment, only GLX is supported which is provided as a separate small library.

**Comment by justdnld** [comment]
Thanks.  That was missing, but didn't seem to have resolved the issue...

**Comment by sadko4u** [comment]
The second case can be that the version of 3D backend is mismatched. The UI engine is discarding the bakend which reports the invalid version.

**Comment by justdnld** [comment]
Yep.  Built lsp-r3d-glx-lib-1.0.7 to match LSP 1.2.4 and it works.  Thanks much.
