### ISSUE TITLE
A few little UI feature requests for parametric EQs and spectrum analyzers

### ISSUE THREAD

**Issue by elcalenx** [sadko4u/lsp-plugins#313]
Hi! I actually wrote these ideas in a thread over at linuxmusicians.com recently, but I figured it might be worthwhile making a more formal feature request post. Since 1.2.6 came out and had some nice improvements for the parametric EQs and spectrum analyzer, I thought of a few more little UX improvements that could be useful.

1. I would love an option to reverse the behaviour of the mousewheel over the dots in the parametric EQ graph. A lot of EQs use this to adjust Q the same way LSP does, but the problem is there isn't consistency in *which way* the Q changes. Other EQs I use (including, for example, REAPER's ReaEQ) work the opposite way, which can be pretty annoying when you're switching between different EQs and your muscle memory is used to a particular motion.
2. An easy way to switch the channel of an existing filter in the mid/side or left/right versions of the parametric EQ could be occasionally useful.
3. In the spectrum analyzer, it could sometimes be useful to have an adjustable horizontal guideline in addition to the vertical frequency slider, for better comparing the level of peaks in different parts of the frequency range. (Probably wouldn't need to be displayed permanently, but it could maybe appear when holding down the mouse button, or there could be a toggle to make it always visible...)

**Comment by elcalenx** [comment]
2. I feel like the most logical way would probably be to just use a new previously unused filter, right? Don't want to accidentally remove other filters you're using. Of course I have no idea what the easiest way to implement it would be, though. As for UI, I imagine it would make most sense to have the switch option in the pop-up menu for the EQ dots, I imagine?
3. I haven't thought too deeply about this, tbh. I wouldn't say it's a very high priority for me, just a thought I had. But I guess the most intuitive would be if it worked pretty much the same as the current frequency slider. Dragging/clicking in the graph would set both lines simultaneously. Kinda like in the parametric EQ the dots have both vertical and horizontal guide lines, right? I think it should definitely be optional, though, and probably not displayed by default.

**Comment by sadko4u** [comment]
Available in 1.2.7
