### ISSUE TITLE
lsp-plugins 1.2.6 broke the "Solo" button and the "Inline-display" in Carla

### ISSUE THREAD

**Issue by SnipeXandrej** [sadko4u/lsp-plugins#314]
Hi, today I updated my Arch system and noticed that the Inline Displays in Carla, and the Solo button in the Parametric Equalizer (also in Carla) stopped working after the upgrade of lsp-plugins- to version 1.2.6

Downgrading `liblsp-r3d-glx-lib` `lsp-plugins-lv2` and `lsp-plugins-standalone` down to 1.2.5 fixes these issues.

Distro: Arch Linux
DE: KDE Plasma Wayland
PipeWire 0.3.67-1

**Comment by sadko4u** [comment]
Hello! Thank you for your report. If it is so, it will be fixed in 1.2.7.

**Comment by sadko4u** [comment]
The fix for the inline display is here:
https://github.com/lsp-plugins/lsp-plugin-fw/commit/8e0bc50f2ec86393b94ffd89a8e53b8d89035040

**Comment by sadko4u** [comment]
Fixed in 1.2.7
