### ISSUE TITLE
CLAP plugin versioning changed at 1.2.6

### ISSUE THREAD

**Issue by Vascom** [sadko4u/lsp-plugins#316]
At 1.2.5 clap plugin lib was versioned. After build and install i Have file `/usr/lib64/clap/lsp-plugins-clap-1.2.5.clap`.
But at 1.2.6 this lib unversioned `/usr/lib64/clap/lsp-plugins-clap.clap`
Is it bug?

**Comment by sadko4u** [comment]
Hello!
No, it's feature: https://github.com/sadko4u/lsp-plugins/issues/301

**Comment by sadko4u** [comment]
@Vascom do you have any additional questions?

**Comment by Vascom** [comment]
No.
Thanks for clarification.
