### ISSUE TITLE
No CLAP UI  in Bitwig

### ISSUE THREAD

**Issue by porzione** [sadko4u/lsp-plugins#319]
Arch Linux, Pipewire 0.3.70, LSP 1.2.6. The CLAP version of the plugins in Bitwig Studio 4.4.10 has no UI - no crashes, no messages in the terminal. In fact, plugins can work with a generic UI. Same issue with plugins downloaded from Sourceforge. VST versions are fine. Reaper doesn't have this problem.

**Comment by sadko4u** [comment]
Fixed in 1.2.7
