### ISSUE TITLE
[Question] How should I install liblsp-r3d-glx-lib and its variants?

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#320]
Hi @sadko4u  It's been a while since I updated your plugins, being specific I stayed at [1.2.4](https://github.com/sadko4u/lsp-plugins/releases/tag/1.2.4) Today I decided to update to [1.2.7](https://github.com/sadko4u/lsp-plugins/releases/tag/1.2.7) however I came across new files: `liblsp-r3d-glx-lib.a` `liblsp-r3d-glx-lib.so` `liblsp-r3d-glx-lib-1.0.11.a` `liblsp-r3d-glx-lib-1.0.11.so` and a folder: **pkgconfig** which contains `lsp-r3d-glx-lib.pc`

My question is how should I install these files? That is, before it was enough to just move the **lsp-plugins** folder to `.vst` or `.lv2` (in my home directory) now I know that these files are used for something... but I don't know where put them :')

By the way, thank you for your contributions to audio on Linux, you hold a special place in our hearts <3

**Comment by sadko4u** [comment]
These files provide 3D rendering backend for drawing 3D stuff in the UI. It is currently used only by the Room Builder plugin series:
![Room Builder UI](https://github.com/sadko4u/lsp-plugins/assets/12834464/a2358e0e-8c5e-4928-a7ba-7508523a2662)

You can take the `liblsp-r3d-glx-lib-1.0.11.so` and just place it near to the plugins' `*.so` file, the UI engine should find it. All other files are not used at runtime. They are just the parts of providing the library according to usual rules.

**Comment by p-chan5** [comment]
Now I understand! Thank you so much for your explanation. I guess I can close it now.
