### ISSUE TITLE
LSP crashes Qtractor

### ISSUE THREAD

**Issue by oldcastlehq** [sadko4u/lsp-plugins#322]
Hei,

I opened an issue [here](https://github.com/rncbc/qtractor/issues/396) since some LSP plugins crash Qtractor. Maybe it's worth to take a look at it :-)

**Comment by sadko4u** [comment]
Hello! Which plugins do crash QTractor? LSP Mixer plugin series?
As said [here](https://github.com/rncbc/qtractor/issues/396#issuecomment-1579180069), it seems that Qtractor has very poor routing features to properly deal with plugins that do not match the number of audio inputs/outputs to the Qtractors's track or bus.

**Comment by sadko4u** [comment]
At this moment, the only problem is that Multisampler does not report the main input and output. I need to closely look at this. And also look a stack trace of crashing Qtractor.

**Comment by sadko4u** [comment]
Fixed missing main input and output groups. Will be available in 1.2.8.

**Comment by sadko4u** [comment]
Fixed in 1.2.8.
