### ISSUE TITLE
Multi Sampler Direct Out Mapping in Ardour

### ISSUE THREAD

**Issue by thoth-amon** [sadko4u/lsp-plugins#324]
LSP Plugins: 1.2.6
Ardour: 7.5
Using LV2 version

When Clicking to "fan out" the outputs into tracks in  all the samplers outputs are routed to left channels in the DAW track inputs.  (Pic attached). Also, the main sampler channel (with the plugin on it)  is routed directly to the Master bus when it shouldn't be.

![Screenshot_20230626_131029](https://github.com/sadko4u/lsp-plugins/assets/78971907/490dc693-3e13-4015-941a-da5b17b08251)

**Comment by sadko4u** [comment]
Hello!
LSP Plugins do not perform their routings. The DAW is responsible for routing.

From the LV2 TTL file we get:
```
[
                a lv2:OutputPort, lv2:AudioPort ;
                lv2:index 46 ;
                lv2:symbol "dol_3" ;
                lv2:name "Direct output left 3" ;
                pg:group plug_pg:direct_out_3 ;
                lv2:designation pg:left ;
        ] , [
                a lv2:OutputPort, lv2:AudioPort ;
                lv2:index 47 ;
                lv2:symbol "dor_3" ;
                lv2:name "Direct output right 3" ;
                pg:group plug_pg:direct_out_3 ;
                lv2:designation pg:right ;
        ]
```

That means, that pairs direct outputs are grouped together into single groups and each output has it's own designation to left and right.
So I think we need to ask @x42 about such strange behaviour.

**Comment by sadko4u** [comment]
The description of the port group is the follwing:

```
@prefix plug_pg:    <http://lsp-plug.in/plugins/lv2/multisampler_x12_do/port_groups#>

plug_pg:direct_out_3
        a pg:StereoGroup, pg:OutputGroup ;
        lv2:symbol "direct_out_3" ;
        rdfs:label "Direct Output 3"
        .
```

**Comment by sadko4u** [comment]
There is a question to @drobilla. Should the `pg:StereoGroup` explicitly define elements or should they be predefined by `lilv`?

**Comment by x42** [comment]
I have encountered a similar issue, when using classes, order matters in case multiple classes are references. and in some cases inheritance just does not work.

In case it helps, relevant Ardour source is

https://github.com/Ardour/ardour/blob/e54e24a7a074e0c6800dbc7b3b6e79bf20471b8a/libs/ardour/lv2_plugin.cc#L2475-L2482

and a workaround is to explicitly specify the channel layout like

https://github.com/x42/avldrums.lv2/blob/7a9168b15d7698830ff5ebd93f7abae49c22ad3b/lv2ttl/avldrums.head.ttl.in#L28-L38

**Comment by sadko4u** [comment]
Adding explicit port groups' elements definition in LV2 TTL generator helped.
The workaround will be available in 1.2.8.

https://github.com/lsp-plugins/lsp-plugin-fw/commit/ce2e7ae2d65be2dea4ad68dbc35722860636bac9

**Comment by sadko4u** [comment]
Workaround available in 1.2.8!

**Comment by drobilla** [comment]
> There is a question to @drobilla. Should I expplicitly define elements in the `pg:StereoGroup` or should they be predefined by `lilv`? According to what I found in [documentation](https://lv2plug.in/ns/ext/port-groups#StereoGroup), it seems that they should be predefined.

Apologies for the late reply, although I don't quite understand the question.  Existing roles defined in the standard (left, right, etc) should be used where possible, but it's also fine to define your own (with the caveat that hosts aren't going to understand it well or at all).  From the commit, it seems like you added explicit designations for the ports in groups, and yes, this is how it should be.  Most hosts (as far as I know) make use of the explicit roles in groups and don't bother with trying to figure things out if they have a supposedly stereo group that just has some ports in it without roles (and I think this is a good thing, explicit is better).  Maybe lv2lint or some other validator thing should have a check for this?

**Comment by x42** [comment]
> Existing roles defined in the standard (left, right, etc) should be used where possible

While semantically correct, the problem is that `lilv_world_find_nodes` does not expand pg:elements when iterating over the default `pg:StereoGroup`.

It does however work when the plugin explicitly defines the elements.

**Comment by drobilla** [comment]
> > Existing roles defined in the standard (left, right, etc) should be used where possible
> 
> While semantically correct, the problem is that `lilv_world_find_nodes` does not expand pg:elements when iterating over the default `pg:StereoGroup`.
> 
> It does however work when the plugin explicitly defines the elements.

Can you elaborate on this a bit?  I'm not sure exactly what you mean, "expand" how?

**Comment by sadko4u** [comment]
@drobilla 
From the documentation we see the `pg:StereoGroup` here: https://lv2plug.in/ns/ext/port-groups#StereoGroup
There are `element` options defined at the right:
![изображение](https://github.com/sadko4u/lsp-plugins/assets/12834464/bcd9e5bd-8b6b-44c5-a2d1-5736180a11e0)

The host does not see these options when it finds the `pg:StereoGroup`. We need to explicitly define both elements until it will be reachable by the host.

**Comment by drobilla** [comment]
From IRC:

    <x42> drobilla: for some reason `LILV_FOREACH (nodes, i, designations) { .. }` in libs/ardour/lv2_plugin.cc:2477 does not find any elements when the plugin uses pg:StereoGroup
    <x42> drobilla: but when the plugin defines the exact same group using a custom URI in its ttl, it works
    
All this stuff should be loaded into one massive model, so it shouldn't make any difference where the data is at all.  Possibly this spec data isn't being loaded in Ardour for some reason, or... something else is going on.  I'll try to figure it out.

It's fine to specify groups like this in the plugin data, but you shouldn't have to, so when this gets figured out and/or fixed it should be safe to remove it at whatever point in the future that's appropriate without breaking anything.

**Comment by x42** [comment]
I just tested this again, and it Ardour works here just using `pg:StereoGroup`.  However the downside is that when fanning out, the bus is named "Stereo".

What does **not** work is to derive a new class from the StereoGroup, only overriding the label.
So the problem is that the parent's "elements" are not inherited, and the workaround is to explicitly specify them.

**Comment by drobilla** [comment]
Oh, yeah, that makes sense.  There is no magic general implementation of inheritance (quite a few of the rules in the spec that force things to be explicit where they aren't logically necessary are for this reason, to keep things simple for host implementations), so in this case something somewhere would actually need to implement that (if property isn't on thing but it is on parent, get it from there, and so on).

This seems like a case that should work somehow although I don't know off the top of my head what the best place/way to implement it would be...
