### ISSUE TITLE
[Feature Request] Implement the new types and slopes of the filter plugins in the of equalizer series.

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#329]
Hi Vlad! Thanks for the new filter plugins, I've used them a lot these days; especially the Bandpass, Ladder-pass and Ladder-rej types, in addition to the new slopes (x6 - x16).

Is it possible that you can implement these options in the equalizer series? Seriously, they are quite useful :D

Thank you for everything, I appreciate your work, you are very important to Linux audio world <3

**Comment by sadko4u** [comment]
Hello!

They are not implemented in the Parametric Equalizer due to several reasons:
- They are pretty heavy when we talk about computation resources. If you turn on such many filters in the Equalizer, you probably will get many xruns.
- They are too specific. I wonder if anyone could use such extreme filters just for tone correction.
- We have several non-comfortable cases with the UI: need to implement one additional knob which will be useful only for restricted class of filters.

**Comment by p-chan5** [comment]
Hi again. Thank you very much for your answer.

> They are too specific. I wonder if anyone could use such extreme filters just for tone correction.

In the case of Ladder filters, they could be used to replace two filter classes: Lo-shelf and Hi-shelf, i.e. I need two Hi-shelf filters to emulate a Ladder-pass filter.

![001](https://github.com/sadko4u/lsp-plugins/assets/123143444/302ca379-a80b-4ba0-a1d7-85a1830f7e33)

As for the Bandpass filter, I think it could be emulated with Hi-Pass and Lo-pass filters at 36 dB/oct.

![002](https://github.com/sadko4u/lsp-plugins/assets/123143444/6eda589c-8d33-4b2a-8ffb-439d392c6b81)

Implementing them would avoid this construction process and in turn it would be much easier to move them within the frequency spectrum.

> They are pretty heavy when we talk about computation resources. If you turn on such many filters in the Equalizer, you probably will get many xruns.

Are they that heavy!? Hmm... maybe use a max of 6 for super specific cuts. What do you think?

> We have several non-comfortable cases with the UI: need to implement one additional knob which will be useful only for restricted class of filters.

Maybe you can put it in that empty space, next to Q (Filter width). Yeah, it's a bit awkward... But I think it's the same as with high/low pass filters (you can't adjust the gain control).

![003](https://github.com/sadko4u/lsp-plugins/assets/123143444/5fc59de5-663d-4e26-85a0-10434cb60379)

**Comment by sadko4u** [comment]
> Are they that heavy!? Hmm... maybe use a max of 6 for super specific cuts. What do you think?

With x16 slope - yes.
I don't think it is a good reason to allow x16 slope in the Equalizer.

**Comment by p-chan5** [comment]
I understand. Well I guess that would be fine. Yes, the x16 cut is much tighter than the x4 cut but you could discard it if it consumes a lot of resources.

![001](https://github.com/sadko4u/lsp-plugins/assets/123143444/64f86eb4-c0b6-4253-9f0a-5086f89ff06c)

**Comment by sadko4u** [comment]
Bandpass, Ladder-pass, Ladder-rej will be available in 1.2.9.

**Comment by p-chan5** [comment]
Super! Thank you very much for your time <3

**Comment by sadko4u** [comment]
Available in 1.2.10.
