### ISSUE TITLE
[Feature Request] Implement BWC (BT/MT) and LRX (MT) modes on the Multiband Dynamic Processor series.

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#330]
Hi Vlad! It would be great to be able to set the mode of the multiband filters, i.e. they all act in LRX (BT) mode by default (when in Modern).

This would help to reduce a wider range of frequencies when in (MT) and give a smoother result when in BWC.

I did a quick example on the equalizer. Red = LRX (BT) Blue = LRX (MT)

![0003](https://github.com/sadko4u/lsp-plugins/assets/123143444/73e85652-d48b-4c66-ab36-634b1fbeb206)

This would apply to all filters; something like a general option next to SC boost.

![002](https://github.com/sadko4u/lsp-plugins/assets/123143444/2983e97a-fe78-4673-9a75-597648340460)

**Comment by sadko4u** [comment]
Matched Z transform has it's drawbacks: some part of spectrum is reflected back from Nyquist frequency.

You can observe it by applying some lowpass near to the nyquist frequency on some noise at the input and watch the actual output spectrum.

Second, Matched Z transform is much computation heavier when we're talking about dynamic filters (which are used in `Modern` mode).
So, this is not a good idea and won't be implemented.

**Comment by p-chan5** [comment]
Is right. I applied an LRX (MT) Lo-pass filter near 20 kHz and I could notice some unusual distortion. Sorry I thought it was possible. Thanks anyway <3
