### ISSUE TITLE
[Bug] Parametric Equalizer x16/x32 LeftRight mutes both channels in Inspect mode.

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#331]
**LSP version:** 1.2.8

**Package:** vst2 - Linux-x86_64 - running on Carla 2.1.0

**How to reproduce it:**

1. Load a new instance of the plugin.
2. Turn on at least one band for both channels.
3. Turn on Inspect mode on one of them, then turn it off. You will notice how the other channel is muted.
4. Turn on Inspect mode on the muted channel. You will notice that the audio is gone.

![0004](https://github.com/sadko4u/lsp-plugins/assets/123143444/c39cc5a5-e2c1-4e30-8c55-fe11dc6822b3)

**Comment by sadko4u** [comment]
This is normal for LeftRight version of plugin. The `inspect` mode works only for the filter you want to inspect at this moment.

**Comment by sadko4u** [comment]
Oh, I've missed to see that disabling inspect mode does not turn on the second channel...

**Comment by sadko4u** [comment]
Fixed here:

https://github.com/lsp-plugins/lsp-plugins-para-equalizer/commit/66d836cd82f2c4733adfefac23e96e4772506da6

**Comment by p-chan5** [comment]
Thanks for checking it out! <3

**Comment by sadko4u** [comment]
Fixed in 1.2.10
