### ISSUE TITLE
[Bug] Width (oct) of Bandpass, Ladder-pass and Ladder-rej filters is not persistent in MT mode.

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#335]
Hi Vlad! I was trying out the new filter types in Matched Z Tranfrom mode and noticed that the width (oct) gets smaller as you get closer to 24kHz. Could you take a look at it? Thank you from the heart ❤️

![0002](https://github.com/sadko4u/lsp-plugins/assets/123143444/618b4503-90ee-4be4-9c5d-123bae81585d)

**Comment by sadko4u** [comment]
We can not operate on a frequency greater than the nyquist frequency without additional techniques like oversampling. That's why the high frequency of bandpass/ladderpass/ladderrej filter is limited to the value of the nyquist frequency.

**Comment by p-chan5** [comment]
Thanks for the quick answer, just out of curiosity, from what frequency does it start to operate in nyquist mode?

**Comment by sadko4u** [comment]
https://en.wikipedia.org/wiki/Nyquist_frequency

**Comment by p-chan5** [comment]
Thank you. Sorry for the confusion <3
