### ISSUE TITLE
[Feature Request] Add Phase Invert buttons in Delay plugins

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#337]
Hi Vlad! This would help to solve phase problems and improve mono compatibility. I saw this in the video: [Identify and Fix Phase Issues in the Mix](https://www.youtube.com/watch?v=kJ6Jgn4T8Zw).

It would also be nice to have a Correlation Meter in the Spectrum Analyzer or Oscilloscope plugins; but I think this can wait a bit longer.

What do you think?

**Comment by sadko4u** [comment]
I think that different features for different plugins should not be mixed into a single feature request.

Now about the phase invert for Delay plugins.
If you mean the [Delay compensator](https://github.com/lsp-plugins/lsp-plugins-comp-delay) plugin, then this is a good idea.

**Comment by p-chan5** [comment]
Great! Sorry to mix up both requests, I was watching the video while he was making the request :P It won't happen again.

Thanks for keeping it in mind :D

**Comment by sadko4u** [comment]
Moved part of requirements into another issue - https://github.com/sadko4u/lsp-plugins/issues/338

**Comment by sadko4u** [comment]
Added in 1.2.10.
