### ISSUE TITLE
[Feature Request] Synchronize the band filter curves with the compressor mode.

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#340]
Hi Vlad! Is it possible to update the filter guides with their respective mode? Since they are always shown in Classic mode despite being in Modern or Linear Phase.

![001](https://github.com/sadko4u/lsp-plugins/assets/123143444/bf546101-3b07-4184-ba90-cae8c9a48ad7) ![002](https://github.com/sadko4u/lsp-plugins/assets/123143444/1bca27cf-9c26-4e62-bab5-87406c35d8b7) ![003](https://github.com/sadko4u/lsp-plugins/assets/123143444/401b7196-c5ea-4690-b0ca-6b58b4557b56)

**Comment by sadko4u** [comment]
The problem here is misunderstanding of band curves and overall compression curve.
Band curves show how the sidechain filters work while compression curve shows the amplification magnitude among the whole spectrum range. They should not be mixed together.

**Comment by p-chan5** [comment]
@sadko4u Do you think you can show the band curves instead of the overall compression curve?

That feature would be very useful as it would allow me to see the curvature of each filter, similar to the Crossover plugins but in multiband dynamics plugins like the compressor, gate, expander...

https://github.com/sadko4u/lsp-plugins/assets/123143444/b70e7bba-a1c5-414b-aa58-92f7be50a3e5
