### ISSUE TITLE
Spectrum Analyser Selector Discrepency

### ISSUE THREAD

**Issue by thoth-amon** [sadko4u/lsp-plugins#342]
Version: 1.2.10
Tested with LV2 plugins.

The number by the selector knob doesn't match the one on the graph and in the FFT Frequency Field.

![Screenshot_20230908_173042](https://github.com/sadko4u/lsp-plugins/assets/78971907/c4b6574e-ffb9-4e89-b33c-aff8ea174e90)

**Comment by sadko4u** [comment]
This is not a bug.
The `Selector` shows the desired frequency but FFT is discrete in frequency. The indicator shows the actual frequency of the discrete FFT transform.
