### ISSUE TITLE
[Feature Request] Add frequency and note displaying (with detune in cents) in Multiband Plugins.

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#343]
Hi @sadko4u, I love this feature and use it a lot in Parametric Equalizer plugins but I wish it were also present in these dynamics plugins. Because it is quite useful when I try to tune at [440 Hz](https://pages.mtu.edu/~suits/notefreqs.html).

What do you think?

![0001](https://github.com/sadko4u/lsp-plugins/assets/123143444/f086c6d6-cfe2-4384-bb50-14664ed92741)

**Comment by p-chan5** [comment]
I would like it to be like the frequency split points. In this way I could adjust the frequency of each band according to the note scale. Something like:

Band 1
138.59 Hz
C#3 + 00

Band 2
4434.92 Hz
C#8 + 00

**Comment by sadko4u** [comment]
The feature will be available in 1.2.14 release.

**Comment by sadko4u** [comment]
Available in 1.2.14!
