### ISSUE TITLE
Spectrum Analyzer CLAP appears to not work correctly in Bitwig Studio

### ISSUE THREAD

**Issue by elcalenx** [sadko4u/lsp-plugins#344]
Just for fun, I was checking out the demo version of Bitwig Studio, and one thing I discovered almost immediately was that the LSP Spectrum Analyzer didn't appear to work. Not only was there no graph showing up in the GUI, but there was also no audio coming out of the plugin. When I continued playing around with it, sometimes there would be weird noise coming out of one channel, even when playback was paused. Not sure what triggered that...

Most other LSP plugins I tried seemed to work fine, but the same issue seems to apply also to the Oscilloscope plugin. This is another plugin that has different variants for different channel counts, so I'm guessing that must be relevant; the issue would seem to be related to audio routing.

The issue seems to only affect the CLAP versions. VSTs would appear to work. (And Bitwig doesn't support LV2.)

Other DAWs I use (like REAPER) don't seem to have any routing issues with these plugins.

Using current versions of LSP (1.2.11) and Bitwig (5.0.7), on Ubuntu 23.04.

**Comment by sadko4u** [comment]
What version of Spectrum Analyzer you're trying to use? I mean, the maximum number of simultaneously analyzed channels.

**Comment by elcalenx** [comment]
Mostly I was testing with the 2 channel version (since that's the one I would actually use for stereo audio), but I briefly tried the other variants too and it looked like they all suffered from similar issues.

One weird thing I just noticed is that the CLAP versions of these plugins show an external sidechain input in Bitwig's UI. The VST versions and CLAP versions of other LSP plugins (except the actual sidechain plugins) don't. It's also showing multiple outputs for the 2 channel version, which doesn't quite make sense, since it should just be one stereo output, I think...

**Comment by sadko4u** [comment]
Added port group specifications for the affected plugins. Hope that helps.
@elcalenx are you available to build plugins from the `devel` branch and check that the problem has gone?

**Comment by elcalenx** [comment]
Sorry, I'm not really set up to build stuff right now, it would be a little too much work... Also I recently had to reinstall my OS, and I don't even have Bitwig installed at the moment. I only had the demo version, and I don't think I'll end up buying it any time soon, so this isn't really a high priority for me.

**Comment by sadko4u** [comment]
Just tested on my rare 4.4.10 installation.
Seems to be working well.

**Comment by sadko4u** [comment]
Fixed in 1.2.12.
