### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by OliverEvans96** [sadko4u/lsp-plugins#345]
Hello,

Thank you for the amazing free plugins! I was curious to take a peek at the source code, but it seems that this repo only contains Makefiles. Presumably there's some C++ code somewhere. Is it still available online?

Thanks,
Oliver

**Comment by sadko4u** [comment]
Hello!

Please read more carefully the BUILDING section of README.md file.

All dependencies are automatically fetched by the 'make fetch' command when you prepare for building.

All source code that is downloaded by 'make fetch' is available on this page:
https://github.com/lsp-plugins/

**Comment by OliverEvans96** [comment]
Thank you!
