### ISSUE TITLE
Cross-compilation for ARM (FlatPak)

### ISSUE THREAD

**Issue by sadko4u** [sadko4u/lsp-plugins#35]
The original builds of package for FlatPak are broken.
Need to look how to solve the problem.
Related issue: https://github.com/wwmm/pulseeffects/issues/464

**Comment by sadko4u** [comment]
The first-look log is the following:
```
{standard input}: Assembler messages:
{standard input}:15039: Error: garbage following instruction -- `orr r5,r5,LSL $1'
{standard input}:15207: Error: garbage following instruction -- `orr r8,r8,LSL $1'
{standard input}:15522: Error: garbage following instruction -- `orr r5,r5,LSL $1'
{standard input}:15688: Error: garbage following instruction -- `orr lr,lr,LSL $1'
  g++ decode.cpp
  g++ phase_detector.cpp
  g++ widgets/LSPButton.cpp
  g++ CtlSwitch.cpp
  g++ CtlValuePort.cpp
{standard input}:19681: Error: garbage following instruction -- `subs r5,r3,LSL $1'
{standard input}:20600: Error: garbage following instruction -- `subs r6,r3,LSL $1'
  g++ graph_equalizer.cpp
make[2]: *** [Makefile:77: /run/build/lsp-plugins/.build/src/dsp/neon-d32.o] Error 1
make[1]: *** [Makefile:57: dsp] Error 2
```

Need to obtain compilation command by issuing:
```
make SHELL='bash -x'
```

**Comment by AsavarTzeth** [comment]
Okay here is my first local build, using qemu-user-static and no patches:
- https://gist.github.com/AsavarTzeth/bde134e543ba23c2f06d7f94616e6384

Just in case the Flathub build environment differed in any meaningful way, I made a test build there too:
- https://gist.github.com/AsavarTzeth/debb0be42a397e99154f503fd71ba871

Make arguments used:
- PREFIX=/app
- SHELL=/usr/bin/bash -x

**Comment by sadko4u** [comment]
Could you please build all in non-multithreaded mode with -j1 switch?
Currently output is a total mess, I can not find out the problem file that caused an error.

**Comment by AsavarTzeth** [comment]
Right, that makes a lot more sense.

- https://gist.github.com/AsavarTzeth/80222d00cae94178b7a899ecf51b58ae

**Comment by sadko4u** [comment]
It seems that your compiler tries to build ARM binaries using THUMB instruction set by default.
Created **github-issue-35** branch.
Let's try to disable them by this patch: 0598416b7603d9a973abe13ebf355ded86dab368

**Comment by AsavarTzeth** [comment]
So far so good. Slowly rebuilding and no problem at `Thread.cpp` this time.

**Comment by sadko4u** [comment]
Also I wan to ask you to try to build AArch64 binaries for Flatpak since it is also possible in **github-issue-35** branch.

**Comment by AsavarTzeth** [comment]
Sure thing. First thing on tomorrows agenda.

**Comment by AsavarTzeth** [comment]
Almost, forgot. Both arm (armv7a) and aarch64 builds now pass without any issues when built from the `github-issue-35` branch. Much appreciated!

So I guess the only remaining question is, when can I expect a 1.1.8 release? I guess I could use the `github-issue-35` branch in the meantime, assuming you don't remove it before 1.1.8.

**Comment by sadko4u** [comment]
Nice to see that all is OK now.
Merged changes into **devel** branch: f01e98b9a1263d6cf44cbea8c8c3d6d3fb3eb607
I'm planning to do a 1.1.9 release at the end of this week (odd number of release means bugfix release), so actually we are forced to skip 1.1.8, same as skipped 1.1.6.
You can currently use **devel** branch for building. I'll remove the **github-issue-35** branch now.

**Comment by AsavarTzeth** [comment]
I tried building f01e98b9a1263d6cf44cbea8c8c3d6d3fb3eb607 recently it somehow seems to have regressed with the merge to **devel**. It built successfully for aarch64 (and x86 architectures), but arm broke:

- https://flathub.org/builds/#/builders/14/builds/118

I also tried the (then) latest commit 666599e8ca1c5867f24083812742b96e3c07b44e but that failed to build for all architectures:

- https://flathub.org/builds/#/builders/32/builds/1619

**Comment by AsavarTzeth** [comment]
Currently testing ac0cc5a98e87892d9507864c25b79b774c7e1077 at:
https://flathub.org/builds/#/builders/32/builds/1620

Seems there is a `ld: unrecognized option '-Wl,-z,relro,-z,now'` error that affects that fails all builds.

**Comment by sadko4u** [comment]
The prevoiusly build was OK?

**Comment by sadko4u** [comment]
Build scripts have been altered to reach better compatibility with KXStudio build system.
I believe some errors related to FlatPak were added.
This commit should fix the problem: 6bb93d7e2e15fc113e868b0efa1a3c61043c1e69

**Comment by sadko4u** [comment]
Please confirm.

**Comment by AsavarTzeth** [comment]
Clarify "previously"? The only thing I can say for sure at this point is that local builds from the tip of **github-issue-35** worked consistently.

I will try 6bb93d7e2e15fc113e868b0efa1a3c61043c1e69 right away, locally and pushing it to the CI.

**Comment by sadko4u** [comment]
Seems to be OK at least on one architecture:
```
flatpak-builder: Post-Install lsp-plugins: Running: flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/lsp-plugins --nofilesystem=host --filesystem=/srv/buildbot/worker/build-i386-3/build/.flatpak-builder/build/lsp-plugins-1 --bind-mount=/run/build/lsp-plugins=/srv/buildbot/worker/build-i386-3/build/.flatpak-builder/build/lsp-plugins-1 --build-dir=/run/build/lsp-plugins --bind-mount=/run/ccache=/srv/buildbot/worker/build-i386-3/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1553292846 '--env=CFLAGS=-march=i686 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' '--env=CXXFLAGS=-march=i686 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-i386-3/build/.flatpak-builder/rofiles/rofiles-gZawcl /bin/sh -c 'install -Dm644 -t /app/share/licenses/lsp-plugins LICENSE.txt'
compressing debuginfo in: /srv/buildbot/worker/build-i386-3/build/.flatpak-builder/rofiles/rofiles-gZawcl/files/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so
FB: Running: eu-elfcompress -t zlib-gnu -v /srv/buildbot/worker/build-i386-3/build/.flatpak-builder/rofiles/rofiles-gZawcl/files/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so
processing: /srv/buildbot/worker/build-i386-3/build/.flatpak-builder/rofiles/rofiles-gZawcl/files/lib/lv2/lsp-plugins.lv2/lsp-plugins-lv2.so
```

**Comment by sadko4u** [comment]
ARM build is broken again. I'll fix now.

**Comment by AsavarTzeth** [comment]
I assume you found this test build then? https://flathub.org/builds/#/builders/32/builds/1627 ?

**Comment by sadko4u** [comment]
Yes. Could you change the build process and pass `SHELL='bash -x'` to the build command?
I assume that I've change passing of CXXFLAGS which were required by KXStudio and now our recent patch is overrided by these flags (source files are build with THUMB instruction set instead of ARM instruction set).

**Comment by AsavarTzeth** [comment]
Also one cause of inconsistencies seem to be that the CI sometimes detect something different to my local qemu environment. For example my last local tests passed, using `armv7a` and `aarch64`, while the CI apparently choose `armv8a` in one of its builds.

I guess its good in the way that it gives you more test coverage right now :) But I should probably remember that and specify profiles manually in production builds.

**Comment by AsavarTzeth** [comment]
I can change that. Do you need that to be single job as well?

**Comment by sadko4u** [comment]
I think for better debugging once you've changed the build process, then keep this variable always as an argument. On my system, the command line looks like:
```
g++ -o /home/pi/git/lsp-plugins/.build/src/core/io/Path.o -c io/Path.cpp -fPIC -march=armv7-a -marm -std=c++98 -fdata-sections -pthread -ffunction-sections -fno-exceptions -fno-asynchronous-unwind-tables -Wall -pipe -fno-rtti '-DLSP_MAIN_VERSION="1.1.9"' '-DLSP_INSTALL_PREFIX="/usr/local"' -O2 -DLSP_NO_EXPERIMENTAL -I/home/pi/git/lsp-plugins/include
```
It would be good to see what's the command line on your system.
Single-threaded build is not necessary since we know the problem file (Thread.cpp/Thread.o) and simply can find it in the build log.

**Comment by AsavarTzeth** [comment]
Well now I happened to push single threaded build (lsp-plugins only). At least I moved the module build order up as far as possible, which gives us the lsp-plugins build result earlier.

**Comment by sadko4u** [comment]
No command line :(

**Comment by AsavarTzeth** [comment]
Really? Did I miss something?

**Comment by sadko4u** [comment]
the command sould look like:
```
make SHELL='bash -x'
make install
```
or something like this for your CI script.

**Comment by AsavarTzeth** [comment]
That should be the case already. Oh wait, could it be `BUILD_MODULES=lv2` which I forgot to remove. Stupid me.

**Comment by sadko4u** [comment]
Haha, I see the problem:
```
-------------------------------------------------------------------------------
Building binaries
  target architecture : armv8a
  target platform     : Linux
  target system       : Linux
  compiler            : cc (GCC) 8.2.0
  modules             : lv2
-------------------------------------------------------------------------------
```
target architecture : **armv8a**

**Comment by AsavarTzeth** [comment]
Yeah. On Flathub it for whatever reason detects that, while on my own workstation I get **armv7a**.

**Comment by AsavarTzeth** [comment]
If that is indeed the only issue I can simply set **armv7a** explicitly for that arch.

**Comment by sadko4u** [comment]
Wait a moment please.

**Comment by sadko4u** [comment]
Pushed a change, please just relaunch: f01e98b9a1263d6cf44cbea8c8c3d6d3fb3eb607

**Comment by sadko4u** [comment]
Yet one more commit: 8048363753ed78fb866dfe25a980ad954d84dfaf

**Comment by sadko4u** [comment]
I believe for 32-bit arm build you need armv7a profile.

**Comment by AsavarTzeth** [comment]
Yes, that is the one I have had success with. All my local tests used that automatically.

**Comment by AsavarTzeth** [comment]
There, I now pushed a change so that all "arm" builds will use the **armv7a** profile.

**Comment by sadko4u** [comment]
Seems to be all OK now except unresolved depencencies.
Also, if you want to build LV2 only, you can just pass additional argument:
```
make BUILD_MODULES='lv2'
```

**Comment by AsavarTzeth** [comment]
That is what I used to do earlier. I can change it back.

The one problem I have with that option is that it still builds a lot of other components, like the ui bits. Although that is fine since I can simply skip installing that.

**Comment by sadko4u** [comment]
Since PHP is required only for building documentation, you can skip the module 'doc' in BUILD_MODULES variable.

**Comment by sadko4u** [comment]
If you don't want to use PHP in a build.

**Comment by AsavarTzeth** [comment]
I found that using the **install_lv2** target also helped solve that issue. Correct?

**Comment by AsavarTzeth** [comment]
Well I think I managed to get it right now. Sorry about the mess in the end. It has been a long day and I am way too tired to think straight at the moment.

**Comment by sadko4u** [comment]
Yes but passing BUILD_MODULES variable can exclude some dependencies.
To build documentation, you need a PHP depenency.
To build ladspa, you need <ladspa.h> dependency.
To build jack, you need jack dependency.
If you don't build these modules, you actually don't need these dependencies.
**install_lv2** does a bit different thing: it just copies the necessary files from local **.build** directory into installation paths.

**Comment by AsavarTzeth** [comment]
Yes, hence why I have been using both recently. Only disabled it a few commits ago in case it somehow would prevent you from getting the entire picture.

Well good news is that the last build just passed the lsp-plugins module for all architectures :)

**Comment by sadko4u** [comment]
Anyway, you came at the right moment. I already wanted to build binary packages for a 1.1.9 release. Now I'll do the release tomorrow.

**Comment by sadko4u** [comment]
Release 1.1.9 has been issued.
