### ISSUE TITLE
[Bug] You cannot set a specific value (double mouse click) in Frequency Mid, Hi and Hi-E of the GOTT Compressor (all variants)

### ISSUE THREAD

**Issue by p-chan5** [sadko4u/lsp-plugins#350]
**Package:** `lsp-plugins-vst2-1.2.13-Linux-x86_64.tar.gz`

**How to reproduce it:**

1. Open a new instance of this plugin.
2. Try to set a specific value (double mouse click) in Frequency Mid, Hi or Hi-E
3. After many tries, you will notice that the value box will never appear like it does with other parameters.

![001](https://github.com/sadko4u/lsp-plugins/assets/123143444/25f5d696-90d7-4fdf-b69f-6e8d9dc3bfd7)

**Comment by bor-T** [comment]
This feature will be available in 1.2.14.

**Comment by p-chan5** [comment]
Great! Thanks for the quick fix <3

**Comment by sadko4u** [comment]
Available in 1.2.14!
