### ISSUE TITLE
Multiband Expander - Not all is shown on 1366x768 Display

### ISSUE THREAD

**Issue by stefan-franz** [sadko4u/lsp-plugins#351]
Only i small wish - if it possible, it would nice to be able using the Multiband Expander on a "small" Display

Linux Mint 21.2 Cinnamon.

![Multiband Expander](https://github.com/sadko4u/lsp-plugins/assets/96744684/5bfda93b-f418-4623-8275-c0606a377922)

**Comment by sadko4u** [comment]
Hi! You can try to reduce the UI scaling and increase font scaling if it will look too small.

**Comment by stefan-franz** [comment]
Hmmm.....the GUI is to big for my DJ Laptop (10 Years old but with Linux Mint 21.2 i high speed machin ;-). 
Display: 1366x768. 
How can i reduce it? I didn't find a way to do that.

**Comment by sadko4u** [comment]
You can use `MENU -> UI Scaling` and `MENU -> Font scaling` options or these icons at the bottom of plugin:
![изображение](https://github.com/sadko4u/lsp-plugins/assets/12834464/2fff41f7-6a03-40c9-95ea-196e17bf47ec)

**Comment by stefan-franz** [comment]
Wow. Superb. 
Now i can work with it. Thanks.
