### ISSUE TITLE
[disscuss] Loudness range reduction?

### ISSUE THREAD

**Issue by LebedevRI** [sadko4u/lsp-plugins#353]
This is more of a question and not a feature request per-se.

Let's suppose i have an audio, for which i **know** it's EBUR128 Integrated Loudness and Loudness Range.
Let's pretend that we've normalized the Integrated Loudness to be at `-23dB`,
but the Loudness Range is far too great to listen to, and we want to reduce it.

If we just apply compressor (w/ threshold at normalized loudness)
we will only affect the loud parts, thus affecting loudness distribution,
so we probably want to use Dyna Processor, to also expand below that.
The ratio calculation to achieve desired loudness range change is obvious.

In an ideal situation, you'd want to essentially process each audio sample separately. 

The question: is compressor the right tool for this?
Which Reactivity/Attack/Release timings would be best for this?
I'm asking from a practical standpoint, i'd like to have such a feature in a music player.

**Comment by sadko4u** [comment]
The question is not clear for me. If you have a track normalized to `-23 LUFS`, which means that the track will give `-23 LUFS` at any part of it, then what's the Loudness Range then? And why it's great (did you mean `high`?)? 
According to BS.1770 specification which defines the LUFS metering algorithm, the RMS value of K-weighted signal is computed for a 400 ms window for each input audio channel.
To answer your question, I need more detailed definition of the problem you're trying to solve.

**Comment by sadko4u** [comment]
1. No. It doesn't change the actual algorithm applied to dynamic processing plugin (Compressor, Gate, Expander, Dynamic Processor). But that will make the device more working like distortion on very low values.
2. You can set the sidechain mode to `Peak` and lower the values of mentioned parameters. This will make dynamic tools work like clipper/distortion.
3. There is no clamping in sidechain. Yes, it should behave the same way like if you did it with the -48 dB. I often use such trick when I don't have extra gain or have too much gain at the input.
