### ISSUE TITLE
Wrong use of CFLAGS vs CXXFLAGS

### ISSUE THREAD

**Issue by falkTX** [sadko4u/lsp-plugins#38]
CFLAGS is the variable used for building C code.
CXXFLAGS is used for C++.

lsp-plugins consists mostly of C++ code, but I see only CFLAGS is used.
Please switch to use CXXFLAGS instead.

**Comment by sadko4u** [comment]
Please try this commit: d06ac3987aeb241c74a414ec47443af396ee0f06

**Comment by falkTX** [comment]
That looks like it might work.
One thing I noticed just now, you use `CC` instead of usual `CXX`. any reason for that?

**Comment by falkTX** [comment]
The CXX (g++) will build code in C++ by default, and link to libstdc++ at the end as well.
If we use CC (gcc) we manually need to link to libstdc++

**Comment by sadko4u** [comment]
Nothing special. Just not following usual rules when writing makefiles.
This commit should fix the variable name: 98249addde16c0140d7438408bb7f3c24dd7c49c

**Comment by sadko4u** [comment]
Merged this change into **devel** branch: 6830de7d3fb050a91ac81c18ff0e1d125c4522c5

**Comment by sadko4u** [comment]
Release 1.1.9 has been issued.
