### ISSUE TITLE
Environment CFLAGS not respected

### ISSUE THREAD

**Issue by falkTX** [sadko4u/lsp-plugins#39]
I have set custom CFLAGS (using `export` in the environment) when building lsp-plugins.
It includes `-Wno-unused-result`

But during the build I still see stuff like:
```
x86.cpp:389:115: warning: ignoring return value of ‘int asprintf(char**, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         asprintf(&model, "vendor=%s, family=0x%x, model=0x%x", cpu_vendors[f.vendor], int(f.family), int(f.model));
```

This leads me to believe the makefiles are simply ignoring/overriding my custom flags.
It is impossible to see due to all compiler flags being hidden away, but that is another issue

**Comment by sadko4u** [comment]
Should be fixed with this commit: d06ac3987aeb241c74a414ec47443af396ee0f06

**Comment by sadko4u** [comment]
Merged change into **devel** branch: 6830de7d3fb050a91ac81c18ff0e1d125c4522c5

**Comment by sadko4u** [comment]
Release 1.1.9 has been issued.

**Comment by falkTX** [comment]
There is a regression on this for 1.2, environment variables such as CFLAGS, CXXFLAGS etc are no longer respected.
A way around it for me for now is to tweak the generated config before building, like so:
```
sed -i 's/^CFLAGS=/CFLAGS+=/' .config.mk
sed -i 's/^CXXFLAGS=/CXXFLAGS+=/' .config.mk
...etc
```

**Comment by sadko4u** [comment]
I think you should better open new issue for that. I'll try to solve the problem for the upcoming 1.2.2.
