### ISSUE TITLE
vst3 plugins are loaded incorrectly in Carla v2.5.8

### ISSUE THREAD

**Issue by atskler** [sadko4u/lsp-plugins#398]
Somehow the vst3 line of plugins are laded incorrectly in Carla v2.5.8.
No matter what plugin I select the "Trigger Mono" plugin is loaded.
(Beforehand it was something else that was always loaded.)

It looks like this:
https://www.dropbox.com/scl/fi/cr8ns1u07johy644a8x7t/lsp-vst3-misload-in-carla.mp4?rlkey=vh0bctcq4yz76f7uvtdawwlhj&st=hyc5mdez&dl=0

Is this a Carla problem or an lsp vst3 problem?

Thank you in advance for your help with this.

**Comment by sadko4u** [comment]
This is known problem of Carla:
https://github.com/falkTX/Carla/issues/1869

**Comment by sadko4u** [comment]
Related ticket in our tracker: https://github.com/lsp-plugins/lsp-plugins/issues/384

**Comment by sadko4u** [comment]
The response from @falkTX, the author and maintainer of Carla:
https://github.com/lsp-plugins/lsp-plugins/issues/384#issuecomment-1984188270

**Comment by atskler** [comment]
Thank you for the comprehensive explanation.
