### ISSUE TITLE
Add verbose build flag, or otherwise make it possible to see the compiler calls

### ISSUE THREAD

**Issue by falkTX** [sadko4u/lsp-plugins#40]
Right now it is not possible to see what the compiler is doing behind the scenes.

I have a few flags I always put in packages for kxstudio (like hide all symbols), but right now it is not possible to see if they are actually in use unless I patch out a bunch of makefile lines.
(I pretty much already confirmed the custom flags are NOT being used)

I have a build issue regarding the tests that right now I can't simply debug. (might be my fault, I have no idea...)
Tried a few things to see the actual g++ args but failed.

**Comment by sadko4u** [comment]
You may run verbose build using:
```
make SHELL='bash -x'
```

**Comment by sadko4u** [comment]
The option I've specified works, additional flags for verbosity are not necessary.
