### ISSUE TITLE
AudioFile.cpp fails to find sndfile in custom prefix

### ISSUE THREAD

**Issue by falkTX** [sadko4u/lsp-plugins#41]
I have libsndfile installed in a custom prefix, easily found by pkg-config.
I see there pkg-config being called at some point in the makefiles, which leads me to believe it is doing the right thing.
Somehow build still fails though, with:
```
files/AudioFile.cpp:17:21: fatal error: sndfile.h: No such file or directory
 #include <sndfile.h>
```
so I guess `SNDFILE_HEADERS` is missing when building this file

**Comment by sadko4u** [comment]
This commit should work: ee5bf1d65af4c7fdf7e60e63ff6dc1577427a222

**Comment by falkTX** [comment]
Thanks for the fix.
Now I have a similar issue somewhere else though.
```
  g++ lv2.cpp
In file included from /<<PKGBUILDDIR>>/include/container/lv2/wrapper.h:16:0,
                 from lv2.cpp:19:
/<<PKGBUILDDIR>>/include/container/CairoCanvas.h:15:29: fatal error: cairo/cairo.h: No such file or directory
     #include <cairo/cairo.h>
```

**Comment by sadko4u** [comment]
Good, fixed: f80b842356fd1716430b1ab8148fe6e531e4f599

**Comment by falkTX** [comment]
Nice, lv2.cpp got fixed, now `jack.cpp` fails with exactly the same thing.
I patched it myself and with this part it finally builds!
So just 1 more fix then.

**Comment by sadko4u** [comment]
This, right?
2c8c3fbc7765f0a1a11f69b70fba26a44363022b

**Comment by falkTX** [comment]
Yes, thank you.
With these fixes (just build fixes and backporting the one regarding IR not working), I will push lsp-plugins package into kxstudio repos :)

**Comment by sadko4u** [comment]
I'll merge changes into **devel** branch which already contains all necessary fixes.

**Comment by sadko4u** [comment]
Merged all changes to the **devel** branch: 6830de7d3fb050a91ac81c18ff0e1d125c4522c5
Please try to build from **devel**.

**Comment by falkTX** [comment]
I can confirm build is fixed in devel branch

Tests still fail, but that is a different issue, this one can be closed.
Later on I will figure out a way to fix the tests, I guess it is something with my custom setup.
FYI the error I get is:
```
/<<BUILDDIR>>/lsp-plugins-1.1.7+git20190322/.build/test_core.o:(.text.unlikely._ZN5mtest12_GLOBAL__N_116mtest_standalone16plugin_not_foundEPKc.isra.3+0xb54): undefined reference to `lsp::test_plugin_metadata::metadata'
collect2: error: ld returned 1 exit status
```

**Comment by sadko4u** [comment]
Could you a bit cleaner explain about what are you trying to do with test_core.o?

**Comment by falkTX** [comment]
It is the output of `make test`, which debian package building does automatically if it detects that the makefile supports the `test` target.
Should this be ignored?

**Comment by sadko4u** [comment]
Yes, definitely because 'make test' will build test binary whch can be used for test purposes (unit testing and performance testing) and this requires to perform a full rebuild and issuing 'make clean' first.

**Comment by falkTX** [comment]
ok, all good then!
I pushed the package to the kxstudio repos now.
When 1.1.9 is released, I will switch to that.

**Comment by sadko4u** [comment]
Thanks for your work!

**Comment by sadko4u** [comment]
I've altered build scripts in **devel** branch because compatibility with FlatPak was broken.
Please confirm that this commit builds OK: 6bb93d7e2e15fc113e868b0efa1a3c61043c1e69

**Comment by sadko4u** [comment]
Finally, after dancing with FlatPak I've pushed the following commit: 8048363753ed78fb866dfe25a980ad954d84dfaf
Please check if it builds successfully for KXStudio

**Comment by sadko4u** [comment]
Release 1.1.9 has been issued.
