### ISSUE TITLE
inlineDisplay lv2 extensionData missing from ttl files

### ISSUE THREAD

**Issue by falkTX** [sadko4u/lsp-plugins#45]
This is a continuation of 83ca69b7f709d0f3356d812a0069c751085f14d4

Most (all? did not check) lsp-plugins do not list inlinedisplay in their ttl files.
Please make it so that inlinedisplay is listed.
Could be either for all plugins or on a plugin-by-plugin basis.

**Comment by sadko4u** [comment]
I think I should dig a bit deeper and refactor plugin metadata to properly generate support of InlineDisplay extension in TTL.

**Comment by sadko4u** [comment]
Created a **github-issue-45** branch.
Please confirm that this commit fixes the problem: 6f1f66e6ceefaab45a08def8abf3296bc612809d

**Comment by falkTX** [comment]
I can confirm it works!

Looks great in High-DPI mode :scream: 
![Screenshot_20190326_202420](https://user-images.githubusercontent.com/1334853/55027271-2bb74380-5005-11e9-897a-a1647e279cb9.png)

**Comment by sadko4u** [comment]
Very nice.
Removed branch **github-issue-45**, merged changes into **devel** branch: 95359fae6424aee9259761b3eb7fe46df6bc8ff1

**Comment by sadko4u** [comment]
@falkTX , how about rack mode? Will inline display be there, too?

**Comment by falkTX** [comment]
in rack mode the patchbay shows a single client, the inline display does not work well there.
if you mean the rack tab, I made it so that knobs will extend to the width:

![image](https://user-images.githubusercontent.com/1334853/55028379-d466a280-5007-11e9-832e-baa660fca7b7.png)

I am happy with the current behaviour, it will remain that for v2.1

**Comment by sadko4u** [comment]
@falkTX How does Calf show custom UI in rack mode? Is is a Carla-specific extension?

**Comment by falkTX** [comment]
Carla specific code, not made into an extension yet.
It is one of several "skins". user can pick any for any plugin, same for the color.

**Comment by falkTX** [comment]
unrelated to this bug, just wanted to post this.
synthpod is getting inline display support as well. looks awesome! :open_mouth: 

![image](https://user-images.githubusercontent.com/1334853/55081154-9ddc6680-509f-11e9-902f-c9d668a9f6d2.png)

**Comment by sadko4u** [comment]
Available in 1.1.10 release!
