### ISSUE TITLE
lsp-plugins-jack-core-1.1.9.so installs to /usr/lib

### ISSUE THREAD

**Issue by eeickmeyer** [sadko4u/lsp-plugins#49]
Hi!

I'm working on packaging lsp-plugins for Ubuntu (and Debian), but the biggest roadblock that I'm running into is that lsp-plugins-jack-core-1.1.9.so installs directly into the /usr/lib directory and, per specifications, must be in a subdirectory (i.e. /usr/lib/lsp-plugins). Otherwise, I have a very clean package, but it is being denied due to this one issue.

Would you please move the shared object (and change anything looking for it) to /usr/lib/lsp-plugins (or really any proper subdirectory of your choosing within /usr/lib)? This way, your work would reach a broader audience and would be installed by default in Ubuntu Studio.

Thanks! :)

**Comment by sadko4u** [comment]
Yes, it's fixable. Will do it ASAP.

**Comment by sadko4u** [comment]
Created **github-issue-49** branch based on **master** branch.
This patch should fix the problem: 4442bfb618753616909daabedb3fedd49f815b39
Please confirm.

**Comment by eeickmeyer** [comment]
@sadko4u That patch worked! It has been included in the package, and has been approved for upload. This means it will be included in Ubuntu 19.10's repositories and in Ubuntu Studio 19.10 by default. If congratulations is in order, then congratulations, your work will be in Ubuntu.

**Comment by sadko4u** [comment]
Merged changes to the **devel** branch: ee611ae387562b180c4a10e3c4a9e61a07a255b7.
Fast-forwarded the **hotfix** branch.
The changes will be available in the upcoming release.

**Comment by sadko4u** [comment]
Available in 1.1.10 release!
