### ISSUE TITLE
Tests fail on debian/ubuntu build 

### ISSUE THREAD

**Issue by eeickmeyer** [sadko4u/lsp-plugins#50]
When building for Ubuntu, we are running into this problem unless we disable the test suite:

`/usr/bin/ld: /<<PKGBUILDDIR>>/.build/test_core.o: in function 'mtest::(anonymous namespace)::mtest_standalone::plugin_not_found(char const*) [clone .isra.3]':
./src/test/./include/metadata/modules.h:150: undefined reference to 'lsp::test_plugin_metadata::metadata'`

Enitre build log [here.](https://launchpadlibrarian.net/426670147/buildlog_ubuntu-eoan-amd64.lsp-plugins_1.1.9-0~201906031728~ubuntu19.10.1_BUILDING.txt.gz)

Only way to get it to build is to disable the test suite.

**Comment by sadko4u** [comment]
There's something wrong with your sources. I tried to build plugins from *devel*, *master* and *hotfix* branches and all builds succeeded with the following command on my system:
```
make -j8 test
```

**Comment by eeickmeyer** [comment]
Feel free to look at the discussion on https://bugs.launchpad.net/lsp-plugins/+bug/1827288. We use Launchpad to build everything for Ubuntu, so we are restricted to those sources: Here's what it really comes down to per Steve Langasek, an Archive Administrator and member of the Ubuntu Technical Board directly employed by Canonical:

>The only way to run the tests is by rebuilding the software with different
>build flags and testing that. So the tests are not a valid test of the
>binaries being shipped, and instead triple the package build time for
>minimal added value.
>
>This is an upstream issue to sort out before we would want to do build-time
>tests.

So, basically there's nothing that can really be done on our side to fix this.

**Comment by sadko4u** [comment]
Is it possible to run build again before running tests? I can change the build scripts so the binaries for tests will be built in a different folder (not **.build** but **.test**, for example) and can be launched from this folder.

**Comment by eeickmeyer** [comment]
That's a good question, but I fear that would still triple the package build time. That said, I'll ask and get back to you.

**Comment by sadko4u** [comment]
> That's a good question, but I fear that would still triple the package build time. That said, I'll ask and get back to you.

Or you can build both versions (test and non-test) on the build stage (the 'release' will be in '.build' subdirectory, the 'test' will be in '.test' subdirectory), then package all from the '.build' as a distribution and launch tests from '.test' at the testing build stage.

**Comment by sadko4u** [comment]
For example, the build command will look like:
```
make clean all test
```

**Comment by eeickmeyer** [comment]
The way building is done in Debian and Ubuntu is by using [dh_auto_build](https://manpages.debian.org/testing/debhelper/dh_auto_test.1.en.html) which is a script. It can be manually overridden, but it might not even be necessary. Still waiting for replies from the team.

**Comment by sadko4u** [comment]
Anyway, I've added a feature of issuing the following build command:
```
make clean all test
```
It will build release binaries into '.build' subfolder and test files into '.test' subfolder.
Then:
```
make install
```
Will launch the usual installation process. Also, you will be available to run the tests by issuing:
```
.test/lsp-plugins-test utest
```

**Comment by sadko4u** [comment]
Here's the commit in the **github-issue-50** branch: a9a5503cef6af7206c1d844602a445dfa492be95

**Comment by sadko4u** [comment]
And additional build optimization patch: 03f52733b7ba57c876582f9f6513ac9e829a4610

**Comment by sadko4u** [comment]
On my CPU, the build result is the following:

```
time make -j16 clean all
real    0m12,565s
user    2m16,574s
sys     0m18,691s
```

```
time make -j16 clean all test
real    0m20,763s
user    4m20,840s
sys     0m34,448s
```

```
cat /proc/cpuinfo | grep 'model name' | head -n 1
model name      : AMD Ryzen 7 2700 Eight-Core Processor
```

**Comment by eeickmeyer** [comment]
I'll give it a try and report back.

**Comment by sadko4u** [comment]
Got successful builds on:
* Linux x86_64
* Linux i586
* FreeBSD i586 (gcc)
* FreeBSD x86_64 (gcc)
* Raspbian armv7
* Arch Linux aarch64

**Comment by eeickmeyer** [comment]
We have a successful build on our end. Pending no further issues this should be included in Ubuntu 19.10.

**Comment by sadko4u** [comment]
Merged changes to the **hotfix** and **devel** branches, removed **github-issue-50** branch.

**Comment by sadko4u** [comment]
Avaliable in 1.1.10 release!
