### ISSUE TITLE
Question: Fails to build from source on architectures other than amd64/i386

### ISSUE THREAD

**Issue by eeickmeyer** [sadko4u/lsp-plugins#51]
Using the default configuration, we are unable to build on architectures other than i386/amd64 for Ubuntu's default repository. Are your intentions that lsp-plugins can be built for all architectures, or do you want us to just limit it to amd64/i386?

**Comment by sadko4u** [comment]
The answer is here:
https://github.com/sadko4u/lsp-plugins/blob/04cc45a4aee3bd3a46ecbd0a9160d0d87f8f8a32/README.txt#L30-L47

In 1.1.10 release the architecture requiremens should be reduced (AFAIR) but there is no guarantee that plugins will work for non-supported architectures.

At least, you should get ARMv7 and AArch64 versions compiled, too.

**Comment by eeickmeyer** [comment]
Excellent! Thanks for the info. Everything is all sorted now.
