### ISSUE TITLE
Avoid fork(3) - prefer vfork(2)

### ISSUE THREAD

**Issue by x42** [sadko4u/lsp-plugins#54]
The problem with fork() is that it duplicates the page tables and file-descriptors of the parent process. It is inherently not realtime-safe. Any processes that has realtime threads (here a plugin-host) should not use fork(). In context of pro-audio on POSIX systems, prefer `vfork(); execve();`

https://github.com/sadko4u/lsp-plugins/blob/543e17e9de3b8dc9de6e31438d1223d792054626/src/ui/tk/widgets/LSPHyperlink.cpp#L107

PS. You may also investigate using `posix_spawn()`, but that's a library function on Linux.

**Comment by sadko4u** [comment]
The things should go right after this commit: 03174d7827d1fac9443bbbc9de2b6d343f3bdd5b

@x42 please verify.

**Comment by x42** [comment]
Fine IFF  `__USE_GNU` is defined at compile time. Can that happen?

If so, you could use a wrapper application that does the file re-direct after vfork+exec.

**Comment by sadko4u** [comment]
@x42 right
Changed code to use vfork() directly when __USE_GNU is not defined.
Here's the following commit: 88a8ede1da4eee0204fb531b9343d921a4404e5c

**Comment by x42** [comment]
Looks good. Thanks!

Could that happen in the first place though? On what POSIX OS +  compiler is __USE_GNU not defined? Can that even happen?

**Comment by sadko4u** [comment]
@x42 __USE_GNU is not defined on FreeBSD 11. There, <spawn.h> does not provide a flag that tells posix_spawn to prefer vfork().

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 4bef72f03f862465a3da353a194275ddd6d48734

**Comment by sadko4u** [comment]
Removed **github-issue-54** branch

**Comment by sadko4u** [comment]
Available in the 1.1.11 release!
