### ISSUE TITLE
Error message in Harrison Mixbus 32C

### ISSUE THREAD

**Issue by TobbeT** [sadko4u/lsp-plugins#58]
Hi,

Installed lsp-plugins from KXStudio repos. When I start Harrison Mixbus 32C I get this error message:
[ERROR]: LADSPA: cannot load module "/usr/lib/ladspa/lsp-plugins-ladspa.so" (/usr/lib/ladspa/lsp-plugins-ladspa.so: undefined symbol: _ZN3lsp17builtin_resourcesE).

Same thing on Harrison Mixbus 5, well they both is built ontop of Ardour...I think.

Thank you

**Comment by sadko4u** [comment]
Thank yo for a report. It seems to be a problem of plugins of LADSPA-only format.

**Comment by sadko4u** [comment]
Created **hotfix** patch: 683a1ebd31d8a26dc7494e7330412bdd971d59dc
Merged changes into **devel** branch: a80c2f4c87fb2aab94239b410ad4e8572c1c710e

Verified, now LADSPA plugins are working fine.

**Comment by TobbeT** [comment]
Faster than Flash Gordon :)

Thanks alot.

**Comment by sadko4u** [comment]
Available in the 1.1.11 release!
