### ISSUE TITLE
Oscillator-Mono waveform names misleading

### ISSUE THREAD

**Issue by jrigg** [sadko4u/lsp-plugins#59]
Just tried the oscillator-mono in 1.1.10 (x86_64 JACK version). A minor nitpick: the sawtooth wave is actually triangular. A true sawtooth is asymmetrical which makes it useful for testing for polarity inversion:
https://en.wikipedia.org/wiki/Sawtooth_wave

The parabolic waveform can also be used for this, but it would be good to have both triangle and sawtooth waves in a future version.

**Comment by jrigg** [comment]
Also, I'm not sure what the squared sine and cosine are here, but I'd expect a squared sine to look similar to a full-wave rectified sine wave:
https://en.wikipedia.org/wiki/File:Gratz.rectifier.en.svg

**Comment by sadko4u** [comment]
Hello!
I believe you can change the form of sawtooth wave just by using the 'Width' parameter:
![image](https://user-images.githubusercontent.com/12834464/69534053-1c203e00-0f8a-11ea-825e-ef8606af8263.png)

Squared sine function in fact is:
```
a(t) = sqr(sin(2*pi*f*t + phase));
```

**Comment by sadko4u** [comment]
Or do I right understand that you prefer to see 'Triangular' instead of 'Sawtooth' in the combo box?

**Comment by jrigg** [comment]
Ah, I missed the width control. No problem, sorry for the noise. I'll close the issue.

Regarding the squared sine, I was thinking of squaring the real amplitude (eg. for generating second harmonic). Again, no problem.

Looking forward to 1.1.11; the plugins get better with every release.

**Comment by sadko4u** [comment]
Thanks. There be a couple of interesting changes in 1.1.11.
Estimated release date is December, 21th.
