### ISSUE TITLE
[ERR] Could not find LSP JACK core library

### ISSUE THREAD

**Issue by magnetophon** [sadko4u/lsp-plugins#6]
Many thanks for open open-sourcing lsp-plugins!

I'm trying to package them for [NixOS](https://nixos.org).
The LADSPA and LV2 plugins are working, but the standalone jack gives the above error.
That's probably because NixOS uses non-standard paths, so we don't have ``/usr/lib``, for example.
I've tried to patch the Makefile and ``/include/container/jack/main.h``, but it's not working yet.

Where else is defined where these libraries are found?
Am I missing something?

**Comment by sadko4u** [comment]
Hello!
Where do you install *.so files?
Especially, where are located files:
`lsp-plugins-jack-core-1.1.4-x86_64.so`
`lsp-plugins-vst-core-1.1.4-x86_64.so`

after installation?

**Comment by magnetophon** [comment]
Thanks for the quick reply!


```
ls /nix/store/9ky33v5dgi7zilwpz4hc2bfryfnrh75q-lsp-plugins-1.1.4/lib                                                                                                                     
ladspa	lsp-plugins-jack-core-1.1.4-x86_64.so  lv2  vst

ls /nix/store/9ky33v5dgi7zilwpz4hc2bfryfnrh75q-lsp-plugins-1.1.4/lib/vst                                                                                                                 lsp-plugins-lxvst-1.1.4-x86_64
```

**Comment by sadko4u** [comment]
The main problem is that standalone and VST files are just wrappers for loading these libraries. These wrappers do lookup of *.so files ni standard paths (and user's home directories), load them and pass execution to the proper plugin. 

Because libraries lay in non-standard paths, wrappers can not find them.

To find these files, we should know paths to search for. Is it possible to determine the location of these files dynamically?

Also, is it possible under your system to determine the target platform, like __LINUX__ macro definition for C preprocessor?

**Comment by magnetophon** [comment]
Sure, those are both possible.
Where should I put these paths, and how should I use the platform knowledge?

**Comment by sadko4u** [comment]
You can organize the similar cycle that calls **lookup_jack_main** but right paths, before this cycle:
https://github.com/sadko4u/lsp-plugins/blob/db70248bc4a528dc51586638e9cd71259cf14b7a/include/container/jack/main.h#L234

Same here:
https://github.com/sadko4u/lsp-plugins/blob/db70248bc4a528dc51586638e9cd71259cf14b7a/include/container/vst/main.h#L225

Of course I prefer that this code change would be conditionally-compiled for NixOS only (needs right preprocessor directive).

**Comment by magnetophon** [comment]
I already patch ``jack/main.h`` to point to the correct paths, but it's not working yet.
Any ideas on how to troubleshoot further?

**Comment by sadko4u** [comment]
You can attach your changes here (please use devel branch as base), then probably we'll find the solution together.

**Comment by magnetophon** [comment]
Never mind, it seems I did something wrong somewhere; it works now.

I'm 100% sure that at one point I had the correct paths in there, but it still didn't work.
I guess there was another error at that point in the life of the package.

Again, many thanks for your help and your software!

**Comment by sadko4u** [comment]
Maybe it would be good to add your changes to the upstream?

**Comment by magnetophon** [comment]
Thanks for the offer, much appreciated.
I'm not sure how that would work though.

Let me explain:
NixOS puts ech package in it's own path, which is generated at compile time, by hashing all compile inputs: dependencies and their version, source and it's version, compile flags, etcetera.
So this path changes a lot, as dependencies are updated.

At compile time, there is a variable called ``$out``, which will be replaced with the current output path of the package, so you can replace ``/usr/lib`` with ``$out/lib``, in the relevant files. and then it works.

So I'm not sure if it's possible and/or  desiderable to upstream that change.

I hope I explained it well, since I'm far from a NixOS expert.

**Comment by sadko4u** [comment]
You can pass the value of $out from build scripts as a value for macro definition. For example:
```
make CC_FLAGS=-DNIXOS_LIB_PATH="$out/lib"
```
And just use the macro **NIXOS_LIB_PATH** everywhere in code as a string if it's present.

**Comment by magnetophon** [comment]
I'm not 100% sure I understand what you are suggesting, but it seems more complicated than what I have now, and I'm not sure what the gain would be.

**Comment by sadko4u** [comment]
I mean the following: 9223a9c9ed0318a1709fb9b8592d1c775771265f

I just run:
```
make CC_FLAGS=-DNIXOS_LIB_PATH="/nix/store/s2sjbl85xnrc18rl4fhn56irkxqxyk4p-lsp-plugins"
```
And get the string in binaries:
```
grep -c '/nix/store/s2sjbl85xnrc18rl4fhn56irkxqxyk4p-lsp-plugins' .build/src/vst/* | grep ':1'
```

**Comment by magnetophon** [comment]
I went ahead with a [PR](https://github.com/NixOS/nixpkgs/pull/47694), since the package seems ok to me as it is.
That doesn't mean your suggestions aren't good ones, but just that I can't judge their merit.

**Comment by sadko4u** [comment]
I think, the suggestion with PREFIX is most proper one.
Added support of PREFIX variable: 6ba133313cd4f8c8d1dcddb97bd901f58c9caec1

Now you can issue:
```
make PREFIX="/nix/store/s2sjbl85xnrc18rl4fhn56irkxqxyk4p-lsp-plugins"
make install PREFIX="/nix/store/s2sjbl85xnrc18rl4fhn56irkxqxyk4p-lsp-plugins"
```
Where "/nix/store/s2sjbl85xnrc18rl4fhn56irkxqxyk4p-lsp-plugins" is the actual value of $out variable.

**Comment by magnetophon** [comment]
That's a seems to be a great solution.
Even better would be if you could make it work with:
```
make PREFIX="/nix/store/s2sjbl85xnrc18rl4fhn56irkxqxyk4p-lsp-plugins"
make install
```
That is what NixOS does by default, and afaik how the standard was intended.

**Comment by sadko4u** [comment]
This commit should give the expected behaviour: 74673751b3a978974d58efa529d21331c43f540a
Please verify.

**Comment by magnetophon** [comment]
Yes, that works, thanks!
The cherry on the cake would be to make it work with ``make --prefix=$out``, cause contrary to what I said earlier, *that* is how it normally works. Sorry for the confusion...

**Comment by sadko4u** [comment]
No, it's not possible because `--prefix` is not a legal option for `make`. Maybe you're confusing it with `--prefix` option of `automake` scripts?
For `Makefile`, you're available to pass only values for variables and some other execution options, so I think I'll end with this solution, because it already works much better than the first commit in this branch :).

**Comment by magnetophon** [comment]
Sorry for all the misinformation I'm feeding you.
Thanks for working out a solution with me.

**Comment by sadko4u** [comment]
Merged changes into 'devel' branch, merge commit: cd917c0b826f37a82f7576e10e7ed7c8c9ace740

**Comment by magnetophon** [comment]
Thanks!

**Comment by magnetophon** [comment]
Thanks for the 1.2.0 release, looks great!
I'm running into this problem again.

I also noticed the plugins are now installed in ``DESTDIR`` instead of ``PREFIX``, is that intentional?

**Comment by sadko4u** [comment]
Hello!

You need to do:
```
make config PREFIX=<...>
```

When building plugins

**Comment by sadko4u** [comment]
Also please consider running `make help` for more options.

**Comment by magnetophon** [comment]
Thanks for the quick reply!

When I use
```
make config PREFIX=<...>
```
I don't need ``DESTDIR`` anymore, but I still get the jack error.

**Comment by magnetophon** [comment]
Here's the full build output: https://sebsauvage.net/paste/?a3715941f9d08c2a#NrWb28V4p7x0w89VQHvgzMIA2QqwnYwAqlUQaY6re/0=

Here's the pkg code I'm using:
```nix
{ lib, stdenv, fetchurl, pkg-config, makeWrapper

, libsndfile, jack2
, libGLU, libGL, lv2, cairo
, ladspaH, php }:

stdenv.mkDerivation rec {
  pname = "lsp-plugins";
  version = "1.2.0";

  src = fetchurl {
    url = "https://github.com/sadko4u/${pname}/releases/download/${version}/${pname}-src-${version}.tar.gz";
    sha256 = "sha256-r3UzK/mW3Vcq4ajm6jU30CzJXFoFt+4EWXr9BogA6Xc=";
  };

  nativeBuildInputs = [ pkg-config php makeWrapper ];
  buildInputs = [ jack2 libsndfile libGLU libGL lv2 cairo ladspaH ];

  makeFlags = [
    "PREFIX=${placeholder "out"}"
  ];

  NIX_CFLAGS_COMPILE = "-DLSP_NO_EXPERIMENTAL";


  configurePhase = ''
    make config PREFIX=${placeholder "out"}
  '';

  doCheck = true;

  enableParallelBuilding = true;

  # postInstall = ''
  # mv $out/usr/local/* $out
  # rm -rf $out/usr
  # '';

  meta = with lib;
    { description = "Collection of open-source audio plugins";
      longDescription = ''
        Compatible with follwing formats:

        - LADSPA - set of plugins for Linux Audio Developer's Simple Plugin API
        - LV2 - set of plugins and UIs for Linux Audio Developer's Simple Plugin API (LADSPA) version 2
        - LinuxVST - set of plugins and UIs for Steinberg's VST 2.4 format ported on GNU/Linux Platform
        - JACK - Standalone versions for JACK Audio connection Kit with UI

        Contains the following plugins:

        - Limiter Mono - Begrenzer Mono
        - Limiter Stereo - Begrenzer Stereo
        - Dynamic Processor LeftRight - Dynamikprozessor LeftRight
        - Dynamic Processor MidSide - Dynamikprozessor MidSide
        - Dynamic Processor Mono - Dynamikprozessor Mono
        - Dynamic Processor Stereo - Dynamikprozessor Stereo
        - Expander LeftRight - Expander LeftRight
        - Expander MidSide - Expander MidSide
        - Expander Mono - Expander Mono
        - Expander Stereo - Expander Stereo
        - Crossover LeftRight x8 - Frequenzweiche LeftRight x8
        - Crossover MidSide x8 - Frequenzweiche MidSide x8
        - Crossover Mono x8 - Frequenzweiche Mono x8
        - Crossover Stereo x8 - Frequenzweiche Stereo x8
        - Gate LeftRight - Gate LeftRight
        - Gate MidSide - Gate MidSide
        - Gate Mono - Gate Mono
        - Gate Stereo - Gate Stereo
        - Graphic Equalizer x16 LeftRight - Grafischer Entzerrer x16 LeftRight
        - Graphic Equalizer x16 MidSide - Grafischer Entzerrer x16 MidSide
        - Graphic Equalizer x16 Mono - Grafischer Entzerrer x16 Mono
        - Graphic Equalizer x16 Stereo - Grafischer Entzerrer x16 Stereo
        - Graphic Equalizer x32 LeftRight - Grafischer Entzerrer x32 LeftRight
        - Graphic Equalizer x32 MidSide - Grafischer Entzerrer x32 MidSide
        - Graphic Equalizer x32 Mono - Grafischer Entzerrer x32 Mono
        - Graphic Equalizer x32 Stereo - Grafischer Entzerrer x32 Stereo
        - Impulse Responses Mono - Impulsantworten Mono
        - Impulse Responses Stereo - Impulsantworten Stereo
        - Impulse Reverb Mono - Impulsnachhall Mono
        - Impulse Reverb Stereo - Impulsnachhall Stereo
        - Sampler Mono - Klangerzeuger Mono
        - Sampler Stereo - Klangerzeuger Stereo
        - Compressor LeftRight - Kompressor LeftRight
        - Compressor MidSide - Kompressor MidSide
        - Compressor Mono - Kompressor Mono
        - Compressor Stereo - Kompressor Stereo
        - Artistic Delay Mono - Künstlerische Verzögerung
        - Artistic Delay Stereo - Künstlerische Verzögerung
        - Latency Meter - Latenzmessgerät
        - Loudness Compensator Mono - Lautstärke Kompensator Mono
        - Loudness Compensator Stereo - Lautstärke Kompensator Stereo
        - Multiband Expander LeftRight x8 - Multi-band Expander LeftRight x8
        - Multiband Expander MidSide x8 - Multi-band Expander MidSide x8
        - Multiband Expander Mono x8 - Multi-band Expander Mono x8
        - Multiband Expander Stereo x8 - Multi-band Expander Stereo x8
        - Multiband Gate LeftRight x8 - Multi-band Gate LeftRight x8
        - Multiband Gate MidSide x8 - Multi-band Gate MidSide x8
        - Multiband Gate Mono x8 - Multi-band Gate Mono x8
        - Multiband Gate Stereo x8 - Multi-band Gate Stereo x8
        - Multiband Compressor LeftRight x8 - Multi-band Kompressor LeftRight x8
        - Multiband Compressor MidSide x8 - Multi-band Kompressor MidSide x8
        - Multiband Compressor Mono x8 - Multi-band Kompressor Mono x8
        - Multiband Compressor Stereo x8 - Multi-band Kompressor Stereo x8
        - Oscilloscope x1 - Oscilloscope x1
        - Oscilloscope x2 - Oscilloscope x2
        - Oscilloscope x4 - Oscilloscope x4
        - Oscillator Mono - Oszillator Mono
        - Parametric Equalizer x16 LeftRight - Parametrischer Entzerrer x16 LeftRight
        - Parametric Equalizer x16 MidSide - Parametrischer Entzerrer x16 MidSide
        - Parametric Equalizer x16 Mono - Parametrischer Entzerrer x16 Mono
        - Parametric Equalizer x16 Stereo - Parametrischer Entzerrer x16 Stereo
        - Parametric Equalizer x32 LeftRight - Parametrischer Entzerrer x32 LeftRight
        - Parametric Equalizer x32 MidSide - Parametrischer Entzerrer x32 MidSide
        - Parametric Equalizer x32 Mono - Parametrischer Entzerrer x32 Mono
        - Parametric Equalizer x32 Stereo - Parametrischer Entzerrer x32 Stereo
        - Phase Detector - Phasendetektor
        - Profiler Mono - Profiler Mono
        - Profiler Stereo - Profiler Stereo
        - Room Builder Mono - Raumbaumeister Mono
        - Room Builder Stereo - Raumbaumeister Stereo
        - Multi-Sampler x12 DirectOut - Schlagzeug x12 Direktausgabe
        - Multi-Sampler x12 Stereo - Schlagzeug x12 Stereo
        - Multi-Sampler x24 DirectOut - Schlagzeug x24 Direktausgabe
        - Multi-Sampler x24 Stereo - Schlagzeug x24 Stereo
        - Multi-Sampler x48 DirectOut - Schlagzeug x48 Direktausgabe
        - Multi-Sampler x48 Stereo - Schlagzeug x48 Stereo
        - Sidechain Multiband Expander LeftRight x8 - Sidechain Multi-band Expander LeftRight x8
        - Sidechain Multiband Expander MidSide x8 - Sidechain Multi-band Expander MidSide x8
        - Sidechain Multiband Expander Mono x8 - Sidechain Multi-band Expander Mono x8
        - Sidechain Multiband Expander Stereo x8 - Sidechain Multi-band Expander Stereo x8
        - Sidechain Multiband Gate LeftRight x8 - Sidechain Multi-band Gate LeftRight x8
        - Sidechain Multiband Gate MidSide x8 - Sidechain Multi-band Gate MidSide x8
        - Sidechain Multiband Gate Mono x8 - Sidechain Multi-band Gate Mono x8
        - Sidechain Multiband Gate Stereo x8 - Sidechain Multi-band Gate Stereo x8
        - Sidechain Multiband Compressor LeftRight x8 - Sidechain Multi-band Kompressor LeftRight x8
        - Sidechain Multiband Compressor MidSide x8 - Sidechain Multi-band Kompressor MidSide x8
        - Sidechain Multiband Compressor Mono x8 - Sidechain Multi-band Kompressor Mono x8
        - Sidechain Multiband Compressor Stereo x8 - Sidechain Multi-band Kompressor Stereo x8
        - Sidechain Limiter Mono - Sidechain-Begrenzer Mono
        - Sidechain Limiter Stereo - Sidechain-Begrenzer Stereo
        - Sidechain Dynamic Processor LeftRight - Sidechain-Dynamikprozessor LeftRight
        - Sidechain Dynamic Processor MidSide - Sidechain-Dynamikprozessor MidSide
        - Sidechain Dynamic Processor Mono - Sidechain-Dynamikprozessor Mono
        - Sidechain Dynamic Processor Stereo - Sidechain-Dynamikprozessor Stereo
        - Sidechain Expander LeftRight - Sidechain-Expander LeftRight
        - Sidechain Expander MidSide - Sidechain-Expander MidSide
        - Sidechain Expander Mono - Sidechain-Expander Mono
        - Sidechain Expander Stereo - Sidechain-Expander Stereo
        - Sidechain Gate LeftRight - Sidechain-Gate LeftRight
        - Sidechain Gate MidSide - Sidechain-Gate MidSide
        - Sidechain Gate Mono - Sidechain-Gate Mono
        - Sidechain Gate Stereo - Sidechain-Gate Stereo
        - Sidechain Compressor LeftRight - Sidechain-Kompressor LeftRight
        - Sidechain Compressor MidSide - Sidechain-Kompressor MidSide
        - Sidechain Compressor Mono - Sidechain-Kompressor Mono
        - Sidechain Compressor Stereo - Sidechain-Kompressor Stereo
        - Slapback Delay Mono - Slapback-Delay Mono
        - Slapback Delay Stereo - Slapback-Delay Stereo
        - Spectrum Analyzer x1 - Spektrumanalysator x1
        - Spectrum Analyzer x12 - Spektrumanalysator x12
        - Spectrum Analyzer x16 - Spektrumanalysator x16
        - Spectrum Analyzer x2 - Spektrumanalysator x2
        - Spectrum Analyzer x4 - Spektrumanalysator x4
        - Spectrum Analyzer x8 - Spektrumanalysator x8
        - Surge Filter Mono - Sprungfilter Mono
        - Surge Filter Stereo - Sprungfilter Stereo
        - Trigger MIDI Mono - Triggersensor MIDI Mono
        - Trigger MIDI Stereo - Triggersensor MIDI Stereo
        - Trigger Mono - Triggersensor Mono
        - Trigger Stereo - Triggersensor Stereo
        - Delay Compensator Mono - Verzögerungsausgleicher Mono
        - Delay Compensator Stereo - Verzögerungsausgleicher Stereo
        - Delay Compensator x2 Stereo - Verzögerungsausgleicher x2 Stereo
      '';
      homepage = "https://lsp-plug.in";
      maintainers = with maintainers; [ magnetophon ];
      license = licenses.gpl2;
      platforms = platforms.linux;
    };
}
```

**Comment by sadko4u** [comment]
Yes, can confirm the problem related to LSP Plugin Framework.
This patch should fix it:
https://github.com/lsp-plugins/lsp-plugin-fw/commit/6197e64939b63998e44a6b240546d60a2608d106

I also have updated the `hotfix` branches.

**Comment by magnetophon** [comment]
Great, thanks!

Unfortunately, I don't know how to test this;
NixOS has two phases in building a pkg:
- Getting the source
- Actually building
During the second phase, no network acces is allowed.
Therefore I am using the complete source tarbal: https://github.com/sadko4u/lsp-plugins/releases/download/1.2.0/lsp-plugins-src-1.2.0.tar.gz

I'm now trying to apply that commit "manually" to the tarbal.

**Comment by sadko4u** [comment]
Is it possible to apply patch after unpacking the tarball? I think it is possible for many package building scripts.

**Comment by magnetophon** [comment]
Yes, applying a patch after the unpack is easy, but I haven't figured out how to apply a patch to a submodule.

**Comment by magnetophon** [comment]
I managed to apply the patch, but I'm still getting the same error: ``[ERR] Could not find JACK plugin core library``.

**Comment by sadko4u** [comment]
Hmm. Just tired to build with 'PREFIX=/some/install/path'. Seems that binaries are working well.
Could you dig into the build tree and look the contents of the following file:
`lsp-plugins/.build/target/lsp-plugin-fw/jack/.settings.mk`

It should contain the LSP_INSTALL_PREFIX definition like here:
```
# Auto-generated script, do not edit
EXT_ARTIFACT_NAME=lsp-plugins
EXT_ARTIFACT_GROUP=lsp-plugins
EXT_PREFIX=lsp-plugins-
EXT_OBJS=  /home/sadko/eclipse/lsp-plugins/.build/target/lsp-common-lib/lsp-common-lib.o
EXT_CFLAGS=-DLSP_PLUGIN_PACKAGE_MAJOR=1 -DLSP_PLUGIN_PACKAGE_MINOR=2 -DLSP_PLUGIN_PACKAGE_MICRO=0 -DLSP_PLUGIN_PACKAGE_BRANCH=\"\" -DLSP_INSTALL_PREFIX=\"/some/install/path\"
EXT_CXXFLAGS=-DLSP_PLUGIN_PACKAGE_MAJOR=1 -DLSP_PLUGIN_PACKAGE_MINOR=2 -DLSP_PLUGIN_PACKAGE_MICRO=0 -DLSP_PLUGIN_PACKAGE_BRANCH=\"\" -DLSP_INSTALL_PREFIX=\"/some/install/path\"
EXT_LDFLAGS=-lpthread -ldl 
EXT_INCLUDE=  -I"/home/sadko/eclipse/lsp-plugins/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN -I"/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include" -DLSP_PLUGIN_FW_BUILTIN

```

**Comment by sadko4u** [comment]
And the root project, too:
https://github.com/sadko4u/lsp-plugins/commit/dbf4dc44404f0f9abed1cfbbff38fb3cc10b72cc

**Comment by magnetophon** [comment]
I applied the other 2 patches as well; no luck.

Here's the content of ``lsp-plugins/.build/target/lsp-plugin-fw/jack/.settings.mk`` :
```
# Auto-generated script, do not edit
EXT_ARTIFACT_NAME=lsp-plugins
EXT_ARTIFACT_GROUP=lsp-plugins
EXT_PREFIX=lsp-plugins-
EXT_OBJS=  /build/lsp-plugins/.build/target/lsp-common-lib/lsp-common-lib.o
EXT_CFLAGS=-DLSP_PLUGIN_PACKAGE_MAJOR=1 -DLSP_PLUGIN_PACKAGE_MINOR=2 -DLSP_PLUGIN_PACKAGE_MICRO=0 -DLSP_PLUGIN_PACKAGE_BRANCH=\"\"
EXT_CXXFLAGS=-DLSP_PLUGIN_PACKAGE_MAJOR=1 -DLSP_PLUGIN_PACKAGE_MINOR=2 -DLSP_PLUGIN_PACKAGE_MICRO=0 -DLSP_PLUGIN_PACKAGE_BRANCH=\"\"
EXT_LDFLAGS=-lpthread -ldl
EXT_INCLUDE=  -I"/build/lsp-plugins/modules/lsp-common-lib/include" -DLSP_COMMON_LIB_BUILTIN -I"/build/lsp-plugins/modules/lsp-plugin-fw/include" -DLSP_PLUGIN_FW_BUILTIN
```

**Comment by sadko4u** [comment]
It seems that your patch has not been applied to the source code or applied in a wrong way.
Is it possible for you to check that source code has been properly patched after unpacking?

**Comment by magnetophon** [comment]
Yes, that fixes it.  :)
Thanks for your patience!

**Comment by sadko4u** [comment]
@magnetophon 
A plea for future: please don't reopen issues because they are linked to specific release.
Better is to open the new one and link it with old issue.

**Comment by magnetophon** [comment]
OK, will do.
