### ISSUE TITLE
lsp-plugins-graph-equalizer-x16-ms has the freq labels of lsp-plugins-graph-equalizer-x32-ms

### ISSUE THREAD

**Issue by magnetophon** [sadko4u/lsp-plugins#64]
The other 16 band eq's are fine, but the ms one has 16-500 Hz instead of 16-16k.

**Comment by sadko4u** [comment]
Ah, that's result of the refactoring.

**Comment by sadko4u** [comment]
Pushed commit to the **devel** branch, please verify: 36a096a472e475c6452094d4f9ea0b62644cea84

**Comment by magnetophon** [comment]
Fixed!

**Comment by sadko4u** [comment]
Sad that this was not included into the 1.1.13 release.
Moved changes to the **hotfix** branch which can be used as patch source for master.

**Comment by sadko4u** [comment]
Please don't close issues until they will be published in the release.

**Comment by sadko4u** [comment]
Changes available in 1.1.14 release!
