### ISSUE TITLE
Adding XDG desktop files for all standalone JACK applications

### ISSUE THREAD

**Issue by sadko4u** [sadko4u/lsp-plugins#66]
Things left to be done from the pull request https://github.com/sadko4u/lsp-plugins/pull/63

The *.desktop files are to be installed to /usr/share/applications/, the lsp-plugins.directory to /usr/share/desktop-directories and the lsp-plugin.menu to /etc/xdg/menus/applications-merged/ on a target system.

Adding (preferably) a vector graphic (lsp-plugins.svg) to be used as an icon, that can be installed to /usr/share/icons/hicolor/scalable/apps/

**Comment by trebmuh** [comment]
As said on #63, ping me when done, then I'll make a French translation.

**Comment by sadko4u** [comment]
The changes from pull request have been merged into **github-issue-66** branch.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 1b4817703194c664b7262865034445f129d00ace

**Comment by sadko4u** [comment]
Removed branch **github-issue-66**

**Comment by sadko4u** [comment]
Changes available in 1.1.14 release!

**Comment by Vascom** [comment]
So lsp-plugins.svg not added?
And lsp-plugins.png installed in /usr/share/icons/hicolor/scalable/apps/ instead of /usr/share/icons/hicolor/128x128/apps

It is bug in 1.1.14? Should I create new issue for it?

**Comment by sadko4u** [comment]
@Vascom 
Please look at #83 and try to build from **github-issue-83** branch.
