### ISSUE TITLE
Dropdown menues are displayed in the wrong place.

### ISSUE THREAD

**Issue by magnetophon** [sadko4u/lsp-plugins#7]
I'm using a tiling windowmanager called i3, and when I use one of the dropdown menus in the plugins (both standalone and LV2), they appear in the wrong place.

Some of them go to the top of the screen, and some go to the bottom, appearing even under the WM status bar.

**Comment by sadko4u** [comment]
Currently I have no idea about this, never tried this WM.
There can be two problems: the screen resolution is reported improperly or the position of windows (which are content of drop-down meus) is not updated by window manager due some currently unknown reasons.

**Comment by magnetophon** [comment]
To me it looks like the WM is trying to tile the dropdown windows.
https://imgur.com/a/Hh5RPyJ

**Comment by magnetophon** [comment]
That's correct.

**Comment by sadko4u** [comment]
Seems that lines mentioning **X11__NET_WM_WINDOW_TYPE_DOCK;** in this block:
https://github.com/sadko4u/lsp-plugins/blob/db70248bc4a528dc51586638e9cd71259cf14b7a/src/ui/ws/x11/X11Window.cpp#L429

should be removed.
Please comment-out/remove them, rebuild and test. Hope this helps.

**Comment by magnetophon** [comment]
Yes, that fixes the issue, thanks!

**Comment by sadko4u** [comment]
I'll close this topic when changes reach the 'devel' branch.

**Comment by sadko4u** [comment]
Verified on my machine, committed into **devel** branch: 51fc170e8b0b2a7bfd00a815a51a5d376725f37e

**Comment by magnetophon** [comment]
Thanks!

**Comment by jfdelaquis** [comment]
I don,t mean to revive an old thread but I am currently using version 1.2.3 under arch linux with Awesome WM. Something similar is happening, but the drop down menus are the correct size but appearing at the top left of the screen (floating window mode). I can't get more info using xprop since the window representing the dropdown disappears when I click outside of it.
