### ISSUE TITLE
Plugin request: oscilloscope?

### ISSUE THREAD

**Issue by mxmilkiib** [sadko4u/lsp-plugins#70]
I am specifically interested in a oscilloscope with an an inline-display to use in Carla with newer LV2/JACK CV features whilst constructing modular synths. Being able to drive the X and Y would also be [handy](https://www.reddit.com/r/oscilloscopemusic/top/).

**Comment by sadko4u** [comment]
What basic functions would you like to use in the plugin?

**Comment by sadko4u** [comment]
Seems that @CrocoDuckoDucks is interested in implementing such plugin.
I'll assign a topic to him.

**Comment by CrocoDuckoDucks** [comment]
Development has [started](https://github.com/sadko4u/lsp-plugins/tree/oscilloscope). No commits yet, implementing the basics and XY display will keep me busy for a while.

**Comment by sadko4u** [comment]
As I currently see, the oscilloscope should provide the following functions:
- different plugin instances with 1, 2 and 4 XY channels;
- all channels should bypass the signal;
- possibility to connect any X/Y channel to one of built-in oscillators;
- possibility to display the result of applying ADD, SUB and MUL functions (possible also MID and SIDE) between two selected channels which will allow us to configure it as a **vector scope** often useful in Mid/Side signal analysis.
- possibility to set global x1-x8 oversampling for more accurate drawings of figures like Lissajous curves.

**Comment by mxmilkiib** [comment]
@CrocoDuckoDucks Thank you for working on this btw! Is it worth my building to test things out yet, or should I hold off for a while longer?

**Comment by CrocoDuckoDucks** [comment]
@mxmilkiib Hey there! I am definitely taking more time than I anticipated to get this done, it was redesigned a few times due to to my first design decisions being flawed. At the moment it is not at a testable state (no waveform plot on the screen): I am still making sure the internals are solid.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: a58b2fb0b90f73f5f0e61f626ba3674ffec27292

**Comment by sadko4u** [comment]
Available in 1.1.30
