### ISSUE TITLE
Add bandpass filtering to sidechain

### ISSUE THREAD

**Issue by ampetrosillo** [sadko4u/lsp-plugins#75]
A bandpass filter, adjustable for centre frequency and/or width, would allow a compressor or gate to focus on a certain range of frequencies without being affected by unrelated spill (eg. cymbals in snare/tom mics). This is already achievable using sidechain gates and compressors and using a filtered copy of the source signal as trigger, but having the feature in the plugin would speed up workflow.

**Comment by sadko4u** [comment]
Merged changes to **devel** branch: 5dc8d9c36826838e268718c4d69a96bd68a74434

**Comment by sadko4u** [comment]
Available in 1.1.22 release!

**Comment by ampetrosillo** [comment]
Thanks a lot!
