### ISSUE TITLE
non-scalable image installed to scalable image location

### ISSUE THREAD

**Issue by dvzrv** [sadko4u/lsp-plugins#83]
Hi! When packaging 1.1.14 I saw that now a PNG is installed to the scalable location (
`usr/share/icons/hicolor/scalable/apps/lsp-plugins.png`).
That location is reserved for scalable images though (i.e. SVG).

**Comment by sadko4u** [comment]
Wow. I've just noticed tha *.svg files are also missing in the repository.
I'll fix this.

**Comment by sadko4u** [comment]
Try to build from **github-issue-83** branch.

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 15c83f6e9f0a5480e402ab191244a0085f0bd8cf

**Comment by sadko4u** [comment]
Removed **github-issue-83** branch

**Comment by sadko4u** [comment]
Available in 1.1.15 release!
