### ISSUE TITLE
xdg .desktop files have invalid category

### ISSUE THREAD

**Issue by eeickmeyer** [sadko4u/lsp-plugins#88]
[0001-Fix-invalid-category.patch.txt](https://github.com/sadko4u/lsp-plugins/files/4398211/0001-Fix-invalid-category.patch.txt)
lsp-plugins is not a valid xdg desktop category. As such, I have attached a patch that will fix it to the proper category of AudioVideo;Audio;. I hope this helps.

**Comment by sadko4u** [comment]
@eeickmeyer
Hmm, I've already tried the similar patch. This will publish all program links directly into Audio group. I believe that's not a good idea since other applications will get lost in about 100+ program links.

In our case, all program links will be grouped into 'LSP Plugins' bundle:
![image](https://user-images.githubusercontent.com/12834464/77845072-8b19d780-71b4-11ea-8c0f-9a62d1289e4c.png)

**Comment by eeickmeyer** [comment]
In that case, you might be able to make it X-lsp-plugins, but making your own category doesn't work with all operating systems. I can verify that, but making your own category that's not part of the freedesktop.org standard isn't allowed.

Right now, I have to do that massive patch in order to keep it standards-compliant in Ubuntu, which is not ideal. In Ubuntu Studio, we have a way of customizing the Audio Production menu that makes it standards-compliant while not overcluttering other menus. You can check out launchpad.net/ubuntustudio-menu if you want to see how we do that.

That said, I'm sure we can figure out a compromise that is both standards-compliant and allows you to customize the way you want. X-lsp-plugins might be the way to go, I just need to verify that.

**Comment by sadko4u** [comment]
@eeickmeyer 
Thanks. I'm not very familiar with XDG standard, so I'll mostly rely on your contribution and contribution from @dvzrv and @DNS777 .
According to what I currently understand, @dvzrv has defined a **lsp-plugins** category in the **lsp-plugins.menu** file which is also installed by the build system. So probably this should work as expected.

**Comment by dvzrv** [comment]
[From the spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html):

> Categories in which the entry should be shown in a menu (for possible values see the Desktop Menu Specification).

Looking at the menu spec there, it gets quite interesting... it seems as if they introduce the custom menu and then hardcode all the namespaced XDG desktop files into it: https://specifications.freedesktop.org/menu-spec/latest/apcs03.html

```
          <!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
          "http://www.freedesktop.org/standards/menu-spec/menu-1.0.dtd">
          <Menu>
            <Name>Applications</Name>
            <Menu>
              <Name>WebMirror</Name>
              <Directory>shinythings-webmirror.directory</Directory>
              <Include>
                <Filename>shinythings-webmirror.desktop</Filename>
                <Filename>shinythings-webmirror-admin.desktop</Filename>
              </Include>
            </Menu>
```

Closing, the desktop files should not mention a `Categories` entry but instead be pulled in by the custom menu item.
I did not know that!

**Comment by eeickmeyer** [comment]
I was able to create a custom X-lsp-plugins category, but it did require a "main" category, so I gave it the main category of "Audio". With this patch, all .desktop files have `Categories=Audio;X-lsp-plugins;` as the category entry.

[0001-Fix-invalid-category.patch.txt](https://github.com/sadko4u/lsp-plugins/files/4399212/0001-Fix-invalid-category.patch.txt)

While the custom lsp-plugins.menu may be existing, unfortunately, the .desktop files must still be XDG compliant. This latest (attached) patch keeps the .desktop files XDG compliant.

**Comment by sadko4u** [comment]
@dvzrv Do I right understand that:
1. I need to mention all *.desktop files in the 'lsp-plugins.menu' file?
2. I am free to remove lsp-plugins from the 'Category' parameter now?

**Comment by eeickmeyer** [comment]
@sadko4u If you'd like, you're more than welcome to copy/paste the entries from what I did in ubuntustudio-menu:

https://git.launchpad.net/ubuntustudio-menu/tree/etc/xdg/menus/applications-merged/studio.menu

**Comment by sadko4u** [comment]
Please try patch committed into **github-issue-88** branch: 3f0ff14d203f6e9ab826e35942f67f84fe0a1e22

Seems it's being properly working on my KDE installations (both menus):
![image](https://user-images.githubusercontent.com/12834464/77860921-8daf1800-721a-11ea-9f29-8120965ede65.png)

![image](https://user-images.githubusercontent.com/12834464/77860934-a3244200-721a-11ea-88c1-8fd296a95e0d.png)

Tested on Virtual machine with 32-bit openSUSE Tumbleweed + KDE.

**Comment by eeickmeyer** [comment]
I can confirm that the patch does, indeed, work. In fact, it might be good enough for me to eliminate my individual file call-outs and simply add the entire .directory file inside our "Audio Production/Effects" submenu, essentially making it a submenu of that.

**Comment by sadko4u** [comment]
@dvzrv Can we consider that the latest changes have solved the issue?

**Comment by dvzrv** [comment]
Maybe it would be worth exploring, whether setting `OnlyShowIn` is an option, too.
https://specifications.freedesktop.org/menu-spec/latest/ar01s03.html

Because, if I understand this correctly, listing several `Categories` will lead to the entries showing up in several menus, or does the explicit menu item `lsp-plugins.menu` prevent this now?

All in all, if this works, ship it!

**Comment by sadko4u** [comment]
@dvzrv Do I right understand that it should be:

```
OnlyShowIn:X-lsp-plugins;
```

?

**Comment by sadko4u** [comment]
Merged changes into **devel** branch: 8cf6793edaa191fb8b92be017d2335b5e83d07f8

**Comment by dvzrv** [comment]
On 2020-03-30 07:39:38 (-0700), Vladimir Sadovnikov wrote:
> @dvzrv Do I right understand that it should be:
> 
> ```
> OnlyShowIn:X-lsp-plugins;
> ```

That's how I understand it.

**Comment by sadko4u** [comment]
At least I need to try it.

**Comment by mikhailnov** [comment]
OnlyShowIn is for DEs like KDE, GNOME,XFCE etc.
> The OnlyShowIn field is a list of strings identifying the environments that should display a given menu item

> Categories=Audio;X-lsp-plugins;

Why does not this make a ton of desktop files be shown in the "Audio" category? I think they will be shown there in some configurations but I am not very well familiar with this part of XDG.

**Comment by eeickmeyer** [comment]
> Why does not this make a ton of desktop files be shown in the "Audio" category? I think they will be shown there in some configurations but I am not very well familiar with this part of XDG.

You are correct, this does make a ton of "Audio" menu entries. This is why I basically "blacklisted" them in the [Ubuntu Studio menu.](https://git.launchpad.net/ubuntustudio-menu/tree/etc/xdg/menus/applications-merged/studio.menu). If you scroll through that link, you'll see the same files listed twice: once where they are blacklisted, and another time where they are wanted.

**Comment by mikhailnov** [comment]
Then it is not a solution for upstream, because most people do not have Ubuntu Studio menu installed, including the ones who install lsp-plugins package outside Ubuntu Studio. Maybe `Categories=X-lsp-plugins;` will be enough despite breaking full compilancy with XDG by not having a "main" category? What is the purpose of trying to be 100% compilant here?

**Comment by eeickmeyer** [comment]
> What is the purpose of trying to be 100% compilant here?
[This is why.](https://lintian.debian.org/tags/desktop-entry-invalid-category.html)

If not 100% compliant, the package is not allowed in Debian or Ubuntu. Remember, I report to people higher-up than myself.

**Comment by mikhailnov** [comment]
I think that an exception would be a good choice here. But, if it is not possible or if there is any other good reason to follow XDG specifications so strictly, commit https://github.com/sadko4u/lsp-plugins/commit/8cf6793edaa191fb8b92be017d2335b5e83d07f8 should be extended to not only `<include>`, but to also exclude plugins from the "Audio" category to make them invisible there.
Maybe specifying "Audio" would really help to understand that these applications do something with audio, but I don't know why it may be needed.

**Comment by eeickmeyer** [comment]
It could be done by making a /etc/xdg/menu/applications-merged/lsp-plugins.menu which could blacklist the desktop entries from the Audio menu. Not trivial, but it can be done in a similar fashion to how I did it in ubuntustudio-menu.

**Comment by sadko4u** [comment]
@mikhailnov 
So, can you provide a proper solution?

P.S. It's strange that XDG specificaiton is so complicated for doing so simple things.

**Comment by sadko4u** [comment]
Added OnlyShowIn:X-lsp-plugins; for all desktop entries: a6ac014a92c88143956f453903ac15eb870794af

In KDE just works fine. Please check.

**Comment by sadko4u** [comment]
In Ubuntu I just get this:
![image](https://user-images.githubusercontent.com/12834464/78009181-4ecbb000-7349-11ea-9e10-6803e8eff483.png)

Don't know how correct it is for GNOME desktop but personally for me it is awful.
Moreover, DE doesn't display icons.

**Comment by mikhailnov** [comment]
31.03.2020 12:06, Vladimir Sadovnikov пишет:
>
> Added OnlyShowIn:X-lsp-plugins; for all desktop entries: a6ac014 <https://github.com/sadko4u/lsp-plugins/commit/a6ac014a92c88143956f453903ac15eb870794af>
>
> In KDE just works fine. Please check.
>
As far as I understand, it is probably a KDE bug. Here "X-lsp-plugins" must be treated as a Desktop Environment name, so most DEs must just not show it at all. Am I incorrect?

**Comment by mikhailnov** [comment]
31.03.2020 10:53, Vladimir Sadovnikov пишет:
>
> @mikhailnov <https://github.com/mikhailnov>
> So, can you provide a proper solution?
>
I struggle understanding XDG menu XML layouts, Erick has written above what should be done to avoid just removing Audio from categories.

Maybe they should be put inside "<Not>" tag as here: https://git.launchpad.net/ubuntustudio-menu/tree/etc/xdg/menus/applications-merged/studio.menu#n155 ?

**Comment by mikhailnov** [comment]
31.03.2020 12:16, Vladimir Sadovnikov пишет:
>
> Don't know how correct it is for GNOME desktop but personally for me it is awful.
>
GNOME desktop does not sort applications by categories. "NotShowIn: GNOME" may help here, but I guess that some users of GNOME may want to sort applications to categories using not standard ways.

**Comment by mikhailnov** [comment]
Here is how it is in lsp-plugins 1.1.15 + XFCE + Whisker menu:
![image](https://user-images.githubusercontent.com/15802528/78019231-fbad2980-7357-11ea-8b18-b59ffb790974.png)

It is just fine.

**Comment by sadko4u** [comment]
> Maybe they should be put inside "<Not>" tag
Hmmm. I currently don't understand that XML programming logic. How does it work? Do we really need to use it?

Also, the open question is: why GNOME didn't show LSP icon for applications.

**Comment by sadko4u** [comment]
Interesting message today from openSUSE package manager:

Could not parse file "/usr/local/share/applications/in.lsp_plug.lsp_plugins_sc_mb_expander_lr.desktop": Key file contains line ?OnlyShowIn:X-lsp-plugins;? which is not a key-value pair, group, or comment                                  
Could not parse file "/usr/local/share/applications/in.lsp_plug.lsp_plugins_graph_equalizer_x16_mono.desktop": Key file contains line ?OnlyShowIn:X-lsp-plugins;? which is not a key-value pair, group, or comment                           
Could not parse file "/usr/local/share/applications/in.lsp_plug.lsp_plugins_sc_dyna_processor_mono.desktop": Key file contains line ?OnlyShowIn:X-lsp-plugins;? which is not a key-value pair, group, or comment                             
Could not parse file "/usr/local/share/applications/in.lsp_plug.lsp_plugins_spectrum_analyzer_x4.desktop": Key file contains line ?OnlyShowIn:X-lsp-plugins;? which is not a key-value pair, group, or comment

**Comment by v-fox** [comment]
> Interesting message today from openSUSE package manager:…

How did you manage to build and package it in SUSE ? OBS post-build "quality checks" get pissy about desktop-files like they are rootkits, 'brp-30-desktop' script fails the build on any "problem" and there is [no override, unlike other things](https://bugzilla.opensuse.org/show_bug.cgi?id=968153) that can actually break or compromise your system (stuff with rpmlint and `BuildRequires: -post-build-checks`).

It whines things like:
```
[   76s] calling /usr/lib/rpm/brp-suse.d/brp-30-desktop
[   76s] WARNING: '/usr/lib/rpm/brp-desktop.data/suse-screensavers.menu' does not exist
[   76s] WARNING: '/usr/lib/rpm/brp-desktop.data/applications-kmenuedit.menu' does not exist
[   76s] WARNING: '/usr/lib/rpm/brp-desktop.data/custom.menu' does not exist
[   78s] ERROR: No sufficient Category definition "Audio;X-lsp-plugins;" in /home/abuild/rpmbuild/BUILDROOT/lsp-plugins-1.1.15~20200403T160101.14175-57.1.x86_64//usr/share/applications/in.lsp_plug.lsp_plugins_spectrum_analyzer_x12.desktop 
[   78s] Please refer to https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories
```
Unless you do something like:
```
BuildRequires:  update-desktop-files
…
%install
…
for desktop in %{buildroot}%{_datadir}/applications/*.desktop; do
%suse_update_desktop_file -r ${desktop} AudioVideo Music
done
```
But that clutters the menu.

**Comment by sadko4u** [comment]
@v-fox 
I haven't build package for OpenSUSE. I've just noticed this message while installing another applications. That's why I decided first to correct and then to remove OnlyShowIn parameter in *.desktop files.

**Comment by sadko4u** [comment]
Available in 1.1.17 release!

**Comment by BrunoVernay** [comment]
In Fedora 32 - Gnome, the LSP desktop entries:

- are flooding the "Application Overview" and since Gnome is shortening their names, we cannot even distinguish between about 3 "Mid-Side Stereo ..." labels. 
- In the Applications Menu they are all in "Sound & Video", making others apps hard to find. At least there is more room for their names.

I do not know if I should create a new issue? (here or in Gnome ...?)

- At least they should not show up in the "Application Overview", because their truncated names makes it unusable even if they were in a sub folder.
- In the Application Menu, I do not know why there is no "lsp-plugin" sub-folder

In the end it looks like Gnome is not designed to handle 100 desktops entries. There is some kind of mismatch here.  I will try to ask in Gnome & Fedora forums.  (Still it would be nice to keep a thread running here too. This one or a new one if you prefer)

**Comment by sadko4u** [comment]
@BrunoVernay 
I believe it's a Gnome-specific issue.
All other DEs behave in usual way: they create a menu item called **LSP Plugins** and all other elements are sub-menus of this menu item:
![image](https://user-images.githubusercontent.com/12834464/83245570-95068980-a1a9-11ea-9a03-a6b93b0ae55b.png)

I don't know why GNOME designers decided that their use case is better but I can admit that currently we have troubles with GNOME environment only.

**Comment by mikhailnov** [comment]
I did not check but probably any DE or widget that tries to make a dashboard with application icons will have this problem: GNOME, Deepin, KDE's full screen dashboard, Unity, SimpleWelcome etc. (don't know how people work with such a mess in application menus)

**Comment by BrunoVernay** [comment]
Here [lsp-plugin-gnome.zip](https://github.com/sadko4u/lsp-plugins/files/4706160/lsp-plugin-gnome.zip) is a script that will create a folder in Gnome application overview (see screenshot).
It works and the script should be robust (can be launched multiple times, has some checks)
It relates to https://developer.gnome.org/AppFolders/ . 

I guess some documentation or Wiki could be helpful for the poor Gnome users ... Desktop INI file, menu XML files, directory INI files and now dconf database :-)  I can help write something concise.

**Comment by sadko4u** [comment]
@BrunoVernay 

Do you think that part of your script can be some way integrated into makefile build?

OMG. GTK doesn't follow X11 standard (related to Drag&Drop feature). Now GNOME developers don't follow the XDG standard.

**Comment by BrunoVernay** [comment]
I don't know makefile very well, but if you can call `gsetting`, you are good.

Now I would have let this for packagers. Looks like it is a job for RPM and DEB scripts, no?
And just provides this script in the documentation (could avoid the xslt if the script is generated with the list of desktop files)

**Comment by eeickmeyer** [comment]
@sadko4u 
> OMG. GTK doesn't follow X11 standard (related to Drag&Drop feature). Now GNOME developers don't follow the XDG standard.

Yeah, they haven't followed the XDG standard for the application selection since 3.0. GNOME wants to forge their own way and not rely on what they consider antiquated methods.

@BrunoVernay 
> Now I would have let this for packagers. Looks like it is a job for RPM and DEB scripts, no? And just provides this script in the documentation (could avoid the xslt if the script is generated with the list of desktop files)

As someone that packages for both RPM and DEB, that might actually be the way to go. At least providing the documentation would be amazingly helpful. I know I've been considering making some sort of category system for those that wish to use Ubuntu Studio's packages on Ubuntu proper (GNOME desktop), and since gsettings is how that is done. DEB packaging in particular has gsettings-overrides scripts, but I'm not 100% sure if RPM has an equivalent beyond the %post section which could call gsettings.

Honestly, it's an interesting discussion and concept, and something I do plan on digging into at some point in the near future, in particular for Ubuntu's case. I don't package lsp-plugins for Fedora, but I'm sure a similar concept can be applied there.
