### ISSUE TITLE
lsp-plugins VST on Ubuntu: sndfile not found

### ISSUE THREAD

**Issue by benhriv** [sadko4u/lsp-plugins#92]
Hi.

I should probably start by mentioning that I'm new to this. To GitHub, to Linux, all of it. I'm setting up my laptop to work in my studio with some FOSS that interest me a lot, so I installed Ubuntu 18.04.
So far, I've installed the software from KX Repositories (along with Reaper, which is my main DAW), and have been trying them out, but I'm interested in LSP Project.

I tried installing the Linux Studio Plugins from Sourceforge with no success, so I tried searching another alternative, and found this repository. I made it further than with the tar.gz file on sourceforge, but I'm stuck.

When I type make, the Terminal gives me this message:

Package sndfile was not found in the pkg-config search path.
Perhaps you should add the directory containing `sndfile.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sndfile' found
Package sndfile was not found in the pkg-config search path.
Perhaps you should add the directory containing `sndfile.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sndfile' found
Building core
  g++ stdlib/stdio.cpp
  g++ ICanvas.cpp
  g++ KVTDispatcher.cpp
  g++ io/IOutSequence.cpp
...

and, at the end:

files/AudioFile.cpp:66:14: fatal error: sndfile.h: No existe el archivo o el directorio
...

I don't know if I'm doing something wrong, but it won't let me make install. Is there anything I can do to fix this?

Thanks in advance, I remain at your service.

**Comment by benhriv** [comment]
Seems like the issue has been solved on another thread I didn't find on the first search. So I'm closing this one.

**Comment by sadko4u** [comment]
Hello. You had to install **sndfile** devel package to compile from source.
