### ISSUE TITLE
Some plugins have missing labels

### ISSUE THREAD

**Issue by ents-hqx** [sadko4u/lsp-plugins#95]
Some plugins are missing some labels. I spotted 2 of them, maybe more.
Slapback delay
Delay compensator

![missing_labels](https://user-images.githubusercontent.com/35730375/78533079-00a72880-77f1-11ea-9642-e069ff341b10.png)

**Comment by sadko4u** [comment]
Sad that you've noticed it after 1.1.17 release.

**Comment by sadko4u** [comment]
Created issue **github-issue-95** and fixed labels there: 5105cbafb2c52a27cc5e9d47420def94a3fc1be8

**Comment by sadko4u** [comment]
Fixed labels for parametric equalizers: 50457df4f4c44fe2c4d29f8a265f32a904fff26b

**Comment by sadko4u** [comment]
Merged missing labels into **devel**: 5c21645c6c029f043906e5c7bd9492c59ffcdb23

**Comment by sadko4u** [comment]
Available in 1.1.19 release.
