### ISSUE TITLE
Shared library installed in multiple locations

### ISSUE THREAD

**Issue by eeickmeyer** [sadko4u/lsp-plugins#98]
On Ubuntu and Debian, the packaging system (debhelper) automatically creates debug symbols based on shared libraries. In this case, the same library (lsp-plugins-r3d-glx.so) is installed in `usr/lib/lsp-plugins`, `usr/lib/lv2/lsp-plugins.lv2`, and `usr/lib/vst/lsp-plugins-lxvst-1.1.17` (which shouldn't include the version number at all, but that's a separate issue). This created a file conflict in the debug symbols.

The recommendation I have (and had to do) is remove the files from the lv2 and vst plugins and have those symlink to the file in usr/lib/lsp-plugins, which can be treated as a default directory for such shared libraries. That single file is installed in its own package and is a dependency of the standalone Jack clients, the lv2, and vst plugins.

**Comment by sadko4u** [comment]
The problem is that in some cases you can install different versions of LV2 and VST, for example, if they're packaged into different packages. And there may be a serious issue of some version to deal with the mentioned *.so file.

**Comment by eeickmeyer** [comment]
In this case, I have split the main package into separate subpackages. Any time the main source package is upgraded, so are the subpackages of the various types. This is true in any distribution where the main source package is upgraded.

Additionally, it's dangerous in any Linux operating system to have multiple versions of the same shared library unless that shared library is somehow embedded in the binary or containerized. I am not 100% sure that's possible in this case.

**Comment by sadko4u** [comment]
> Additionally, it's dangerous in any Linux operating system to have multiple versions of the same shared library unless that shared library is somehow embedded in the binary or containerized. 

I've already stepped on this rake. Now when VST plugin wrappers and JACK plugin wrappers search for LSP core library (which contains the code of all plugins, UI and other modules), they check the version string returned by the shared object file and use the only library that returns matching version string.

r3d-glx is an optional feature of LSP Plugins which allows to render 3D scenes in the UI. It is loaded and used if possible but consider it to be a part of the whole core library.

**Comment by eeickmeyer** [comment]
So, basically what you're saying is that this is something you're not willing or otherwise cannot take-on, is that correct? If so, I can continue fixing it in the packaging (doesn't require a patch, just scripting changes).

**Comment by sadko4u** [comment]
> So, basically what you're saying is that this is something you're not willing or otherwise cannot take-on, is that correct?

I'm currently working on the whole code tree decomposition of LSP Plugins.
As you see, there are already different modules decomposed:
https://github.com/sadko4u/lsp-common-lib
https://github.com/sadko4u/lsp-test-fw
https://github.com/sadko4u/lsp-dsp-lib

These modules have common but the enteirly another build lifecycle.
I think we can freeze this topic a bit until I get the entire lsp-plugins tree decomposed.
Let it currently hang opened. I'll trigger you when I'll be ready to discuss packaging details.

**Comment by eeickmeyer** [comment]
Excellent. :)

**Comment by sadko4u** [comment]
Available in 1.2.0.
