### ISSUE TITLE
Split LV2 bundle into smaller ones

### ISSUE THREAD

**Issue by falkTX** [sadko4u/lsp-plugins#99]
Hey there. Just a "small" request...

Currently your plugins package everything in a single LV2 bundle.
While this is easier to get all plugins at once, it is not always wanted.
Generally, the latency meter and other tools are not very useful all the time, so they could simply not be installed (saving space and making the plugin list less cluttered).

On some platforms, like MOD, users install LV2 plugins from a web interface.
Plugins are downloaded and installed in bundles, so installing lsp-plugins means getting 32+ new plugins.
It is likely that the user only wanted something in specific, but ends up with a whole collection.

I guess it is not as big of a problem for general distributions, but on systems where the number of plugins is made purposefully low (quality vs quantity kinda thing), it makes sense.
I personally see myself installing some plugins from LSP like the compressor and convolution reverb, but don't have the need for the rest (most of the time). And another user will have different requirements of course.

So I thought to drop the feature request here.
I expect the LSP project to keep growing, as I see you do a great job and keep adding more things.
Super nice, but just that would be great to split things so we can individually install stuff.
Does not have to be every individual plugin, the compressors being together make sense, for example.
Well, in any case, thanks.

PS: for reference, dpf-plugins, gx-plugins and x42-plugins do the split, but older plugin collections like rkr-lv2 and invada do not.

**Comment by sadko4u** [comment]
Currently it's not a trivial task.
But when I finally end up with decomposition of the whole project tree into separate modules, I probably will be possible to do it.
Anyway, I'll schedule this task for the 1.2.0 milestone

**Comment by sadko4u** [comment]
Some another thoughts against smaller bundles.
Each bundle requires:
- plugin code;
- DSP library;
- graphical toolkit library;
- set of built-in resources.

When all plugins are bundled together, the only one shared object contains all this stuff.
When all plugins are split into bundles, then each bundle will have it's own DSP library, graphical toolkit library and so on unless this code has been split into shared objects.

Packaging and distributing each bundle with a shared object may yield to another set of conflicts between shared objects used by different versions of plugins and installation difficulties from tarballs. Packaging all code into each separate bundle will require much more memory at runtime: around 4MB per bundle against ~5MB per whole collection of plugins.

**Comment by alex-tee** [comment]
i noticed that scanning is very slow for LSP plugins compared to other plugins, maybe this is related

**Comment by sadko4u** [comment]
@alex-tee the scanning is slow because each VST wrapper searches the location of vst core library and loads it. This requires some time, more than for other plugins.

**Comment by sadko4u** [comment]
Seems to be possible since 1.2.0 has been released but I have not performed a full check of this possibility.

**Comment by sadko4u** [comment]
Finished recent tests of plugin builds. Seems that all is working as expected.
Will be available in 1.2.1 release.

**Comment by sadko4u** [comment]
Available in 1.2.1.
